import {loadRegistry,registryIndex} from '../core/registry.js';
import {createPlatformResolver} from '../core/platform.js';
import {mountCard,unmountCard,bindCardRecovery} from '../core/card-host.js';
import {openApp as openHostedApp,closeApp as closeHostedApp} from '../core/app-host.js';
import {loadShellState,saveShellState,pruneMissingCards} from '../core/storage.js';
const $=s=>document.querySelector(s),desktop=$('#desktop'),drawer=$('#drawer'),library=$('#toolLibrary'),dock=$('#quickDock'),windowLayer=$('#windowLayer');const state={cards:[],registry:null,index:new Map(),platform:null},platformResolver=createPlatformResolver();state.platform=platformResolver.get();
const CARD_GAP=18,EDGE=24;
function title(c){return c?.name?.['zh-HK']||c?.name?.['zh-CN']||c?.id||'Card'}function description(c){return c?.description?.['zh-HK']||c?.description?.['zh-CN']||''}function sizeFor(c){return c?.defaultSize?.[state.platform.name]||{w:320,h:180}}function boundsFor(c){const p=state.platform.name,b=sizeFor(c),min=c?.minSize?.[p]||{w:Math.max(280,Math.round(b.w*.68)),h:Math.max(170,Math.round(b.h*.62))},max=c?.maxSize?.[p]||{w:960,h:900};return{min,max}}function clamp(v,min,max){return Math.min(max,Math.max(min,v))}function placed(id){return state.cards.some(x=>x.id===id)}function persist(){saveShellState({cards:state.cards})}function freeform(){return state.platform.name!=='mobile'}
function itemRect(item,card){const size=sizeFor(card),bounds=boundsFor(card);return{x:Number(item.x)||EDGE,y:Number(item.y)||EDGE,w:clamp(Number(item.w)||size.w,bounds.min.w,bounds.max.w),h:clamp(Number(item.h)||size.h,bounds.min.h,bounds.max.h)}}
function overlaps(a,b,gap=CARD_GAP){return!(a.x+a.w+gap<=b.x||b.x+b.w+gap<=a.x||a.y+a.h+gap<=b.y||b.y+b.h+gap<=a.y)}
function collides(rect,ignoreId=null,cards=state.cards){return cards.some(item=>{if(item.id===ignoreId)return false;const card=state.index.get(item.id);return card?overlaps(rect,itemRect(item,card)):false})}
function findOpenPosition(card,ignoreId=null,cards=state.cards){const probe=itemRect({id:card.id},card),usable=Math.max(probe.w+EDGE*2,(desktop.clientWidth||innerWidth)-96);const others=cards.filter(x=>x.id!==ignoreId&&state.index.has(x.id));const xs=[EDGE],ys=[EDGE];for(const item of others){const r=itemRect(item,state.index.get(item.id));xs.push(r.x+r.w+CARD_GAP);ys.push(r.y+r.h+CARD_GAP)}xs.sort((a,b)=>a-b);ys.sort((a,b)=>a-b);for(const y of ys)for(const x of xs){const rect={x,y,w:probe.w,h:probe.h};if(x+probe.w>usable)continue;if(!collides(rect,ignoreId,others))return{x,y}}const bottom=others.reduce((m,item)=>{const r=itemRect(item,state.index.get(item.id));return Math.max(m,r.y+r.h)},EDGE);return{x:EDGE,y:bottom+CARD_GAP}}
function normalizeLayout(){if(!freeform())return false;let changed=false;const settled=[];for(const item of state.cards){const card=state.index.get(item.id);if(!card)continue;const r=itemRect(item,card),bad=settled.some(other=>overlaps(r,itemRect(other,state.index.get(other.id))));if(!Number.isFinite(item.x)||!Number.isFinite(item.y)||bad){const p=findOpenPosition(card,item.id,settled);item.x=p.x;item.y=p.y;changed=true}else{item.x=r.x;item.y=r.y}if(item.w!==r.w||item.h!==r.h){item.w=r.w;item.h=r.h;changed=true}settled.push(item)}return changed}
function createHost(item,card){const host=document.createElement('article'),size=sizeFor(card),bounds=boundsFor(card);host.className='wd-card';host.dataset.cardHost='1';host.dataset.id=card.id;if(freeform()){const r=itemRect(item,card);Object.assign(item,r);Object.assign(host.style,{left:`${r.x}px`,top:`${r.y}px`,width:`${r.w}px`,height:`${r.h}px`,minWidth:`${bounds.min.w}px`,minHeight:`${bounds.min.h}px`,maxWidth:`${bounds.max.w}px`,maxHeight:`${bounds.max.h}px`});host.dataset.userSized='1'}host.innerHTML=`<header class="wd-card-head"><div class="wd-card-title"><span class="wd-card-icon">${card.icon||'•'}</span><span>${title(card)}</span></div><button data-remove="${card.id}" aria-label="移除">×</button></header><div class="wd-card-mount" data-card-mount></div>${freeform()?'<div class="wd-card-resize" data-resize-card role="button" aria-label="調整卡片大小" tabindex="0"></div>':''}`;host.querySelector('[data-card-mount]')._manifest=card;return host}
async function renderDesktop(){await Promise.all([...desktop.querySelectorAll('[data-card-mount]')].map(unmountCard));desktop.replaceChildren();if(normalizeLayout())persist();for(const item of state.cards){const card=state.index.get(item.id);if(!card)continue;const shell=createHost(item,card);desktop.appendChild(shell);await mountCard(shell.querySelector('[data-card-mount]'),card,state.platform.name)}bindCards();if(freeform()){const bottom=state.cards.reduce((m,item)=>{const card=state.index.get(item.id);if(!card)return m;const r=itemRect(item,card);return Math.max(m,r.y+r.h)},0);desktop.style.minHeight=Math.max(innerHeight,bottom+140)+'px'}}
function addCard(card){if(!card||placed(card.id))return;const size=sizeFor(card),item={id:card.id,w:size.w,h:size.h};if(freeform()){const p=findOpenPosition(card);item.x=p.x;item.y=p.y}state.cards.push(item);persist()}
function renderLibrary(q=''){const text=q.trim().toLowerCase(),cards=(state.registry?.cards||[]).filter(c=>!text||`${title(c)} ${description(c)} ${c.category}`.toLowerCase().includes(text));library.innerHTML=cards.length?cards.map(c=>{const added=placed(c.id);return `<div class="wd-tool${added?' is-added':''}"><span class="wd-card-icon">${c.icon||'•'}${added?'<i class="wd-tool-present" aria-hidden="true"></i>':''}</span><strong>${title(c)}</strong>${added?'<span class="wd-tool-spacer" aria-label="已在桌面"></span>':`<button class="wd-tool-add" data-add="${c.id}" aria-label="加入 ${title(c)}"><span aria-hidden="true"></span></button>`}</div>`}).join(''):'<p class="wd-empty">沒有結果</p>';library.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const c=state.index.get(b.dataset.add);addCard(c);renderDesktop();renderLibrary($('#toolSearch').value);drawer.classList.remove('open')})}
function renderDock(){const cards=(state.registry?.cards||[]).slice(0,3);dock.innerHTML=cards.map(c=>`<button data-quick-add="${c.id}" title="${title(c)}">${c.icon||'•'}</button>`).join('')+'<button data-action="library" title="功能中心">＋</button>'}
function bindCards(){desktop.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.cards=state.cards.filter(c=>c.id!==b.dataset.remove);persist();renderDesktop();renderLibrary($('#toolSearch').value)});if(!freeform())return;desktop.querySelectorAll('.wd-card-head').forEach(head=>{head.onpointerdown=e=>{if(e.target.closest('button'))return;const shell=head.closest('.wd-card'),item=state.cards.find(x=>x.id===shell.dataset.id),card=state.index.get(item.id),r=itemRect(item,card),sx=e.clientX,sy=e.clientY,ox=r.x,oy=r.y;head.setPointerCapture(e.pointerId);const move=ev=>{const maxX=Math.max(0,(desktop.clientWidth||innerWidth)-r.w-96),candidate={x:clamp(ox+ev.clientX-sx,0,maxX),y:Math.max(0,oy+ev.clientY-sy),w:r.w,h:r.h};if(collides(candidate,item.id))return;item.x=Math.round(candidate.x);item.y=Math.round(candidate.y);shell.style.left=item.x+'px';shell.style.top=item.y+'px';desktop.style.minHeight=Math.max(innerHeight,item.y+shell.offsetHeight+160)+'px'},up=()=>{persist();head.removeEventListener('pointermove',move);head.removeEventListener('pointerup',up)};head.addEventListener('pointermove',move);head.addEventListener('pointerup',up,{once:true})}});desktop.querySelectorAll('[data-resize-card]').forEach(handle=>{handle.onpointerdown=e=>{e.preventDefault();e.stopPropagation();const shell=handle.closest('.wd-card'),item=state.cards.find(x=>x.id===shell.dataset.id),card=state.index.get(shell.dataset.id),bounds=boundsFor(card),sx=e.clientX,sy=e.clientY,sw=shell.offsetWidth,sh=shell.offsetHeight;handle.setPointerCapture(e.pointerId);shell.dataset.userSized='1';const move=ev=>{const maxW=Math.min(bounds.max.w,Math.max(bounds.min.w,(desktop.clientWidth||innerWidth)-(item.x||0)-96)),w=Math.round(clamp(sw+ev.clientX-sx,bounds.min.w,maxW)),h=Math.round(clamp(sh+ev.clientY-sy,bounds.min.h,bounds.max.h)),candidate={x:item.x||0,y:item.y||0,w,h};if(collides(candidate,item.id))return;item.w=w;item.h=h;shell.style.width=w+'px';shell.style.height=h+'px';desktop.style.minHeight=Math.max(innerHeight,(item.y||0)+h+160)+'px'},up=()=>{persist();handle.removeEventListener('pointermove',move);handle.removeEventListener('pointerup',up)};handle.addEventListener('pointermove',move);handle.addEventListener('pointerup',up,{once:true})}})}
async function openApp(id){const card=state.index.get(id);if(!card)return;try{await openHostedApp(windowLayer,card,state.platform.name)}catch(e){console.error('[WebDesk V2 app]',e)}}document.addEventListener('webdesk:open-app',e=>openApp(e.detail?.id));document.addEventListener('click',e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(a==='library')drawer.classList.add('open');if(a==='close-drawer')drawer.classList.remove('open');const quick=e.target.closest('[data-quick-add]')?.dataset.quickAdd;if(quick&&!placed(quick)){addCard(state.index.get(quick));renderDesktop();renderLibrary($('#toolSearch').value)}});$('#toolSearch').addEventListener('input',e=>renderLibrary(e.target.value));bindCardRecovery(document,()=>state.platform.name);platformResolver.subscribe(async next=>{state.platform=next;await closeHostedApp(windowLayer);renderDesktop();renderLibrary($('#toolSearch').value)});async function boot(){try{state.registry=await loadRegistry();state.index=registryIndex(state.registry);state.cards=pruneMissingCards(loadShellState(),state.index).cards;if(!state.cards.length){const first=state.registry.cards[0];if(first){const size=sizeFor(first);state.cards=[{id:first.id,x:EDGE,y:EDGE,w:size.w,h:size.h}]}}if(normalizeLayout())persist();else persist();renderDock();renderLibrary();await renderDesktop()}catch(e){console.error(e);library.innerHTML='<p class="wd-empty">載入失敗</p>'}}boot();
