import{loadImageFile,releaseImage,renderPreview,exportCanvas,bindDropZone,cropRatioValue,centerCropRect,normalizeCropRect}from'../shared/image-service.js';
export async function mount({host,signal}){
 let state=null,cropRect=null,drag=null;
 host.innerHTML=`<style>.is-workspace{position:relative;display:inline-block;max-width:100%;max-height:100%;line-height:0;user-select:none;touch-action:none}.is-workspace img{display:block;max-width:100%;max-height:calc(100vh - 180px);object-fit:contain;box-shadow:0 8px 32px rgba(0,0,0,.16);pointer-events:none}.is-cropbox{position:absolute;box-sizing:border-box;border:2px solid white;outline:1px solid #1473e6;background:rgba(20,115,230,.08);cursor:move;touch-action:none}.is-cropbox:before,.is-cropbox:after{content:"";position:absolute;pointer-events:none}.is-cropbox:before{left:33.33%;right:33.33%;top:0;bottom:0;border-left:1px solid rgba(255,255,255,.7);border-right:1px solid rgba(255,255,255,.7)}.is-cropbox:after{top:33.33%;bottom:33.33%;left:0;right:0;border-top:1px solid rgba(255,255,255,.7);border-bottom:1px solid rgba(255,255,255,.7)}.is-cropbox i{position:absolute;width:14px;height:14px;border-radius:50%;background:white;border:2px solid #1473e6;box-sizing:border-box;z-index:2}.is-cropbox i[data-handle=nw]{left:-8px;top:-8px;cursor:nwse-resize}.is-cropbox i[data-handle=ne]{right:-8px;top:-8px;cursor:nesw-resize}.is-cropbox i[data-handle=sw]{left:-8px;bottom:-8px;cursor:nesw-resize}.is-cropbox i[data-handle=se]{right:-8px;bottom:-8px;cursor:nwse-resize}.is-controls .is-secondary{background:#e8eef8;color:#30445f}</style><section class="is-app is-desktop"><aside class="is-panel"><header><strong>Image Studio</strong><small>本機處理，不上傳</small></header><label class="is-drop" data-drop><input type="file" accept="image/*" data-file><b>選擇圖片</b><span>或拖放到這裡</span></label><div class="is-controls" hidden data-controls><label>裁切<select data-crop><option value="free">自由裁切</option><option value="1:1">1:1 正方形</option><option value="4:3">4:3</option><option value="3:4">3:4 直幅</option><option value="16:9">16:9 寬屏</option></select></label><button class="is-secondary" type="button" data-reset>重設裁切</button><label>寬度<input type="number" min="1" data-w></label><label>高度<input type="number" min="1" data-h></label><label class="is-lock"><input type="checkbox" checked data-lock>鎖定輸出比例</label><label>格式<select data-format><option value="image/png">PNG</option><option value="image/jpeg">JPEG</option><option value="image/webp">WebP</option></select></label><label>品質<input type="range" min="40" max="100" value="90" data-quality></label><button type="button" data-export>下載處理後圖片</button><small data-meta></small></div></aside><main class="is-stage"><div class="is-empty" data-empty>圖片預覽</div><div class="is-workspace" hidden data-workspace><img draggable="false" data-source><div class="is-cropbox" data-cropbox><i data-handle="nw"></i><i data-handle="ne"></i><i data-handle="sw"></i><i data-handle="se"></i></div></div><canvas data-canvas hidden></canvas></main></section>`;
 const file=host.querySelector('[data-file]'),drop=host.querySelector('[data-drop]'),controls=host.querySelector('[data-controls]'),canvas=host.querySelector('[data-canvas]'),empty=host.querySelector('[data-empty]'),workspace=host.querySelector('[data-workspace]'),source=host.querySelector('[data-source]'),box=host.querySelector('[data-cropbox]'),w=host.querySelector('[data-w]'),h=host.querySelector('[data-h]'),lock=host.querySelector('[data-lock]'),crop=host.querySelector('[data-crop]'),format=host.querySelector('[data-format]'),quality=host.querySelector('[data-quality]'),meta=host.querySelector('[data-meta]'),reset=host.querySelector('[data-reset]');
 const currentRatio=()=>cropRatioValue(crop.value)||(cropRect?.w/cropRect?.h)||state?.width/state?.height||1;
 const syncBox=()=>{if(!state||!cropRect)return;const dw=source.clientWidth,dh=source.clientHeight;if(!dw||!dh)return;box.style.left=`${cropRect.x/state.width*dw}px`;box.style.top=`${cropRect.y/state.height*dh}px`;box.style.width=`${cropRect.w/state.width*dw}px`;box.style.height=`${cropRect.h/state.height*dh}px`};
 const draw=()=>{if(!state||!cropRect)return;cropRect=normalizeCropRect(state.width,state.height,cropRect,cropRatioValue(crop.value));const src=renderPreview(canvas,state.image,Math.max(1,+w.value||cropRect.w),Math.max(1,+h.value||cropRect.h),{cropRect,cropRatio:cropRatioValue(crop.value)});cropRect=src;syncBox();meta.textContent=`原圖 ${state.width}×${state.height} · 裁切 ${Math.round(src.w)}×${Math.round(src.h)} @ ${Math.round(src.x)},${Math.round(src.y)} · 輸出 ${canvas.width}×${canvas.height}`};
 const syncOutputRatio=()=>{if(state&&lock.checked)h.value=Math.max(1,Math.round((+w.value||cropRect?.w||state.width)/currentRatio()))};
 w.oninput=()=>{syncOutputRatio();draw()};h.oninput=()=>{if(state&&lock.checked)w.value=Math.max(1,Math.round((+h.value||cropRect?.h||state.height)*currentRatio()));draw()};
 crop.onchange=()=>{if(!state)return;cropRect=centerCropRect(state.width,state.height,cropRatioValue(crop.value));syncOutputRatio();draw()};
 lock.onchange=()=>{syncOutputRatio();draw()};reset.onclick=()=>{if(!state)return;cropRect=centerCropRect(state.width,state.height,cropRatioValue(crop.value));w.value=Math.round(cropRect.w);h.value=Math.round(cropRect.h);draw()};
 const use=async f=>{try{releaseImage(state);state=await loadImageFile(f);if(signal?.aborted)return;crop.value='free';cropRect={x:0,y:0,w:state.width,h:state.height};w.value=state.width;h.value=state.height;controls.hidden=false;empty.hidden=true;workspace.hidden=false;source.src=state.url;await source.decode().catch(()=>{});draw()}catch(e){meta.textContent=e.message}};
 const pointerDown=e=>{if(!state||!cropRect)return;e.preventDefault();const handle=e.target?.dataset?.handle||'move',dw=source.clientWidth,dh=source.clientHeight;if(!dw||!dh)return;drag={id:e.pointerId,handle,x:e.clientX,y:e.clientY,rect:{...cropRect},sx:state.width/dw,sy:state.height/dh};box.setPointerCapture?.(e.pointerId)};
 const pointerMove=e=>{if(!drag||e.pointerId!==drag.id||!state)return;const dx=(e.clientX-drag.x)*drag.sx,dy=(e.clientY-drag.y)*drag.sy,r=drag.rect,min=Math.max(8,Math.min(state.width,state.height)*.02),ratio=cropRatioValue(crop.value);let next={...r};if(drag.handle==='move'){next.x=r.x+dx;next.y=r.y+dy}else{const east=drag.handle.includes('e'),south=drag.handle.includes('s'),ax=east?r.x:r.x+r.w,ay=south?r.y:r.y+r.h;let nw=Math.max(min,Math.abs((east?r.x+r.w+dx:r.x+dx)-ax)),nh=Math.max(min,Math.abs((south?r.y+r.h+dy:r.y+dy)-ay));if(ratio){if(nw/nh>ratio)nh=nw/ratio;else nw=nh*ratio}next.w=nw;next.h=nh;next.x=east?ax:ax-nw;next.y=south?ay:ay-nh}cropRect=normalizeCropRect(state.width,state.height,next,ratio);if(lock.checked)h.value=Math.max(1,Math.round((+w.value||cropRect.w)/(cropRect.w/cropRect.h)));draw()};
 const pointerUp=e=>{if(drag&&e.pointerId===drag.id){box.releasePointerCapture?.(e.pointerId);drag=null}};
 box.addEventListener('pointerdown',pointerDown);box.addEventListener('pointermove',pointerMove);box.addEventListener('pointerup',pointerUp);box.addEventListener('pointercancel',pointerUp);window.addEventListener('resize',syncBox);
 file.onchange=()=>file.files?.[0]&&use(file.files[0]);const unbind=bindDropZone(drop,use);host.querySelector('[data-export]').onclick=()=>state&&exportCanvas(canvas,{format:format.value,quality:(+quality.value||90)/100,filename:state.name});
 return()=>{releaseImage(state);unbind();window.removeEventListener('resize',syncBox);box.removeEventListener('pointerdown',pointerDown);box.removeEventListener('pointermove',pointerMove);box.removeEventListener('pointerup',pointerUp);box.removeEventListener('pointercancel',pointerUp)};
}
