import{loadImageFile,releaseImage,renderPreview,exportCanvas,bindDropZone,cropRatioValue}from'../shared/image-service.js';
export async function mount({host,signal}){
 let state=null,ratio=1;
 host.innerHTML=`<section class="is-app is-desktop"><aside class="is-panel"><header><strong>Image Studio</strong><small>本機處理，不上傳</small></header><label class="is-drop" data-drop><input type="file" accept="image/*" data-file><b>選擇圖片</b><span>或拖放到這裡</span></label><div class="is-controls" hidden data-controls><label>裁切<select data-crop><option value="free">原圖比例</option><option value="1:1">1:1 正方形</option><option value="4:3">4:3</option><option value="3:4">3:4 直幅</option><option value="16:9">16:9 寬屏</option></select></label><label>寬度<input type="number" min="1" data-w></label><label>高度<input type="number" min="1" data-h></label><label class="is-lock"><input type="checkbox" checked data-lock>鎖定比例</label><label>格式<select data-format><option value="image/png">PNG</option><option value="image/jpeg">JPEG</option><option value="image/webp">WebP</option></select></label><label>品質<input type="range" min="40" max="100" value="90" data-quality></label><button type="button" data-export>下載處理後圖片</button><small data-meta></small></div></aside><main class="is-stage"><div class="is-empty" data-empty>圖片預覽</div><canvas data-canvas hidden></canvas></main></section>`;
 const file=host.querySelector('[data-file]'),drop=host.querySelector('[data-drop]'),controls=host.querySelector('[data-controls]'),canvas=host.querySelector('[data-canvas]'),empty=host.querySelector('[data-empty]'),w=host.querySelector('[data-w]'),h=host.querySelector('[data-h]'),lock=host.querySelector('[data-lock]'),crop=host.querySelector('[data-crop]'),format=host.querySelector('[data-format]'),quality=host.querySelector('[data-quality]'),meta=host.querySelector('[data-meta]');
 const activeRatio=()=>cropRatioValue(crop.value)||ratio;
 const draw=()=>{if(!state)return;const cropRatio=cropRatioValue(crop.value),src=renderPreview(canvas,state.image,Math.max(1,+w.value||state.width),Math.max(1,+h.value||state.height),{cropRatio});const cropText=cropRatio?` · 裁切 ${Math.round(src.w)}×${Math.round(src.h)}`:'';meta.textContent=`原圖 ${state.width}×${state.height}${cropText} · 輸出 ${canvas.width}×${canvas.height}`};
 const onW=()=>{if(state&&lock.checked)h.value=Math.max(1,Math.round((+w.value||state.width)/activeRatio()));draw()},onH=()=>{if(state&&lock.checked)w.value=Math.max(1,Math.round((+h.value||state.height)*activeRatio()));draw()};w.oninput=onW;h.oninput=onH;
 crop.onchange=()=>{if(!state)return;const r=activeRatio();if(lock.checked)h.value=Math.max(1,Math.round((+w.value||state.width)/r));draw()};
 lock.onchange=()=>{if(state&&lock.checked){h.value=Math.max(1,Math.round((+w.value||state.width)/activeRatio()));draw()}};
 const use=async f=>{try{releaseImage(state);state=await loadImageFile(f);if(signal?.aborted)return;ratio=state.width/state.height;crop.value='free';w.value=state.width;h.value=state.height;controls.hidden=false;empty.hidden=true;canvas.hidden=false;draw()}catch(e){meta.textContent=e.message}};
 file.onchange=()=>file.files?.[0]&&use(file.files[0]);const unbind=bindDropZone(drop,use);host.querySelector('[data-export]').onclick=()=>state&&exportCanvas(canvas,{format:format.value,quality:(+quality.value||90)/100,filename:state.name});
 return()=>{releaseImage(state);unbind();file.onchange=null;w.oninput=null;h.oninput=null;crop.onchange=null;lock.onchange=null};
}
