import{layers,layerById,fetchPointWeather,fetchWeatherGrid,fetchWindField,supportsVisualOverlay,supportsWindField,DEFAULT_CENTER,TIMELINE_HOURS,timelineLabel}from'../shared/global-weather-service.js';
import{mountMap,basemaps}from'../shared/map-engine.js';
import{imageryModes,createImageryController}from'../shared/imagery-controller.js';
export async function mount({host,signal}){
  let active='wind',offsetHours=0,data=null,timer=0,mapApi=null,imageryApi=null,resizeTimer=0,weatherAbort=null,overlayAbort=null,overlayTimer=0,overlayMeta=null,imageryState={state:'off',mode:'off'},view={lat:DEFAULT_CENTER.lat,lon:DEFAULT_CENTER.lon,zoom:4.1},mapState={state:'loading',source:'OpenFreeMap'};
  host.innerHTML=`<section class="gw-app gw-mobile-app"><div class="gw-mobile-map" data-map aria-label="全球天氣地圖"></div><div class="gw-mobile-title"><strong>全球天氣</strong><span data-map-status>地圖載入中…</span></div><nav class="gw-mobile-layers">${layers.map((l,i)=>`<button type="button" data-layer="${l.id}" class="${i?'':'on'}">${l.label}</button>`).join('')}</nav><nav class="gw-mobile-timeline" aria-label="預報時間">${TIMELINE_HOURS.map((h,i)=>`<button type="button" data-time="${h}" class="${i?'':'on'}">${timelineLabel(h)}</button>`).join('')}</nav><section class="gw-mobile-sheet"><div class="gw-mobile-readout" data-readout>讀取即時資料…</div><nav class="gw-mobile-bases">${basemaps.map(b=>`<button type="button" data-base="${b.id}" class="${b.id==='weather'?'on':''}">${b.label}</button>`).join('')}${imageryModes.map(m=>`<button type="button" data-imagery="${m.id}" class="${m.id==='off'?'on':''}">${m.label}</button>`).join('')}</nav><small data-source>資料載入中…</small></section></section>`;
  const readout=host.querySelector('[data-readout]'),source=host.querySelector('[data-source]'),mapStatus=host.querySelector('[data-map-status]'),mapNode=host.querySelector('[data-map]');
  const fieldText=()=>{if(!overlayMeta)return' · 場資料載入中…';return supportsWindField(active)?` · ${active==='gust'?'陣風':'風'}場 ${overlayMeta.sampleCount} 點`:` · 圖層 ${overlayMeta.sampleCount} 點`};
  const imageryText=()=>{if(imageryState.state==='off')return'';const t=imageryState.updatedAt?String(imageryState.updatedAt).replace('T',' ').replace('Z','').slice(0,16):'—';if(imageryState.state==='loading')return` · ${imageryState.source||'影像'} 載入中`;if(imageryState.state==='fallback')return` · ${imageryState.source} ${t}（備援）`;if(imageryState.state==='ready')return` · ${imageryState.source} ${t}`;return` · ${imageryState.source||'影像'}不可用`};
  const paint=()=>{if(!data)return;const l=layerById(active),v=data.summary[active],t=String(data.updatedAt||'').replace('T',' ').slice(5,16)||'—';readout.textContent=`${l.label} ${v}${v==='—'?'':' '+l.unit} · ${timelineLabel(offsetHours)}`;source.textContent=`天氣 ${data.source} · 預報 ${t} · 地圖 ${mapState.source||'—'}${mapState.state==='fallback'?'（備援）':''}${fieldText()}${imageryText()}`};
  const updateMapStatus=s=>{mapState=s||mapState;if(!mapStatus)return;if(s.state==='fallback')mapStatus.textContent='OpenStreetMap 備援';else if(s.state==='ready')mapStatus.textContent=`${s.source} 地圖`;else mapStatus.textContent=`${s.source||'地圖'} 載入中…`;paint()};
  const updateImagery=s=>{imageryState=s||imageryState;paint()};
  const loadField=(delay=120)=>{clearTimeout(overlayTimer);overlayMeta=null;paint();overlayTimer=setTimeout(async()=>{overlayAbort?.abort();overlayAbort=new AbortController();try{let field=null;if(supportsWindField(active)){mapApi?.clearWeatherOverlay?.();field=await fetchWindField({...view,layer:active,offsetHours,signal:overlayAbort.signal,size:7});if(signal?.aborted||field?.layer!==active)return;overlayMeta=field;mapApi?.setWindField?.(active,field.geojson)}else if(supportsVisualOverlay(active)){mapApi?.clearWindField?.();field=await fetchWeatherGrid({...view,layer:active,offsetHours,signal:overlayAbort.signal});if(signal?.aborted||field?.layer!==active)return;overlayMeta=field;mapApi?.setWeatherOverlay?.(active,field.geojson)}paint()}catch(e){if(!signal?.aborted&&e?.name!=='AbortError'){overlayMeta=null;mapApi?.clearWeatherOverlay?.();mapApi?.clearWindField?.();source.textContent=`圖層暫時不可用 · 地圖 ${mapState.source||'—'}${imageryText()}`}}},delay)};
  const refresh=({lat,lon,zoom=view.zoom},delay=80)=>{view={lat,lon,zoom};clearTimeout(timer);timer=setTimeout(async()=>{weatherAbort?.abort();weatherAbort=new AbortController();try{data=await fetchPointWeather(lat,lon,{signal:weatherAbort.signal,offsetHours});if(!signal?.aborted)paint()}catch(e){if(!signal?.aborted&&e?.name!=='AbortError'){readout.textContent='預報資料暫時不可用';source.textContent=`地圖 ${mapState.source||'—'}${imageryText()}`}}},delay);loadField(delay+40)};
  refresh(view,0);mapApi=await mountMap(mapNode,{center:[DEFAULT_CENTER.lon,DEFAULT_CENTER.lat],zoom:4.1,basemap:'weather',onMove:p=>refresh(p),onStatus:updateMapStatus});if(!mapApi&&!signal?.aborted){updateMapStatus({state:'fallback',source:'地圖不可用'});readout.textContent='地圖暫時不可用'}else{imageryApi=createImageryController(mapApi,{signal,onChange:updateImagery});loadField(0)}
  const syncMapSize=()=>{if(!signal?.aborted)mapApi?.resize?.()};requestAnimationFrame(()=>{syncMapSize();requestAnimationFrame(syncMapSize)});resizeTimer=setTimeout(syncMapSize,240);const onViewportResize=()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(syncMapSize,80)};window.addEventListener('resize',onViewportResize,{passive:true});window.visualViewport?.addEventListener('resize',onViewportResize,{passive:true});
  host.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>{active=b.dataset.layer;overlayMeta=null;host.querySelectorAll('[data-layer]').forEach(x=>x.classList.toggle('on',x===b));paint();loadField(0)});
  host.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>{offsetHours=Number(b.dataset.time)||0;overlayMeta=null;host.querySelectorAll('[data-time]').forEach(x=>x.classList.toggle('on',x===b));refresh(view,0)});
  host.querySelectorAll('[data-base]').forEach(b=>b.onclick=()=>{mapApi?.setBasemap(b.dataset.base);host.querySelectorAll('[data-base]').forEach(x=>x.classList.toggle('on',x===b));setTimeout(syncMapSize,120)});
  host.querySelectorAll('[data-imagery]').forEach(b=>b.onclick=async()=>{host.querySelectorAll('[data-imagery]').forEach(x=>x.classList.toggle('on',x===b));await imageryApi?.set?.(b.dataset.imagery);paint()});
  return()=>{clearTimeout(timer);clearTimeout(overlayTimer);clearTimeout(resizeTimer);weatherAbort?.abort();overlayAbort?.abort();imageryApi?.destroy?.();window.removeEventListener('resize',onViewportResize);window.visualViewport?.removeEventListener('resize',onViewportResize);mapApi?.destroy?.()};
}
