import{layers,layerById,fetchPointWeather,fetchWeatherGrid,fetchWindField,supportsVisualOverlay,supportsWindField,supportsImageryLayer,DEFAULT_CENTER,TIMELINE_HOURS,timelineLabel}from'../shared/global-weather-service.js';
import{mountMap,basemaps}from'../shared/map-engine.js';
import{createImageryController}from'../shared/imagery-controller.js';
import{attachMapVisualEnhancements}from'../shared/map-visual-enhancements.js';
import{createContinuousWeatherField}from'../shared/continuous-weather-field.js';
import{createTyphoonController}from'../shared/typhoon-controller.js';
import{enableMapInteractions}from'../shared/map-interactions.js';
export async function mount({host,signal}){
  let active='temp',offsetHours=0,data=null,timer=0,mapApi=null,imageryApi=null,visualApi=null,fieldApi=null,typhoonApi=null,interactionApi=null,weatherAbort=null,overlayAbort=null,overlayTimer=0,overlayMeta=null,pointState='loading',imageryState={state:'off',mode:'off'},typhoonState={state:'idle',visible:false,storms:[],warning:null,tips:[]},view={lat:DEFAULT_CENTER.lat,lon:DEFAULT_CENTER.lon,zoom:4.2},mapState={source:'OpenFreeMap'};
  host.innerHTML=`<section class="gw-app gw-tablet-app"><div class="gw-map" data-map aria-label="全球天氣地圖"></div><button type="button" class="gw-tablet-title" data-controls-toggle aria-expanded="false"><strong>全球天氣</strong><span>深圳附近</span><b>⌄</b></button><div data-controls hidden><nav class="gw-tablet-layers">${layers.map(l=>`<button type="button" data-layer="${l.id}" class="${l.id===active?'on':''}">${l.label}</button>`).join('')}</nav><nav class="gw-tablet-timeline">${TIMELINE_HOURS.map((h,i)=>`<button type="button" data-time="${h}" class="${i?'':'on'}">${timelineLabel(h)}</button>`).join('')}</nav><div class="gw-tablet-bottom"><nav class="gw-tablet-bases">${basemaps.map(b=>`<button type="button" data-base="${b.id}" class="${b.id==='weather'?'on':''}">${b.label}</button>`).join('')}<button type="button" data-typhoon>颱風</button></nav><small data-source></small></div></div><div class="gw-tablet-readout" data-readout>讀取預報資料…</div></section>`;
  const readout=host.querySelector('[data-readout]'),source=host.querySelector('[data-source]'),mapNode=host.querySelector('[data-map]'),controls=host.querySelector('[data-controls]'),toggle=host.querySelector('[data-controls-toggle]');
  const fieldText=()=>supportsImageryLayer(active)?'':overlayMeta?(supportsWindField(active)?` · ${active==='gust'?'陣風':'風'}場 ${overlayMeta.sampleCount} 點`:` · ${layerById(active).label}連續場 ${overlayMeta.sampleCount} 點`):' · 場資料載入中…';
  const imageryText=()=>imageryState.state==='off'?'':` · ${imageryState.source||'影像'}${imageryState.state==='ready'?'':' '+imageryState.state}`;
  const typhoonText=()=>!typhoonState.visible?'':` · HKO ${typhoonState.storms?.length||0} 個熱帶氣旋`;
  const nearestFieldValue=field=>{const fs=field?.geojson?.features||[];let best=null,bd=Infinity;for(const f of fs){const c=f.geometry?.coordinates||[],dx=(Number(c[0])-view.lon)*Math.cos(view.lat*Math.PI/180),dy=Number(c[1])-view.lat,d=dx*dx+dy*dy;if(Number.isFinite(d)&&d<bd){bd=d;best=f}}return best};
  const useFieldFallback=field=>{if(!field||supportsImageryLayer(active))return;const f=nearestFieldValue(field),v=Number(supportsWindField(active)?f?.properties?.speed:f?.properties?.value);if(!Number.isFinite(v))return;const summary={wind:'—',gust:'—',rain:'—',temp:'—',humidity:'—',pressure:'—'};summary[active]=active==='rain'||active==='temp'?Number(v.toFixed(1)):Math.round(v);data={lat:view.lat,lon:view.lon,updatedAt:f?.properties?.updatedAt||field.updatedAt||new Date().toISOString(),source:field.source||'Open-Meteo',forecastOffset:offsetHours,summary,fieldFallback:true};};
  const paint=()=>{const l=layerById(active);if(supportsImageryLayer(active)){readout.textContent=`${l.label} · ${imageryState.state==='ready'?'實況影像':imageryState.state==='loading'?'載入中…':'等待影像'}`}else if(data){const v=data.summary[active];readout.textContent=`${l.label} ${v??'—'}${v==='—'||v==null?'':' '+l.unit} · ${timelineLabel(offsetHours)}${data.fieldFallback?' · 場值':''}`}else if(pointState==='error'&&overlayMeta){readout.textContent=`${l.label}圖層已載入 · ${timelineLabel(offsetHours)}`}else if(pointState==='error'){readout.textContent='點預報暫時不可用 · 正在重試場資料'}const t=String(data?.updatedAt||overlayMeta?.updatedAt||'').replace('T',' ').slice(5,16)||'—',pointNote=pointState==='error'?' · 點預報暫時不可用':'';if(source)source.textContent=`${supportsImageryLayer(active)?'影像':'Open-Meteo · 預報 '+t} · 地圖 ${mapState.source||'—'}${fieldText()}${pointNote}${imageryText()}${typhoonText()}`};
  const fieldRequest=()=>{const b=mapApi?.map?.getBounds?.();return b?{...view,bounds:{west:b.getWest(),east:b.getEast(),south:b.getSouth(),north:b.getNorth()}}:{...view}};
  const loadField=(delay=150)=>{clearTimeout(overlayTimer);paint();overlayTimer=setTimeout(async()=>{overlayAbort?.abort();overlayAbort=new AbortController();try{if(supportsImageryLayer(active)){fieldApi?.clear?.();mapApi?.clearWindField?.();overlayMeta=null;await imageryApi?.set?.(active==='cloud'?'satellite':'radar');paint();return}await imageryApi?.set?.('off');let field=null,req=fieldRequest();if(supportsWindField(active)){fieldApi?.clear?.();field=await fetchWindField({...req,layer:active,offsetHours,signal:overlayAbort.signal});if(signal?.aborted||field?.layer!==active)return;overlayMeta=field;if(pointState!=='ready')useFieldFallback(field);mapApi?.setWindField?.(active,field.geojson)}else if(supportsVisualOverlay(active)){mapApi?.clearWindField?.();field=await fetchWeatherGrid({...req,layer:active,offsetHours,signal:overlayAbort.signal});if(signal?.aborted||field?.layer!==active)return;overlayMeta=field;if(pointState!=='ready')useFieldFallback(field);fieldApi?.setField?.(active,field.geojson)}paint()}catch(e){if(!signal?.aborted&&e?.name!=='AbortError'){if(source)source.textContent=`氣象場暫時不可用${pointState==='ready'?' · 點預報正常':''}${imageryText()}${typhoonText()}`;paint()}}},delay)};
  const refresh=({lat,lon,zoom=view.zoom},delay=150)=>{view={lat,lon,zoom};clearTimeout(timer);timer=setTimeout(async()=>{weatherAbort?.abort();weatherAbort=new AbortController();pointState='loading';try{const next=await fetchPointWeather(lat,lon,{signal:weatherAbort.signal,offsetHours});if(!signal?.aborted){data=next;pointState='ready';paint()}}catch(e){if(!signal?.aborted&&e?.name!=='AbortError'){pointState='error';paint()}}},delay);if(!supportsImageryLayer(active))loadField(delay)};
  mapApi=await mountMap(mapNode,{center:[DEFAULT_CENTER.lon,DEFAULT_CENTER.lat],zoom:4.2,basemap:'weather',onMove:refresh,onStatus:s=>{mapState=s||mapState;paint()}});interactionApi=enableMapInteractions(mapApi,mapNode);visualApi=attachMapVisualEnhancements(mapApi);fieldApi=createContinuousWeatherField(mapApi,mapNode);imageryApi=createImageryController(mapApi,{signal,onChange:s=>{imageryState=s||imageryState;paint()}});typhoonApi=createTyphoonController(mapApi,{signal,onChange:s=>{typhoonState=s||typhoonState;visualApi?.refresh?.();paint()}});refresh(view,0);
  toggle.onclick=()=>{const open=controls.hidden;controls.hidden=!open;toggle.setAttribute('aria-expanded',String(open));toggle.querySelector('b').textContent=open?'⌃':'⌄'};
  host.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>{active=b.dataset.layer;overlayMeta=null;if(data?.fieldFallback)data=null;host.querySelectorAll('[data-layer]').forEach(x=>x.classList.toggle('on',x===b));paint();loadField(0)});
  host.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>{offsetHours=Number(b.dataset.time)||0;overlayMeta=null;data=null;pointState='loading';host.querySelectorAll('[data-time]').forEach(x=>x.classList.toggle('on',x===b));refresh(view,0);if(supportsImageryLayer(active))loadField(0)});
  host.querySelectorAll('[data-base]').forEach(b=>b.onclick=()=>{mapApi?.setBasemap(b.dataset.base);host.querySelectorAll('[data-base]').forEach(x=>x.classList.toggle('on',x===b));setTimeout(()=>{visualApi?.refresh?.();interactionApi?.destroy?.();interactionApi=enableMapInteractions(mapApi,mapNode);if(supportsVisualOverlay(active))fieldApi?.setField?.(active,overlayMeta?.geojson);else if(supportsImageryLayer(active))imageryApi?.set?.(active==='cloud'?'satellite':'radar')},160)});
  host.querySelector('[data-typhoon]').onclick=e=>{const on=e.currentTarget.classList.toggle('on');typhoonApi?.setVisible?.(on);paint()};
  return()=>{clearTimeout(timer);clearTimeout(overlayTimer);weatherAbort?.abort();overlayAbort?.abort();fieldApi?.destroy?.();interactionApi?.destroy?.();typhoonApi?.destroy?.();visualApi?.destroy?.();imageryApi?.destroy?.();mapApi?.destroy?.()};
}
