import{layers,layerById,fetchPointWeather,fetchWeatherGrid,fetchWindField,supportsVisualOverlay,supportsWindField,DEFAULT_CENTER,TIMELINE_HOURS,timelineLabel}from'../shared/global-weather-service.js';
import{mountMap,basemaps}from'../shared/map-engine.js';
import{imageryModes,createImageryController}from'../shared/imagery-controller.js';
import{attachMapVisualEnhancements}from'../shared/map-visual-enhancements.js';
import{createTyphoonController}from'../shared/typhoon-controller.js';
import{enableMapInteractions}from'../shared/map-interactions.js';
export async function mount({host,signal}){
  let active='temp',offsetHours=0,data=null,timer=0,mapApi=null,imageryApi=null,visualApi=null,typhoonApi=null,interactionApi=null,weatherAbort=null,overlayAbort=null,overlayTimer=0,overlayMeta=null,imageryState={state:'off',mode:'off'},typhoonState={state:'idle',visible:false,storms:[],warning:null,tips:[]},view={lat:DEFAULT_CENTER.lat,lon:DEFAULT_CENTER.lon,zoom:4.2},mapState={source:'OpenFreeMap'};
  host.innerHTML=`<section class="gw-app gw-tablet-app"><div class="gw-map" data-map aria-label="全球天氣地圖"></div><div class="gw-tablet-title"><strong>全球天氣</strong><span>深圳附近</span></div><nav class="gw-tablet-layers">${layers.map(l=>`<button type="button" data-layer="${l.id}" class="${l.id===active?'on':''}">${l.label}</button>`).join('')}</nav><nav class="gw-tablet-timeline">${TIMELINE_HOURS.map((h,i)=>`<button type="button" data-time="${h}" class="${i?'':'on'}">${timelineLabel(h)}</button>`).join('')}</nav><div class="gw-tablet-bottom"><div class="gw-tablet-readout" data-readout>讀取預報資料…</div><nav class="gw-tablet-bases">${basemaps.map(b=>`<button type="button" data-base="${b.id}" class="${b.id==='weather'?'on':''}">${b.label}</button>`).join('')}${imageryModes.map(m=>`<button type="button" data-imagery="${m.id}" class="${m.id==='off'?'on':''}">${m.label}</button>`).join('')}<button type="button" data-typhoon>颱風</button></nav><small data-source></small></div></section>`;
  const readout=host.querySelector('[data-readout]'),source=host.querySelector('[data-source]'),mapNode=host.querySelector('[data-map]');
  const fieldText=()=>overlayMeta?(supportsWindField(active)?` · ${active==='gust'?'陣風':'風'}場 ${overlayMeta.sampleCount} 點`:` · ${layerById(active).label}圖層 ${overlayMeta.sampleCount} 點`):' · 場資料載入中…';
  const imageryText=()=>{if(imageryState.state==='off')return'';const t=imageryState.updatedAt?String(imageryState.updatedAt).replace('T',' ').replace('Z','').slice(0,16):'—';if(imageryState.state==='loading')return` · ${imageryState.source||'影像'} 載入中`;if(imageryState.state==='fallback')return` · ${imageryState.source} ${t}（備援）`;if(imageryState.state==='ready')return` · ${imageryState.source} ${t}`;return` · ${imageryState.source||'影像'}不可用`};
  const typhoonText=()=>{if(!typhoonState.visible||typhoonState.state==='idle')return'';if(typhoonState.state==='loading')return' · HKO 颱風載入中';if(typhoonState.state==='error')return' · HKO 颱風不可用';const n=typhoonState.storms?.length||0,w=typhoonState.warning?.type||typhoonState.warning?.code||'';return` · HKO ${n?`${n} 個熱帶氣旋`:'無現行路徑'}${w?` · ${w}`:''}`};
  const paint=()=>{if(!data)return;const l=layerById(active),v=data.summary[active],t=String(data.updatedAt||'').replace('T',' ').slice(5,16)||'—';readout.textContent=`${l.label} ${v}${v==='—'?'':' '+l.unit} · ${timelineLabel(offsetHours)}`;source.textContent=`Open-Meteo · 預報 ${t} · 地圖 ${mapState.source||'—'}${fieldText()}${imageryText()}${typhoonText()}`};
  const loadField=(delay=110)=>{clearTimeout(overlayTimer);overlayMeta=null;paint();overlayTimer=setTimeout(async()=>{overlayAbort?.abort();overlayAbort=new AbortController();try{let field=null;if(supportsWindField(active)){mapApi?.clearWeatherOverlay?.();field=await fetchWindField({...view,layer:active,offsetHours,signal:overlayAbort.signal,size:5});if(signal?.aborted||field?.layer!==active)return;overlayMeta=field;mapApi?.setWindField?.(active,field.geojson)}else if(supportsVisualOverlay(active)){mapApi?.clearWindField?.();field=await fetchWeatherGrid({...view,layer:active,offsetHours,signal:overlayAbort.signal,size:7});if(signal?.aborted||field?.layer!==active)return;overlayMeta=field;mapApi?.setWeatherOverlay?.(active,field.geojson);visualApi?.refresh?.()}paint()}catch(e){if(!signal?.aborted&&e?.name!=='AbortError'){overlayMeta=null;source.textContent=`預報圖層暫時不可用${imageryText()}${typhoonText()}`}}},delay)};
  const refresh=({lat,lon,zoom=view.zoom},delay=110)=>{view={lat,lon,zoom};clearTimeout(timer);timer=setTimeout(async()=>{weatherAbort?.abort();weatherAbort=new AbortController();try{data=await fetchPointWeather(lat,lon,{signal:weatherAbort.signal,offsetHours});if(!signal?.aborted)paint()}catch(e){if(!signal?.aborted&&e?.name!=='AbortError')readout.textContent='預報資料暫時不可用'}},delay);loadField(delay+80)};
  mapApi=await mountMap(mapNode,{center:[DEFAULT_CENTER.lon,DEFAULT_CENTER.lat],zoom:4.2,basemap:'weather',onMove:refresh,onStatus:s=>{mapState=s||mapState;paint()}});interactionApi=enableMapInteractions(mapApi,mapNode);visualApi=attachMapVisualEnhancements(mapApi);imageryApi=createImageryController(mapApi,{signal,onChange:s=>{imageryState=s||imageryState;paint()}});typhoonApi=createTyphoonController(mapApi,{signal,onChange:s=>{typhoonState=s||typhoonState;visualApi?.refresh?.();paint()}});refresh(view,0);loadField(0);
  host.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>{active=b.dataset.layer;overlayMeta=null;host.querySelectorAll('[data-layer]').forEach(x=>x.classList.toggle('on',x===b));paint();loadField(0)});
  host.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>{offsetHours=Number(b.dataset.time)||0;overlayMeta=null;host.querySelectorAll('[data-time]').forEach(x=>x.classList.toggle('on',x===b));refresh(view,0)});
  host.querySelectorAll('[data-base]').forEach(b=>b.onclick=()=>{mapApi?.setBasemap(b.dataset.base);host.querySelectorAll('[data-base]').forEach(x=>x.classList.toggle('on',x===b));setTimeout(()=>{visualApi?.refresh?.();interactionApi?.destroy?.();interactionApi=enableMapInteractions(mapApi,mapNode);typhoonApi?.setVisible?.(host.querySelector('[data-typhoon]')?.classList.contains('on'))},160)});
  host.querySelectorAll('[data-imagery]').forEach(b=>b.onclick=async()=>{host.querySelectorAll('[data-imagery]').forEach(x=>x.classList.toggle('on',x===b));await imageryApi?.set?.(b.dataset.imagery);visualApi?.refresh?.();paint()});
  host.querySelector('[data-typhoon]').onclick=e=>{const on=e.currentTarget.classList.toggle('on');typhoonApi?.setVisible?.(on);visualApi?.refresh?.();paint()};
  return()=>{clearTimeout(timer);clearTimeout(overlayTimer);weatherAbort?.abort();overlayAbort?.abort();interactionApi?.destroy?.();typhoonApi?.destroy?.();visualApi?.destroy?.();imageryApi?.destroy?.();mapApi?.destroy?.()};
}
