(()=>{'use strict';
const data={cities:[['taipei','台北',78,42,26,'台北大巨蛋 / 台北小巨蛋','核心主場','主場記憶、台北大巨蛋、台北小巨蛋與 5525+2 的核心敘事。'],['taichung','台中',72,50,14,'台中洲際棒球場','起跑 / 跨年','5525 起跑與跨年線，適合做成場館攻略與倒數頁。'],['kaohsiung','高雄',69,62,12,'高雄世運主場館','戶外大場','港都戶外大場、世運主場館與大型合唱氛圍。'],['hongkong','香港',56,64,10,'中環海濱 / 紅磡','海港海外線','維港海風、海外華語城市節點與海濱演唱會氣質。'],['shanghai','上海',74,28,9,'上海體育場','連場都市','華東高密度都市連場路線。'],['beijing','北京',60,14,8,'國家體育場 · 鳥巢','超大型場','鳥巢大型場記憶與北方巡演節點。'],['shenzhen','深圳',55,60,5,'深圳大運中心','霓虹城市','大灣區霓虹節點與年輕城市線。'],['singapore','新加坡',38,84,3,'國家體育場 / 室內館','東南亞節點','東南亞巡演節點，後續可補交通與入場指南。'],['tokyo','東京',92,18,2,'日本武道館等','日本資料線','日文資料、海外作品與武道館記憶。']].map(x=>({id:x[0],name:x[1],x:x[2],y:x[3],visits:x[4],venue:x[5],tag:x[6],summary:x[7]})),tours:[['all','全部巡演','All routes','#f4f8ff',['taichung','kaohsiung','hongkong','beijing','shanghai','taipei']],['t5525','5525 回到那一天','2023–2026','#28d7ff',['taichung','kaohsiung','hongkong','beijing','shanghai','taipei']],['wantsee','好好好想見到你','2020–2024','#f7c65b',['kaohsiung','taichung','taipei','hongkong','shenzhen','shanghai']],['life','LIFE 人生無限公司','2017–2019','#9b84ff',['taipei','hongkong','shanghai','beijing','kaohsiung']],['ark','諾亞方舟','2011–2014','#ff7ea9',['taipei','kaohsiung','hongkong','shanghai','beijing']],['dna','DNA 創造','2009–2010','#72f5c6',['taipei','hongkong','shanghai','singapore','tokyo']]].map(x=>({id:x[0],name:x[1],years:x[2],color:x[3],route:x[4]})),albums:['第一張創作專輯','愛情萬歲','人生海海','時光機','神的孩子都在跳舞','為愛而生','後青春期的詩','第二人生','自傳','作品9號'],songs:['Live 現場心跳精選','巡演安可歌單','城市夜行歌單','親子出遊清新版','五月天入坑 30 首','深夜電台慢歌'],books:['演唱會場刊','專輯內頁','票根收藏','樂譜與文字作品','展覽小誌','官方新聞剪報'],timeline:[['1997','成軍','建立故事起點與人物關係。'],['1999','首張創作專輯','專輯資料與作品索引入口。'],['2011','第二人生 / 諾亞方舟','大型巡演記憶層。'],['2017','LIFE 人生無限公司','科技感與大型場館階段。'],['2023','5525 起跑','目前主巡演資料主線。'],['2026','5525+2','台北大巨蛋與城市專題升級。']]};
const pages=[['home','A 巡演地圖'],['city','B 城市專題'],['album','C 專輯室'],['songs','D 歌曲宇宙'],['books','E 書籍出版'],['timeline','F 歷程檔案']];
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s)),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={page:'home',tour:'all',city:'taipei'};const city=id=>data.cities.find(c=>c.id===id)||data.cities[0],tour=id=>data.tours.find(t=>t.id===id)||data.tours[0];
function init(){const app=$('#app');app.innerHTML=`<div class="shell"><header class="top"><div class="wrap top-in"><a class="brand" href="#home"><span class="mark">M</span><span><b>MAYDAYLAND</b><small>v118 · lightweight product shell</small></span></a><nav class="nav">${pages.map(p=>`<button data-page="${p[0]}">${p[1]}</button>`).join('')}</nav><div class="perf"><i class="dot"></i><span>0 external libs · no iframe · no WebGL on main</span></div></div></header><div class="wrap"><section class="hero"><article class="hero-copy"><span class="kicker">Performance-first reset</span><h1>把卡頓先砍掉，再做精緻。</h1><p>這版主頁不載入 Three.js、不掛 iframe、不跑重動畫；用輕量 SVG 先把巡演分色、城市專題、專輯室和 A–F 分頁完整串起來。高階 3D Atlas 之後作為可選模式，不再阻塞首頁。</p><div class="hero-actions"><button class="primary" data-page="home">看巡演地圖</button><button class="ghost" data-page="city">看城市專題</button><button class="ghost" data-page="album">看專輯室</button></div></article><aside class="score"><div><small>入口請求</small><b>2 files</b></div><div><small>主頁 WebGL</small><b>0</b></div><div><small>A–F 分頁</small><b>已接起</b></div><div><small>目標</small><b>先流暢</b></div></aside></section><section class="page active" id="page-home">${home()}</section><section class="page" id="page-city">${cityPage()}</section><section class="page" id="page-album">${albumPage()}</section><section class="page" id="page-songs">${songsPage()}</section><section class="page" id="page-books">${booksPage()}</section><section class="page" id="page-timeline">${timelinePage()}</section></div><footer class="footer"><div class="wrap">Maydayland v118 · performance-first visible reset · static SVG route map · no legacy stack.</div></footer></div><div class="toast">v118 已切換為輕量首頁：先解決卡頓，再逐步補視覺細節。</div>`;bind();readHash();render();setTimeout(()=>$('.toast')?.classList.add('hide'),5200)}
function home(){return `<main class="main"><aside class="panel"><h2>Tour Filters</h2><div class="tour-list">${data.tours.map(tourButton).join('')}</div></aside><section class="panel map-card"><div class="map-head"><h2>巡演分色路線圖</h2><button class="chip" data-city="taipei">回到台北</button></div><div class="map-stage">${mapSvg()}${data.cities.map(c=>`<button class="city-btn" style="left:${c.x}%;top:${c.y}%" data-city="${c.id}">${c.name}</button>`).join('')}</div><div class="legend">${data.tours.filter(t=>t.id!=='all').map(t=>`<span style="--c:${t.color}"><i></i>${esc(t.name)}</span>`).join('')}</div></section><aside class="panel city-panel"><div id="cityBox"></div></aside></main>`}
function tourButton(t){return `<button class="tour" data-tour="${t.id}" style="--c:${t.color}"><i></i><span><b>${esc(t.name)}</b><small>${esc(t.years)}</small></span></button>`}
function mapSvg(){const regions='<path class="region" d="M695 82 L780 124 L760 220 L650 205 L612 130 Z"/><path class="region" d="M740 245 L815 268 L790 352 L704 338 Z"/><path class="region" d="M560 530 L635 560 L610 650 L505 626 Z"/><path class="region" d="M350 735 L444 730 L470 812 L356 832 Z"/><path class="region" d="M888 98 L970 135 L938 220 L855 188 Z"/>';const routes=data.tours.filter(t=>t.id!=='all').map(t=>{const d=t.route.map(id=>{const c=city(id);return `${c.x*10},${c.y*9}`}).join(' ');return `<polyline class="route" data-route="${t.id}" style="--c:${t.color}" points="${d}"/>`}).join('');const nodes=data.cities.map(c=>`<g><circle class="city-node ${c.visits>10?'hot':''}" cx="${c.x*10}" cy="${c.y*9}" r="7"/><text class="city-label" x="${c.x*10+10}" y="${c.y*9-8}">${esc(c.name)}</text></g>`).join('');return `<svg class="map-svg" viewBox="0 0 1000 900" role="img" aria-label="Mayday tour route map"><defs><linearGradient id="sea" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#0d2339"/><stop offset="1" stop-color="#06101d"/></linearGradient></defs><rect width="1000" height="900" fill="url(#sea)"/><circle cx="790" cy="378" r="280" fill="none" stroke="rgba(255,255,255,.04)"/><circle cx="620" cy="500" r="360" fill="none" stroke="rgba(255,255,255,.04)"/>${regions}${routes}${nodes}</svg>`}
function cityBox(){const c=city(state.city);const related=data.tours.filter(t=>t.id!=='all'&&t.route.includes(c.id));return `<div class="city-hero"><small>${esc(c.tag)}</small><h2>${esc(c.name)}</h2><p>${esc(c.summary)}</p></div><div class="kv"><div><small>熱度</small><b>${c.visits}</b></div><div><small>場館</small><b>${esc(c.venue)}</b></div><div><small>關聯巡演</small><b>${related.length}</b></div><div><small>模式</small><b>輕量</b></div></div><h2>關聯路線</h2><div class="legend">${related.map(t=>`<span style="--c:${t.color}"><i></i>${esc(t.name)}</span>`).join('')}</div>`}
function cityPage(){return `<div class="grid">${data.cities.map(c=>`<article class="card"><h3>${esc(c.name)} · ${esc(c.tag)}</h3><p>${esc(c.summary)}</p><div class="legend"><span><i style="background:#ffd36a"></i>${c.visits} heat</span><span>${esc(c.venue)}</span></div></article>`).join('')}</div>`}
function albumPage(){return `<div class="panel"><h2>五月天時光唱片室</h2><p class="muted">先用輕量唱片牆做正式頁面骨架，下一步再補封面圖與官方資料。</p><div class="album-wall">${data.albums.map((a,i)=>`<div class="album" style="background:linear-gradient(135deg,hsl(${i*32},70%,34%),#0d1727)">${esc(a)}</div>`).join('')}</div></div>`}
function songsPage(){return `<div class="playlist">${data.songs.map((s,i)=>`<article class="card"><h3>${esc(s)}</h3><p>${['適合首頁播放器','適合城市頁','適合夜間模式','適合親子出遊','適合新歌迷','適合深夜瀏覽'][i]}</p></article>`).join('')}</div>`}
function booksPage(){return `<div class="book-shelf">${data.books.map(b=>`<article class="card"><h3>${esc(b)}</h3><p>後續接入縮略圖、來源、購買/收藏狀態與年份索引。</p></article>`).join('')}</div>`}
function timelinePage(){return `<div class="panel timeline"><h2>歷程檔案</h2>${data.timeline.map(x=>`<div class="moment"><time>${x[0]}</time><article><h3>${esc(x[1])}</h3><p>${esc(x[2])}</p></article></div>`).join('')}</div>`}
function bind(){document.addEventListener('click',e=>{const p=e.target.closest('[data-page]');if(p){state.page=p.dataset.page;location.hash=state.page;return}const t=e.target.closest('[data-tour]');if(t){state.tour=t.dataset.tour;render();return}const c=e.target.closest('[data-city]');if(c){state.city=c.dataset.city;state.page='home';location.hash='home';render();return}});addEventListener('hashchange',()=>{readHash();render()})}
function readHash(){const h=(location.hash||'#home').replace('#','').split('/')[0];state.page=pages.some(p=>p[0]===h)?h:'home'}
function render(){$$('.page').forEach(p=>p.classList.toggle('active',p.id===`page-${state.page}`));$$('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===state.page));$$('.tour').forEach(b=>b.classList.toggle('active',b.dataset.tour===state.tour));$$('.route').forEach(r=>{const show=state.tour==='all'||r.dataset.route===state.tour;r.classList.toggle('dim',!show)});$$('.city-btn').forEach(b=>b.classList.toggle('active',b.dataset.city===state.city));const box=$('#cityBox');if(box)box.innerHTML=cityBox();document.documentElement.dataset.maydaylandRuntime='v118-ready'}
document.addEventListener('DOMContentLoaded',init,{once:true});
})();