(() => {
  'use strict';
  const D = window.MAYDAYLAND_ARCHIVE || {tours:[], albums:[], books:[], timeline:[]};
  const API = 'https://music-api.gdstudio.xyz/api.php';
  const LOGO = './mayday-logo.svg?v=12.0.0';
  const W = 1400, H = 700, LAT_MIN = -60, LAT_MAX = 85;
  const $ = id => document.getElementById(id);
  const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt = s => Number.isFinite(s) ? `${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}` : '0:00';

  const IMAGES = {
    band: 'https://www.mayday.jp/blue/img/photo-member.jpg',
    blue: 'https://www.mayday.jp/blue/img/header-cn.jpg',
    life: 'https://www.mayday.jp/wp-content/uploads/ffb31aec0c0adb49e80f9fc7e18b284f-500x399.jpg',
    history: 'https://www.mayday.jp/wp-content/uploads/5b5c7eed8c21d28d399c608497ab94561-500x500.jpg',
    first: 'https://www.mayday.jp/img/biography-oversea-1.jpg',
    viva: 'https://www.mayday.jp/img/biography-oversea-2.jpg',
    ocean: 'https://www.mayday.jp/img/biography-oversea-3.jpg',
    time: 'https://www.mayday.jp/img/biography-oversea-4.jpg',
    god: 'https://www.mayday.jp/img/biography-oversea-5.jpg',
    best: 'https://www.mayday.jp/img/biography-oversea-6.jpg',
    born: 'https://www.mayday.jp/img/biography-oversea-7.jpg',
    poetry: 'https://www.mayday.jp/img/biography-oversea-8.jpg',
    second: 'https://www.mayday.jp/img/biography-oversea-9a.jpg'
  };
  const songHints = ['倔强','知足','温柔','突然好想你','干杯','恋爱ING','OAOA','后来的我们','任意门','派对动物','笑忘歌','人生海海','憨人'];
  const dom = {
    tourList:$('tourList'), detail:$('detailPanel'), mapFrame:$('mapFrame'), canvas:$('mapCanvas'), routeLayer:$('routeLayer'), markerLayer:$('markerLayer'), pop:$('mapPopover'), routeRail:$('routeRail'), routeCaption:$('routeCaption'), routePlay:$('routePlay'), archiveView:$('archiveView'), archiveTitle:$('archiveTitle'), archiveBody:$('archiveBody'),
    audio:$('audio'), miniCover:$('miniCover'), miniTitle:$('miniTitle'), miniArtist:$('miniArtist'), miniWorld:$('miniWorld'), miniProgress:$('miniProgress'), openPlayer:$('openPlayer'), play:$('playButton'), prev:$('prevButton'), next:$('nextButton'), shuffle:$('shuffleButton'), repeat:$('repeatButton'), playerSheet:$('playerSheet'), playerClose:$('playerClose'), fullCover:$('fullCover'), fullTitle:$('fullTitle'), fullArtist:$('fullArtist'), fullWorld:$('fullWorld'), progress:$('progressInput'), currentTime:$('currentTime'), durationTime:$('durationTime'), lyrics:$('lyrics'), unlock:$('soundUnlock'), toast:$('toast'), globalSearch:$('globalSearch'), globalSearchInput:$('globalSearchInput'), mobileToggle:$('mobileTourToggle')
  };
  const state = {tour:D.tours[D.tours.length-1] || null, stopIndex:0, transform:{scale:1,x:0,y:0,rotation:0}, dragging:false, drag:null, routeTimer:0, routePlaying:false, tracks:[], index:-1, current:null, lyric:[], lyricIndex:-1, shuffle:true, repeat:false, busy:false, toastTimer:0};

  function project(lng, lat){return [((Number(lng)+180)/360)*W, ((LAT_MAX-Math.max(LAT_MIN,Math.min(LAT_MAX,Number(lat))))/(LAT_MAX-LAT_MIN))*H];}
  function safeImage(img, src, fallback=LOGO){if(!img)return; img.referrerPolicy='no-referrer'; img.onerror=()=>{img.onerror=null; img.src=fallback}; img.src=src||fallback;}
  function toast(msg){clearTimeout(state.toastTimer); dom.toast.textContent=msg; dom.toast.classList.add('show'); state.toastTimer=setTimeout(()=>dom.toast.classList.remove('show'),2200);}
  function tourImage(t){return ({'5525':IMAGES.history, blue:IMAGES.blue, jri:IMAGES.blue, life:IMAGES.life, jump:IMAGES.band, nowhere:IMAGES.second, dna:IMAGES.poetry, finalhome:IMAGES.god, back:IMAGES.poetry, sky:IMAGES.time, where:IMAGES.ocean, standout:IMAGES.viva, '168':IMAGES.first}[t?.id] || IMAGES.band);}
  function stopImage(stop,tour){return tourImage(tour);}

  function setView(view){
    document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active', b.dataset.view===view));
    $('mapView').classList.toggle('active', view==='map');
    dom.archiveView.classList.toggle('active', view!=='map');
    if(view==='map') { dom.archiveView.classList.remove('active'); requestAnimationFrame(()=>fitTour(state.tour,false)); }
    else openArchive(view);
  }

  function renderTourList(){
    const tours = D.tours || [];
    dom.tourList.innerHTML = tours.map(t=>`<button class="tour-item${t.id===state.tour?.id?' active':''}" data-tour="${t.id}" style="--tour:${t.color}"><i class="tour-dot"></i><span><b>${esc(t.name)}</b><small>${esc(t.english)}</small></span><em>${esc(t.years)}</em></button>`).join('');
  }

  function curve(a,b){const [x1,y1]=project(a.lng,a.lat), [x2,y2]=project(b.lng,b.lat); const dx=x2-x1, dy=y2-y1; const d=Math.hypot(dx,dy)||1; const mx=(x1+x2)/2, my=(y1+y2)/2; const bend=Math.max(16,Math.min(72,d*0.12)); return `M${x1.toFixed(1)} ${y1.toFixed(1)} Q${(mx-dy/d*bend).toFixed(1)} ${(my+dx/d*bend).toFixed(1)} ${x2.toFixed(1)} ${y2.toFixed(1)}`;}
  function arrowPath(a,b){const [x1,y1]=project(a.lng,a.lat), [x2,y2]=project(b.lng,b.lat); const mx=(x1+x2)/2,my=(y1+y2)/2, ang=Math.atan2(y2-y1,x2-x1), s=6; const p1=[mx+Math.cos(ang)*s,my+Math.sin(ang)*s],p2=[mx+Math.cos(ang+2.5)*s,my+Math.sin(ang+2.5)*s],p3=[mx+Math.cos(ang-2.5)*s,my+Math.sin(ang-2.5)*s]; return `M${p1[0]},${p1[1]} L${p2[0]},${p2[1]} L${p3[0]},${p3[1]} Z`;}
  function renderMap(){
    const t=state.tour; if(!t)return;
    const seg=[]; for(let i=1;i<t.stops.length;i++)seg.push([t.stops[i-1],t.stops[i]]);
    dom.routeLayer.innerHTML=seg.map(([a,b])=>`<path class="route-shadow" d="${curve(a,b)}"></path><path class="route-line" d="${curve(a,b)}" style="--tour:${t.color}"></path><path class="route-direction" d="${arrowPath(a,b)}" style="--tour:${t.color}"></path>`).join('');
    dom.markerLayer.innerHTML=t.stops.map((s,i)=>{const [x,y]=project(s.lng,s.lat); const labelX=x>W-120?-14:14, anchor=x>W-120?'end':'start'; return `<g class="map-stop${i===state.stopIndex?' active':''}" data-stop="${i}" transform="translate(${x.toFixed(1)} ${y.toFixed(1)})" style="--tour:${t.color}"><circle class="stop-halo" r="15"></circle><circle class="stop-disc" r="8"></circle><circle class="stop-core" r="3"></circle><text y=".8" text-anchor="middle">${i+1}</text><text class="city-label" x="${labelX}" y="4" text-anchor="${anchor}">${esc(s.city)}</text></g>`}).join('');
    dom.markerLayer.querySelectorAll('[data-stop]').forEach(g=>g.addEventListener('click',()=>selectStop(+g.dataset.stop,true)));
    renderRouteRail(); updatePopover();
  }
  function renderRouteRail(){const n=state.tour.stops.length; dom.routeRail.innerHTML=`<i style="width:${n<=1?0:(state.stopIndex/(n-1))*100}%"></i>`+state.tour.stops.map((s,i)=>`<span class="${i<=state.stopIndex?'done':''}" style="left:${n<=1?50:(i/(n-1))*100}%" data-rail="${i}"></span>`).join(''); dom.routeRail.querySelectorAll('[data-rail]').forEach(e=>e.addEventListener('click',()=>selectStop(+e.dataset.rail,true))); const s=state.tour.stops[state.stopIndex]; dom.routeCaption.textContent=`${state.stopIndex+1}/${n} ${s.city} ${s.date||state.tour.years}`;}
  function applyTransform(){dom.canvas.style.transform=`translate3d(${state.transform.x}px,${state.transform.y}px,0) scale(${state.transform.scale}) rotate(${state.transform.rotation}deg)`;}
  function fitTour(tour, animate=true){if(!tour?.stops?.length)return; const r=dom.mapFrame.getBoundingClientRect(); const pts=tour.stops.map(s=>{const [x,y]=project(s.lng,s.lat);return [x/W*r.width,y/H*r.height]}); const xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]); const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys); const w=Math.max(90,maxX-minX),h=Math.max(90,maxY-minY); const scale=Math.max(1,Math.min(2.6,Math.min((r.width-150)/w,(r.height-120)/h))); state.transform.x=r.width/2-((minX+maxX)/2)*scale; state.transform.y=r.height/2-((minY+maxY)/2)*scale; state.transform.scale=scale; applyTransform();}
  function bindMap(){dom.mapFrame.addEventListener('wheel',e=>{e.preventDefault(); const old=state.transform.scale; const next=Math.max(1,Math.min(4.2,old*(e.deltaY<0?1.12:.9))); const r=dom.mapFrame.getBoundingClientRect(); const px=e.clientX-r.left,py=e.clientY-r.top; const wx=(px-state.transform.x)/old,wy=(py-state.transform.y)/old; state.transform.scale=next; state.transform.x=px-wx*next; state.transform.y=py-wy*next; applyTransform();},{passive:false}); dom.mapFrame.addEventListener('pointerdown',e=>{if(e.target.closest('[data-stop]'))return; state.dragging=true; state.drag={x:e.clientX,y:e.clientY,tx:state.transform.x,ty:state.transform.y};}); window.addEventListener('pointermove',e=>{if(!state.dragging)return; state.transform.x=state.drag.tx+e.clientX-state.drag.x; state.transform.y=state.drag.ty+e.clientY-state.drag.y; applyTransform();}); window.addEventListener('pointerup',()=>state.dragging=false); $('zoomIn').onclick=()=>{state.transform.scale=Math.min(4.2,state.transform.scale*1.2);applyTransform()}; $('zoomOut').onclick=()=>{state.transform.scale=Math.max(1,state.transform.scale/1.2);applyTransform()}; $('fitMap').onclick=()=>fitTour(state.tour); $('flatMode').onclick=()=>{dom.canvas.classList.remove('globe'); $('flatMode').classList.add('active'); $('globeMode').classList.remove('active')}; $('globeMode').onclick=()=>{dom.canvas.classList.add('globe'); $('globeMode').classList.add('active'); $('flatMode').classList.remove('active')}; $('rotateLeft').onclick=()=>{state.transform.rotation-=7;applyTransform()}; $('rotateRight').onclick=()=>{state.transform.rotation+=7;applyTransform()};}

  function selectTour(id){const t=D.tours.find(x=>x.id===id); if(!t)return; state.tour=t; state.stopIndex=0; renderTourList(); renderMap(); openDetail(); fitTour(t); dom.miniWorld.textContent=dom.fullWorld.textContent=t.name;}
  function selectStop(i,focus=false){state.stopIndex=Math.max(0,Math.min(i,state.tour.stops.length-1)); renderMap(); openDetail(); if(focus){dom.detail.classList.add('open'); const s=state.tour.stops[state.stopIndex],r=dom.mapFrame.getBoundingClientRect(); const [x,y]=project(s.lng,s.lat); state.transform.scale=Math.max(1.5,state.transform.scale); state.transform.x=r.width/2-(x/W*r.width)*state.transform.scale; state.transform.y=r.height/2-(y/H*r.height)*state.transform.scale; applyTransform();}}
  function updatePopover(){const s=state.tour.stops[state.stopIndex]; const [x,y]=project(s.lng,s.lat); const r=dom.mapFrame.getBoundingClientRect(); dom.pop.hidden=false; dom.pop.style.left=`${Math.min(r.width-260,Math.max(18,x/W*r.width+24))}px`; dom.pop.style.top=`${Math.min(r.height-170,Math.max(78,y/H*r.height-80))}px`; dom.pop.innerHTML=`<img src="${stopImage(s,state.tour)}" alt="${esc(s.city)}" referrerpolicy="no-referrer"><div><b>${esc(s.city)}</b><small>${esc([s.date,s.venue].filter(Boolean).join(' · ')||state.tour.years)}</small></div>`;}
  function openDetail(){const t=state.tour,s=t.stops[state.stopIndex]; dom.detail.classList.add('open'); dom.detail.innerHTML=`<article class="detail-card" style="--tour:${t.color}"><div class="detail-hero"><img id="detailHero" alt="${esc(s.city)}"><div class="detail-title"><small>${state.stopIndex+1} · ${esc(t.years)} · TOUR STOP</small><h2>${esc(s.city)}</h2></div></div><div class="detail-body"><h3>${esc(s.venue||'官方城市节点')}</h3><p>${esc([s.date,s.phase].filter(Boolean).join(' · ')||'官方资料未列逐场日期；本站只保留可核实资料。')}</p><div class="venue-block"><b>所属巡演</b><p>${esc(t.name)}｜${esc(t.english)}</p></div><div class="stats"><div class="stat"><b>${t.stops.length}</b><small>路线节点</small></div><div class="stat"><b>${new Set(t.stops.map(x=>x.city)).size}</b><small>城市／场馆</small></div></div><div class="thumbs"><img src="${tourImage(t)}" alt="巡演照片"><img src="${IMAGES.band}" alt="五月天"><img src="${IMAGES.blue}" alt="巡演视觉"></div><p>${esc(t.summary)}</p><div class="source-links"><a href="${esc(t.source)}" target="_blank" rel="noopener">官方资料来源</a>${t.secondary?`<a href="${esc(t.secondary)}" target="_blank" rel="noopener">补充官方页</a>`:''}<button data-play-tour>播放巡演歌单</button></div><button class="primary-action" data-play-tour>查看该站歌单 ▶</button><div class="stops">${t.stops.map((x,i)=>`<button class="stop-row" data-stop-row="${i}"><span class="stop-no">${i+1}</span><span><b>${esc(x.city)}</b><small>${esc([x.date,x.venue,x.phase].filter(Boolean).join(' · ')||'官方城市档案未列逐场日期')}</small></span></button>`).join('')}</div></div></article>`; safeImage($('detailHero'), stopImage(s,t), LOGO); dom.detail.querySelectorAll('[data-stop-row]').forEach(b=>b.onclick=()=>selectStop(+b.dataset.stopRow,true)); dom.detail.querySelectorAll('[data-play-tour]').forEach(b=>b.onclick=()=>startRadio(`五月天 ${t.name} Live`));}

  function routePlay(){clearInterval(state.routeTimer); state.routePlaying=!state.routePlaying; dom.routePlay.textContent=state.routePlaying?'Ⅱ':'▶'; if(!state.routePlaying)return; state.routeTimer=setInterval(()=>{if(state.stopIndex>=state.tour.stops.length-1){clearInterval(state.routeTimer);state.routePlaying=false;dom.routePlay.textContent='▶';return} selectStop(state.stopIndex+1,true);},1100);}

  async function openArchive(view){
    dom.archiveTitle.textContent=({albums:'五月天时光唱片室',songs:'全曲库搜索与播放',books:'书籍与出版品',timeline:'五月天完整历程'}[view]||'档案馆');
    if(view==='albums') return renderAlbumRoom();
    if(view==='books') return renderBooks();
    if(view==='timeline') return renderTimeline();
    return renderSongSearch();
  }
  function albumArt(a){return a.image || LOGO;}
  function albumsByEra(){const groups={}; (D.albums||[]).forEach((a,i)=>{const y=parseInt(String(a.date).slice(0,4))||1999; const era=y<2000?'1990 - 1999':y<2010?'2000 - 2009':y<2020?'2010 - 2019':'2020 - 至今'; (groups[era] ||= []).push({...a,index:i,year:y});}); return groups;}
  function renderAlbumRoom(){const groups=albumsByEra(); const current=groups['2000 - 2009']?'2000 - 2009':Object.keys(groups)[0]; dom.archiveBody.innerHTML=`<section class="album-room"><div class="room-intro"><span class="eyebrow">TIME MACHINE ROOM</span><h2>五月天时光唱片室</h2><p>回到当初，像在老房间里从木质 CD 架上抽出一张唱片。</p><div class="era-filter">${['全部年代','2020 - 至今','2010 - 2019','2000 - 2009','1990 - 1999'].map(e=>`<button data-era="${e}" class="${e===current?'active':''}">${e}<span></span></button>`).join('')}</div></div><div class="record-player"></div><div class="shelf-area" id="shelfArea"></div><aside class="room-detail" id="roomDetail"></aside></section>`; renderShelf(current); document.querySelectorAll('[data-era]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-era]').forEach(x=>x.classList.toggle('active',x===b)); renderShelf(b.dataset.era)});}
  function renderShelf(era){const groups=albumsByEra(); const list=era==='全部年代'?Object.values(groups).flat():groups[era]||[]; const byYear={}; list.forEach(a=>(byYear[a.year] ||= []).push(a)); $('shelfArea').innerHTML=Object.keys(byYear).sort((a,b)=>b-a).map(y=>`<div class="shelf-row"><h3>${y}</h3><div class="cd-list">${byYear[y].map(a=>`<button class="cd-case" data-album="${a.index}"><img src="${albumArt(a)}" alt="${esc(a.title)}" referrerpolicy="no-referrer"><small>${esc(a.title)}</small></button>`).join('')}</div></div>`).join('') || '<p>这一年代还没有录入专辑。</p>'; document.querySelectorAll('[data-album]').forEach(b=>b.onclick=()=>selectAlbum(+b.dataset.album)); selectAlbum(list[0]?.index ?? 0);}
  async function selectAlbum(i){const a=D.albums[i]; if(!a)return; const tracks=await getAlbumTracks(a); const box=$('roomDetail'); if(!box)return; box.innerHTML=`<span class="eyebrow">${esc(a.date)}</span><h2>${esc(a.title)}</h2><p>${esc(a.english||'Mayday Album')}</p><img src="${albumArt(a)}" alt="${esc(a.title)}" referrerpolicy="no-referrer"><p>收录这一时期的声音与回忆，作为 Maydayland 的时光唱片档案。</p><div class="track-list">${(tracks.length?tracks:songHints.slice(0,6)).map((t,idx)=>`<button data-song-query="五月天 ${esc(t)}"><b>${String(idx+1).padStart(2,'0')} ${esc(t)}</b></button>`).join('')}</div><button class="primary-action" data-play-album="五月天 ${esc(a.title)}">播放专辑 ▶</button>`; box.querySelectorAll('[data-song-query]').forEach(b=>b.onclick=()=>startRadio(b.dataset.songQuery)); box.querySelector('[data-play-album]').onclick=()=>startRadio(box.querySelector('[data-play-album]').dataset.playAlbum);}
  async function getAlbumTracks(a){try{const r=await fetch(`https://itunes.apple.com/search?term=${encodeURIComponent('五月天 '+a.title)}&entity=album&country=TW&limit=10`); const j=await r.json(); const hit=(j.results||[]).find(x=>/五月天|Mayday/i.test(x.artistName||''))||(j.results||[])[0]; if(!hit?.collectionId)return []; const lr=await fetch(`https://itunes.apple.com/lookup?id=${hit.collectionId}&entity=song&country=TW`); const lj=await lr.json(); return (lj.results||[]).filter(x=>x.wrapperType==='track').map(x=>x.trackName).slice(0,14)}catch{return []}}
  function renderBooks(){const coverId=url=>String(url||'').match(/products\/(\d+)/)?.[1]; const cover=id=>id?`https://www.books.com.tw/img/${id.slice(0,3)}/${id.slice(3,6)}/${id.slice(6,8)}/${id}.jpg`:''; dom.archiveBody.className='archive-grid'; dom.archiveBody.innerHTML=(D.books||[]).map((b,i)=>{const id=coverId(b.url);return `<article class="archive-card book-card"><div class="book-cover"><img src="${cover(id)}" alt="${esc(b.title)}" onerror="this.remove();this.parentElement.textContent='${esc(b.title)}'"></div><div><small>${esc(b.year)} · ${esc(b.publisher)}</small><h3>${esc(b.title)}</h3><p>${esc(b.author)}</p><p>${esc(b.note)}</p><a href="${esc(b.url)}" target="_blank" rel="noopener">资料页</a></div></article>`}).join('');}
  function renderTimeline(){dom.archiveBody.className='timeline'; dom.archiveBody.innerHTML=(D.timeline||[]).map(([y,t,p])=>`<div class="time-row"><time>${esc(y)}</time><i></i><div><h3>${esc(t)}</h3><p>${esc(p)}</p></div></div>`).join('');}
  function renderSongSearch(){dom.archiveBody.className='song-search-view'; dom.archiveBody.innerHTML=`<form id="songSearch"><input id="songQuery" placeholder="搜索五月天歌曲、专辑或现场版本"><button>搜索</button></form><div id="songResults"></div>`; $('songSearch').onsubmit=async e=>{e.preventDefault(); const box=$('songResults'); box.innerHTML='<p>正在搜索…</p>'; const rows=await searchSongs('五月天 '+$('songQuery').value.trim(),50); box.innerHTML=rows.map((s,i)=>`<button class="stop-row" data-song="${i}"><span class="stop-no">▶</span><span><b>${esc(s.name)}</b><small>${esc(s.artist)} · ${esc(s.album)}</small></span></button>`).join('')||'<p>没有结果。</p>'; box.querySelectorAll('[data-song]').forEach(b=>b.onclick=()=>{state.tracks=rows; playAt(+b.dataset.song)});};}

  async function apiJson(url,timeout=6500){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{signal:c.signal,cache:'no-store'});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(t)}}
  function norm(x,source){return{id:String(x.id||''),name:String(x.name||x.title||''),artist:Array.isArray(x.artist)?x.artist.join(' / '):String(x.artist||'五月天'),album:String(x.album||''),pic:x.pic_id||'',source:x.source||source}}
  async function searchSource(source,q,count=24){const data=await apiJson(`${API}?types=search&source=${source}&name=${encodeURIComponent(q)}&count=${count}&pages=1`,5600); if(!Array.isArray(data))return[]; return data.map(x=>norm(x,source)).filter(x=>x.id&&/五月天|Mayday/i.test(`${x.artist} ${x.album} ${x.name}`));}
  async function searchSongs(q,count=40){const settled=await Promise.allSettled(['netease','qq','kuwo','migu'].map(s=>searchSource(s,q,count))); const map=new Map(); settled.flatMap(r=>r.status==='fulfilled'?r.value:[]).forEach(x=>map.set(`${x.source}:${x.id}`,x)); return [...map.values()];}
  function cover(song){return song?.pic?`${API}?types=pic&id=${encodeURIComponent(song.pic)}&source=${encodeURIComponent(song.source)}&size=700`:LOGO;}
  async function resolve(song){for(const br of [320,192,128]){try{const d=await apiJson(`${API}?types=url&id=${encodeURIComponent(song.id)}&source=${encodeURIComponent(song.source)}&br=${br}`,5500); if(d?.url)return String(d.url).replace(/^http:/,'https:')}catch{}}return'';}
  async function startRadio(q='五月天'){if(state.busy)return; state.busy=true; dom.miniTitle.textContent='正在连接歌源…'; let rows=await searchSongs(q,30); if(!rows.length) rows=await searchSongs('五月天 '+songHints[Math.floor(Math.random()*songHints.length)],12); state.tracks=rows.sort(()=>Math.random()-.5); state.busy=false; if(!state.tracks.length){dom.miniTitle.textContent='歌源暂时无回应';return toast('歌源暂时无法连接，请稍后再试');} playAt(0);}
  async function playAt(i,attempt=0){if(!state.tracks.length||attempt>5)return; state.index=(i+state.tracks.length)%state.tracks.length; state.current=state.tracks[state.index]; updateNow(); const url=await resolve(state.current); if(!url)return playAt(state.index+1,attempt+1); dom.audio.src=url; dom.audio.load(); loadLyrics(state.current); try{await dom.audio.play(); dom.unlock.hidden=true}catch(e){dom.unlock.hidden=false; dom.unlock.textContent=e?.name==='NotAllowedError'?'▶ 点一下开启声音':'▶ 点一下重试播放';}}
  function updateNow(){const s=state.current; safeImage(dom.miniCover,cover(s),LOGO); safeImage(dom.fullCover,cover(s),LOGO); dom.miniTitle.textContent=dom.fullTitle.textContent=s?.name||'等待播放'; dom.miniArtist.textContent=dom.fullArtist.textContent=s?.artist||'五月天'; dom.miniWorld.textContent=dom.fullWorld.textContent=state.tour?.name||'MAYDAYLAND RADIO';}
  async function loadLyrics(s){dom.lyrics.innerHTML='<p>正在载入歌词…</p>';state.lyric=[];try{const d=await apiJson(`${API}?types=lyric&id=${encodeURIComponent(s.id)}&source=${encodeURIComponent(s.source)}`,7000); const raw=typeof d==='string'?d:(d?.lyric||d?.lrc?.lyric||d?.lrc||''); const lines=[]; String(raw).split(/\r?\n/).forEach(line=>{const text=line.replace(/\[[^\]]+\]/g,'').trim(); for(const m of line.matchAll(/\[(\d+):(\d+(?:\.\d+)?)\]/g)) if(text) lines.push({time:+m[1]*60+ +m[2],text});}); state.lyric=lines.sort((a,b)=>a.time-b.time); dom.lyrics.innerHTML=state.lyric.length?state.lyric.map((l,i)=>`<div class="lyric-line" data-lyric="${i}">${esc(l.text)}</div>`).join(''):'<p>目前没有可用的时间轴歌词。</p>'}catch{dom.lyrics.innerHTML='<p>歌词服务暂时没有回应。</p>'}}
  function syncLyric(t){if(!state.lyric.length)return; let idx=0; for(let i=0;i<state.lyric.length;i++){if(state.lyric[i].time<=t)idx=i;else break} if(idx===state.lyricIndex)return; state.lyricIndex=idx; dom.lyrics.querySelectorAll('.lyric-line').forEach((l,i)=>l.classList.toggle('active',i===idx)); dom.lyrics.querySelector(`[data-lyric="${idx}"]`)?.scrollIntoView({block:'center',behavior:'smooth'});}

  function bind(){document.addEventListener('click',e=>{const v=e.target.closest('[data-view]'); if(v){e.preventDefault(); setView(v.dataset.view)}}); dom.tourList.onclick=e=>{const b=e.target.closest('[data-tour]'); if(b)selectTour(b.dataset.tour)}; dom.routePlay.onclick=routePlay; $('randomButton').onclick=()=>selectTour(D.tours[Math.floor(Math.random()*D.tours.length)].id); $('timelineButton').onclick=()=>setView('timeline'); dom.mobileToggle.onclick=()=>document.querySelector('.tour-sidebar').classList.toggle('open'); bindMap(); dom.globalSearch.onsubmit=e=>{e.preventDefault(); setView('songs'); setTimeout(()=>{$('songQuery').value=dom.globalSearchInput.value; $('songSearch').dispatchEvent(new Event('submit'))},80)}; dom.play.onclick=()=>dom.audio.paused?(state.current?dom.audio.play().catch(()=>dom.unlock.hidden=false):startRadio()):dom.audio.pause(); dom.prev.onclick=()=>playAt(state.index-1); dom.next.onclick=()=>playAt(state.shuffle?Math.floor(Math.random()*state.tracks.length):state.index+1); dom.shuffle.onclick=()=>{state.shuffle=!state.shuffle;dom.shuffle.classList.toggle('active',state.shuffle)}; dom.repeat.onclick=()=>{state.repeat=!state.repeat;dom.repeat.classList.toggle('active',state.repeat)}; dom.unlock.onclick=()=>dom.audio.play().then(()=>dom.unlock.hidden=true).catch(()=>startRadio()); dom.openPlayer.onclick=()=>dom.playerSheet.classList.add('open'); dom.playerClose.onclick=()=>dom.playerSheet.classList.remove('open'); $('lyricsButton').onclick=()=>dom.playerSheet.classList.add('open'); dom.audio.onplay=()=>dom.play.textContent='Ⅱ'; dom.audio.onpause=()=>dom.play.textContent='▶'; dom.audio.onended=()=>state.repeat?playAt(state.index):playAt(state.shuffle?Math.floor(Math.random()*state.tracks.length):state.index+1); dom.audio.ontimeupdate=()=>{const d=dom.audio.duration||0,c=dom.audio.currentTime||0;dom.miniProgress.style.width=`${d?c/d*100:0}%`;dom.progress.value=Math.round((d?c/d:0)*1000);dom.currentTime.textContent=fmt(c);dom.durationTime.textContent=fmt(d);syncLyric(c)}; dom.progress.oninput=()=>{if(dom.audio.duration)dom.audio.currentTime=dom.progress.value/1000*dom.audio.duration}; window.addEventListener('resize',()=>fitTour(state.tour,false));}

  function init(){renderTourList(); bind(); selectTour(state.tour?.id || D.tours[0]?.id); setTimeout(()=>startRadio(),450);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true}); else init();
})();
