(()=>{'use strict';
const albums=[
{title:'第一張創作專輯',year:'1999',date:'1999-07-07',tone:['#cf5f42','#24120f'],note:'把青春、城市與樂團現場感第一次完整放進唱片。'},
{title:'愛情萬歲',year:'2000',date:'2000-07-07',tone:['#4f7eaa','#142333'],note:'更直接、更熱烈的吉他聲響，奠定早期五月天的現場性格。'},
{title:'人生海海',year:'2001',date:'2001-07-06',tone:['#d19a45','#3c2814'],note:'在告別與遠行之前，把成長、友情與世界感寫成一張完整作品。'},
{title:'時光機',year:'2003',date:'2003-11-11',tone:['#8065aa','#241b3c'],note:'復出後的時間旅行，開始把概念敘事與大型舞台感帶進專輯。'},
{title:'神的孩子都在跳舞',year:'2004',date:'2004-11-05',tone:['#4f8a70','#142a23'],note:'更硬朗的樂團編制與節奏，唱片本身像一場高速運轉的 Live。'},
{title:'為愛而生',year:'2006',date:'2006-12-29',tone:['#a65a76','#351925'],note:'把愛、信念與大場館式抒情推到更寬廣的尺度。'},
{title:'後青春期的詩',year:'2008',date:'2008-10-23',tone:['#4e7d99','#152a37'],note:'青春之後仍然追問青春，是很多歌迷的人生分水嶺。'},
{title:'第二人生',year:'2011',date:'2011-12-16',tone:['#b68043','#342313'],note:'末日命題與第二人生選擇題，和諾亞方舟巡演形成完整世界觀。'},
{title:'自傳',year:'2016',date:'2016-07-21',tone:['#677f9e','#192531'],note:'回望樂團與個人人生，把二十年的軌跡濃縮成一部音樂自傳。'}
];
const cities=[['taipei','台北',78,42,26,'台北大巨蛋 / 台北小巨蛋','核心主場','主場記憶、台北大巨蛋、台北小巨蛋與 5525+2 的核心敘事。'],['taichung','台中',72,50,14,'台中洲際棒球場','起跑 / 跨年','5525 起跑與跨年線，適合做成場館攻略與倒數頁。'],['kaohsiung','高雄',69,62,12,'高雄世運主場館','戶外大場','港都戶外大場、世運主場館與大型合唱氛圍。'],['hongkong','香港',56,64,10,'中環海濱 / 紅磡','海港海外線','維港海風、海外華語城市節點與海濱演唱會氣質。'],['shanghai','上海',74,28,9,'上海體育場','連場都市','華東高密度都市連場路線。'],['beijing','北京',60,14,8,'國家體育場 · 鳥巢','超大型場','鳥巢大型場記憶與北方巡演節點。'],['shenzhen','深圳',55,60,5,'深圳大運中心','霓虹城市','大灣區霓虹節點與年輕城市線。'],['singapore','新加坡',38,84,3,'國家體育場 / 室內館','東南亞節點','東南亞巡演節點，後續可補交通與入場指南。'],['tokyo','東京',92,18,2,'日本武道館等','日本資料線','日文資料、海外作品與武道館記憶。']].map(x=>({id:x[0],name:x[1],x:x[2],y:x[3],visits:x[4],venue:x[5],tag:x[6],summary:x[7]}));
const tours=[['all','全部巡演','All routes','#f4f8ff',['taichung','kaohsiung','hongkong','beijing','shanghai','taipei']],['t5525','5525 回到那一天','2023–2026','#28d7ff',['taichung','kaohsiung','hongkong','beijing','shanghai','taipei']],['wantsee','好好好想見到你','2020–2024','#f7c65b',['kaohsiung','taichung','taipei','hongkong','shenzhen','shanghai']],['life','LIFE 人生無限公司','2017–2019','#9b84ff',['taipei','hongkong','shanghai','beijing','kaohsiung']],['ark','諾亞方舟','2011–2014','#ff7ea9',['taipei','kaohsiung','hongkong','shanghai','beijing']],['dna','DNA 創造','2009–2010','#72f5c6',['taipei','hongkong','shanghai','singapore','tokyo']]].map(x=>({id:x[0],name:x[1],years:x[2],color:x[3],route:x[4]}));
const pages=[['home','A 巡演地圖'],['city','B 城市專題'],['album','C 專輯室'],['songs','D 歌曲宇宙'],['books','E 書籍出版'],['timeline','F 歷程檔案']];
const songs=['Live 現場心跳精選','巡演安可歌單','城市夜行歌單','親子出遊清新版','五月天入坑 30 首','深夜電台慢歌'];
const books=['演唱會場刊','專輯內頁','票根收藏','樂譜與文字作品','展覽小誌','官方新聞剪報'];
const timeline=[['1997','成軍','建立故事起點與人物關係。'],['1999','首張創作專輯','專輯資料與作品索引入口。'],['2011','第二人生 / 諾亞方舟','大型巡演記憶層。'],['2017','LIFE 人生無限公司','科技感與大型場館階段。'],['2023','5525 起跑','目前主巡演資料主線。'],['2026','5525+2','台北大巨蛋與城市專題升級。']];
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s)),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={page:'home',tour:'all',city:'taipei'},artCache=new Map(),trackCache=new Map();
const city=id=>cities.find(c=>c.id===id)||cities[0];
function init(){const app=$('#app');app.innerHTML=`<div class="shell"><header class="top"><div class="wrap top-in"><a class="brand" href="#home"><span class="mark">M</span><span><b>MAYDAYLAND</b><small>v119 · Album Room</small></span></a><nav class="nav">${pages.map(p=>`<button data-page="${p[0]}">${p[1]}</button>`).join('')}</nav><div class="perf"><i class="dot"></i><span>2 shell files · album media on demand</span></div></div></header><div class="wrap"><section class="hero"><article class="hero-copy"><span class="kicker">Productized Record Room</span><h1>城市在路上，唱片在房間裡。</h1><p>保留 v118 的輕量首頁，C 頁升級為真正可打開的時光唱片室。封面與曲目只在進入專輯頁後按需載入，不重新引入首頁 WebGL、iframe 或 legacy stack。</p><div class="hero-actions"><button class="primary" data-page="album">進入唱片室</button><button class="ghost" data-page="home">看巡演地圖</button><button class="ghost" data-page="city">看城市專題</button></div></article><aside class="score"><div><small>主入口</small><b>2 files</b></div><div><small>首頁外部請求</small><b>0</b></div><div><small>專輯室</small><b>9 albums</b></div><div><small>載入策略</small><b>On demand</b></div></aside></section><section class="page active" id="page-home">${home()}</section><section class="page" id="page-city">${cityPage()}</section><section class="page" id="page-album">${albumPage()}</section><section class="page" id="page-songs">${songsPage()}</section><section class="page" id="page-books">${booksPage()}</section><section class="page" id="page-timeline">${timelinePage()}</section></div><footer class="footer"><div class="wrap">Maydayland v119 · lightweight shell · productized Album Room · media loaded only when needed.</div></footer></div>${albumDrawer()}`;bind();readHash();render()}
function home(){return `<main class="main"><aside class="panel"><h2>Tour Filters</h2><div class="tour-list">${tours.map(t=>`<button class="tour" data-tour="${t.id}" style="--c:${t.color}"><i></i><span><b>${esc(t.name)}</b><small>${esc(t.years)}</small></span></button>`).join('')}</div></aside><section class="panel map-card"><div class="map-head"><h2>巡演分色路線圖</h2><button class="chip" data-city="taipei">回到台北</button></div><div class="map-stage">${mapSvg()}${cities.map(c=>`<button class="city-btn" style="left:${c.x}%;top:${c.y}%" data-city="${c.id}">${c.name}</button>`).join('')}</div><div class="legend">${tours.filter(t=>t.id!=='all').map(t=>`<span style="--c:${t.color}"><i></i>${esc(t.name)}</span>`).join('')}</div></section><aside class="panel city-panel"><div id="cityBox"></div></aside></main>`}
function mapSvg(){const regions='<path class="region" d="M695 82 L780 124 L760 220 L650 205 L612 130 Z"/><path class="region" d="M740 245 L815 268 L790 352 L704 338 Z"/><path class="region" d="M560 530 L635 560 L610 650 L505 626 Z"/><path class="region" d="M350 735 L444 730 L470 812 L356 832 Z"/><path class="region" d="M888 98 L970 135 L938 220 L855 188 Z"/>';const routes=tours.filter(t=>t.id!=='all').map(t=>`<polyline class="route" data-route="${t.id}" style="--c:${t.color}" points="${t.route.map(id=>{const c=city(id);return `${c.x*10},${c.y*9}`}).join(' ')}"/>`).join('');const nodes=cities.map(c=>`<g><circle class="city-node ${c.visits>10?'hot':''}" cx="${c.x*10}" cy="${c.y*9}" r="7"/><text class="city-label" x="${c.x*10+10}" y="${c.y*9-8}">${esc(c.name)}</text></g>`).join('');return `<svg class="map-svg" viewBox="0 0 1000 900" role="img" aria-label="Mayday tour route map"><defs><linearGradient id="sea" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#0d2339"/><stop offset="1" stop-color="#06101d"/></linearGradient></defs><rect width="1000" height="900" fill="url(#sea)"/>${regions}${routes}${nodes}</svg>`}
function cityBox(){const c=city(state.city),related=tours.filter(t=>t.id!=='all'&&t.route.includes(c.id));return `<div class="city-hero"><small>${esc(c.tag)}</small><h2>${esc(c.name)}</h2><p>${esc(c.summary)}</p></div><div class="kv"><div><small>熱度</small><b>${c.visits}</b></div><div><small>場館</small><b>${esc(c.venue)}</b></div><div><small>關聯巡演</small><b>${related.length}</b></div><div><small>模式</small><b>輕量</b></div></div><h2>關聯路線</h2><div class="legend">${related.map(t=>`<span style="--c:${t.color}"><i></i>${esc(t.name)}</span>`).join('')}</div>`}
function cityPage(){return `<div class="grid">${cities.map(c=>`<article class="card"><h3>${esc(c.name)} · ${esc(c.tag)}</h3><p>${esc(c.summary)}</p><div class="legend"><span><i style="background:#ffd36a"></i>${c.visits} heat</span><span>${esc(c.venue)}</span></div></article>`).join('')}</div>`}
function albumPage(){return `<section class="record-room panel"><header class="record-head"><div><span class="kicker">MAYDAY TIME MACHINE · RECORD ROOM</span><h2>五月天時光唱片室</h2><p class="muted">按年代陳列九張錄音室專輯。點擊 CD 盒可打開封面、年代敘事與完整曲目；所有外部媒體都延遲到此頁才載入。</p></div><span class="room-badge">1999—2016</span></header><div class="shelf-groups">${[['青春啟程','1999—2001',0,3],['世界展開','2003—2006',3,6],['第二人生以後','2008—2016',6,9]].map(g=>`<section class="shelf-row"><div class="shelf-label"><b>${g[0]}</b><small>${g[1]}</small></div><div class="cd-shelf">${albums.slice(g[2],g[3]).map((a,j)=>albumCard(a,g[2]+j)).join('')}</div></section>`).join('')}</div></section>`}
function albumCard(a,i){return `<button class="cd-case" data-album="${i}" style="--album-a:${a.tone[0]};--album-b:${a.tone[1]}"><span class="cd-jewel"><img loading="lazy" alt="${esc(a.title)} 專輯封面"><span class="cd-fallback"><b>${esc(a.title)}</b><small>${a.year}</small></span></span><span class="cd-spine"><b>${esc(a.title)}</b><time>${a.year}</time></span></button>`}
function albumDrawer(){return `<section class="album-drawer" id="albumDrawer" aria-hidden="true"><button class="drawer-scrim" data-close-album aria-label="關閉專輯詳情"></button><article class="drawer-card"><button class="drawer-close" data-close-album aria-label="關閉">×</button><div class="disc-stage"><i class="vinyl"></i><img id="drawerCover" alt="專輯封面"></div><div class="drawer-copy"><span class="kicker" id="drawerDate">MAYDAY ALBUM</span><h2 id="drawerTitle">Album</h2><p id="drawerNote"></p><div class="album-meta" id="drawerMeta"></div><div class="track-head"><b>完整曲目</b><small id="trackCount">載入中</small></div><ol class="track-list" id="trackList"><li>正在打開唱片資料…</li></ol></div></article></section>`}
function songsPage(){return `<div class="playlist">${songs.map((s,i)=>`<article class="card"><h3>${esc(s)}</h3><p>${['適合首頁播放器','適合城市頁','適合夜間模式','適合親子出遊','適合新歌迷','適合深夜瀏覽'][i]}</p></article>`).join('')}</div>`}
function booksPage(){return `<div class="book-shelf">${books.map(b=>`<article class="card"><h3>${esc(b)}</h3><p>後續接入縮略圖、來源、收藏狀態與年份索引。</p></article>`).join('')}</div>`}
function timelinePage(){return `<div class="panel timeline"><h2>歷程檔案</h2>${timeline.map(x=>`<div class="moment"><time>${x[0]}</time><article><h3>${esc(x[1])}</h3><p>${esc(x[2])}</p></article></div>`).join('')}</div>`}
async function albumInfo(i){if(artCache.has(i))return artCache.get(i);const a=albums[i];try{const r=await fetch(`https://itunes.apple.com/search?term=${encodeURIComponent(`五月天 ${a.title}`)}&entity=album&country=TW&limit=20`),{mode:'cors'}),d=await r.json(),rows=Array.isArray(d.results)?d.results:[],hit=rows.find(x=>/五月天|Mayday/i.test(x.artistName||'')&&(x.collectionName||'').replace(/\s/g,'').includes(a.title.replace(/\s/g,'')))||rows.find(x=>/五月天|Mayday/i.test(x.artistName||'')),v={id:hit?.collectionId||'',art:hit?.artworkUrl100?.replace('100x100bb','1200x1200bb')||'',genre:hit?.primaryGenreName||'Mandopop',count:hit?.trackCount||''};artCache.set(i,v);return v}catch{return {id:'',art:'',genre:'Mandopop',count:''}}}
async function loadCovers(){const cards=$$('[data-album]');await Promise.all(cards.map(async b=>{const i=+b.dataset.album,img=$('img',b);if(!img||img.dataset.loaded)return;img.dataset.loaded='1';const info=await albumInfo(i);if(info.art){img.onload=()=>b.classList.add('has-cover');img.onerror=()=>b.classList.add('cover-failed');img.src=info.art}}))}
async function tracks(i){if(trackCache.has(i))return trackCache.get(i);const info=await albumInfo(i);if(!info.id)return[];try{const r=await fetch(`https://itunes.apple.com/lookup?id=${info.id}&entity=song&country=TW`,{mode:'cors'}),d=await r.json(),rows=(d.results||[]).filter(x=>x.wrapperType==='track').map(x=>({n:x.trackNumber||0,name:x.trackName}));trackCache.set(i,rows);return rows}catch{return[]}}
async function openAlbum(i){const a=albums[i],drawer=$('#albumDrawer');if(!a||!drawer)return;drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');document.body.classList.add('drawer-open');$('#drawerDate').textContent=a.date;$('#drawerTitle').textContent=a.title;$('#drawerNote').textContent=a.note;$('#drawerMeta').innerHTML='<span>五月天</span><span>錄音室專輯</span><span>資料載入中</span>';$('#trackCount').textContent='載入中';$('#trackList').innerHTML='<li>正在打開唱片資料…</li>';const info=await albumInfo(i),cover=$('#drawerCover');cover.src=info.art||'./mayday-logo.svg';$('#drawerMeta').innerHTML=`<span>五月天</span><span>${esc(info.genre)}</span>${info.count?`<span>${info.count} 首</span>`:''}`;const rows=await tracks(i);$('#trackCount').textContent=rows.length?`${rows.length} 首`:'曲目暫不可用';$('#trackList').innerHTML=rows.length?rows.map((t,n)=>`<li><i>${String(n+1).padStart(2,'0')}</i><span>${esc(t.name)}</span></li>`).join(''):'<li>目前無法取得完整曲目，專輯基本資料仍可瀏覽。</li>'}
function closeAlbum(){const d=$('#albumDrawer');d?.classList.remove('open');d?.setAttribute('aria-hidden','true');document.body.classList.remove('drawer-open')}
function bind(){document.addEventListener('click',e=>{const p=e.target.closest('[data-page]');if(p){state.page=p.dataset.page;location.hash=state.page;return}const t=e.target.closest('[data-tour]');if(t){state.tour=t.dataset.tour;render();return}const c=e.target.closest('[data-city]');if(c){state.city=c.dataset.city;state.page='home';location.hash='home';render();return}const a=e.target.closest('[data-album]');if(a){openAlbum(+a.dataset.album);return}if(e.target.closest('[data-close-album]'))closeAlbum()});addEventListener('hashchange',()=>{readHash();render()});addEventListener('keydown',e=>{if(e.key==='Escape')closeAlbum()})}
function readHash(){const h=(location.hash||'#home').replace('#','').split('/')[0];state.page=pages.some(p=>p[0]===h)?h:'home'}
function render(){$$('.page').forEach(p=>p.classList.toggle('active',p.id===`page-${state.page}`));$$('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===state.page));$$('.tour').forEach(b=>b.classList.toggle('active',b.dataset.tour===state.tour));$$('.route').forEach(r=>r.classList.toggle('dim',!(state.tour==='all'||r.dataset.route===state.tour)));$$('.city-btn').forEach(b=>b.classList.toggle('active',b.dataset.city===state.city));const box=$('#cityBox');if(box)box.innerHTML=cityBox();if(state.page==='album')requestAnimationFrame(loadCovers);document.documentElement.dataset.maydaylandRuntime='v119-ready'}
document.addEventListener('DOMContentLoaded',init,{once:true});
})();