(() => {
  'use strict';
  const $ = (selector, root=document) => root.querySelector(selector);
  const $$ = (selector, root=document) => Array.from(root.querySelectorAll(selector));
  const esc = value => String(value ?? '').replace(/[&<>"]/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[ch] || ch));
  const cities = [
    { city:'台北', lat:25.037, lng:121.565, visits:26, venue:'台北大巨蛋 / 台北小巨蛋', years:'1999–2026', level:'核心主場', score:74, tone:'#ff70b7', source:'https://www.bin-music.com.tw/news/2409', mood:'台灣主場、25 週年收官與大型場館記憶核心。', set:['回到那一天','倔強','突然好想你','知足','乾杯'], tasks:['核對逐日場次','補官方主視覺','補交通與拍照點','補逐日歌單'] },
    { city:'台中', lat:24.179, lng:120.646, visits:14, venue:'洲際棒球場', years:'2023–2026', level:'起跑 / 跨年', score:69, tone:'#ffd36a', source:'https://www.bin-music.com.tw/news/1985', mood:'5525 起跑與跨年敘事，適合做年度專題。', set:['派對動物','OAOA','倔強','乾杯'], tasks:['補起跑場圖牆','整理跨年節點','補場館交通','補年度時間線'] },
    { city:'高雄', lat:22.755, lng:120.310, visits:12, venue:'高雄世運主場館', years:'2024', level:'戶外大場', score:65, tone:'#ff9a56', source:'#', mood:'世運主場館、港都夜景與大型戶外舞台。', set:['離開地球表面','戀愛ing','溫柔','乾杯'], tasks:['補五場歌單','補世運照片','補交通資料','補港都旅遊延伸'] },
    { city:'香港', lat:22.282, lng:114.158, visits:10, venue:'中環海濱活動空間', years:'2024', level:'海港海外線', score:63, tone:'#8f7dff', source:'#', mood:'維港、海風與城市天際線，是海外華語場景的高記憶點。', set:['知足','突然好想你','倔強','溫柔'], tasks:['補官方票務','補維港照片','補交通路線','整理海外線'] },
    { city:'上海', lat:31.230, lng:121.474, visits:9, venue:'上海體育場', years:'2024', level:'連場都市', score:62, tone:'#64e8ff', source:'#', mood:'都市密度、連場演出與夜景霓虹。', set:['派對動物','夜訪吸血鬼','傷心的人別聽慢歌','乾杯'], tasks:['整理多場日曆','補城市夜景','補交通座位','補特殊曲'] },
    { city:'北京', lat:39.904, lng:116.407, visits:8, venue:'國家體育場 鳥巢', years:'2024–2026', level:'超大型場', score:61, tone:'#c96dff', source:'#', mood:'鳥巢級大型場館，適合做北方收官與大型場專題。', set:['諾亞方舟','成名在望','頑固','倔強'], tasks:['核對 2026 場次','補鳥巢官方圖','補收官專題','補票務交通'] },
    { city:'深圳', lat:22.543, lng:114.057, visits:5, venue:'深圳大運中心體育場', years:'2024', level:'霓虹城市', score:58, tone:'#35d0ff', source:'#', mood:'年輕市場、現代城市與夜景霓虹。', set:['OAOA','戀愛ing','派對動物','突然好想你'], tasks:['補場館照片','補站點歌單','整理交通','補票務來源'] }
  ];
  const albums = [
    ['第一張創作專輯','1999','https://www.bin-music.com.tw/album/artist_album/6256aaa3c124b-lw500h500.jpeg'],
    ['愛情萬歲','2000','https://www.bin-music.com.tw/album/artist_album/5ecf788f0856f-lw420h420.jpg'],
    ['人生海海','2001','https://www.bin-music.com.tw/album/artist_album/5ed7efaf18827-lw500h500.jpg'],
    ['時光機','2003','https://www.bin-music.com.tw/album/artist_album/5ed8e4a2afda5-lw500h500.jpg'],
    ['神的孩子都在跳舞','2004','https://www.bin-music.com.tw/album/artist_album/5ed8f08519147%2Btcw500h500.jpg'],
    ['知足 最真傑作選','2005','https://www.bin-music.com.tw/album/artist_album/5ed80323cb98f-lw500h500.jpg']
  ];
  const sourceLinks = [
    ['相信音樂 五月天藝人專區','官方身份、作品與藝人介紹入口','https://www.bin-music.com.tw/artist/MAYDAY'],
    ['5525+2 台北大巨蛋新聞','台北大巨蛋年度場次與主線來源','https://www.bin-music.com.tw/news/2409'],
    ['5525 起跑 / 台中跨年線','台中起跑、跨年與 5525 主線敘事','https://www.bin-music.com.tw/news/1985'],
    ['Mayday.jp Discography','海外作品與日文資料入口','https://www.mayday.jp/discography/']
  ];
  const state = { view:'map', city:'台北', track:'倔強 · 現場心跳版', map:null, tile:null, markers:[] };
  const viewLabels = {map:'巡演地圖',albums:'時光唱片室',songs:'歌曲宇宙',books:'書籍出版',timeline:'歷程'};
  const timeline = [['1997','成軍與校園時期'],['1999','第一張創作專輯'],['2003','時光機與華語樂團辨識度'],['2011','第二人生大型概念時期'],['2017','LiFE 人生無限公司'],['2023','5525 回到那一天起跑'],['2026','5525+2 年度延伸']];
  const activeCity = () => cities.find(c => c.city === state.city) || cities[0];
  const app = () => $('#app');
  function render(){
    app().innerHTML = `<div class="ml-app"><header class="top glass"><a class="brand" href="#" data-view="map"><img src="./mayday-logo.svg?v=32.0.0" alt="Mayday"><span><b>MAYDAYLAND</b><small>Clean Product Build · v32</small></span></a><nav class="nav">${Object.entries(viewLabels).map(([id,label])=>`<button class="${state.view===id?'active':''}" data-view="${id}">${label}</button>`).join('')}</nav><label class="search">⌕<input id="search" placeholder="搜索城市、場館、歌曲…" autocomplete="off"></label></header><section class="product-hero"><article class="hero-copy glass"><span class="kicker">Product rebuild after layout audit</span><h1>五月天巡演地圖與時光資料館</h1><p>v32 不再疊 widget，而是用單一產品架構承載地圖、城市、作品、歌單、出版與時間線。這版先把視覺秩序、閱讀節奏和資料入口做厚。</p></article><aside class="hero-score glass">${score('架構穩定','1 套入口','0 舊版疊層',100)}${score('內容完整','72 分','持續補素材',72)}${score('城市檔案',String(cities.length),'可切換節點',78)}${score('下一門檻','85 分','未到收貨',68)}</aside></section><main class="shell"><aside class="rail panel glass">${rail()}</aside><section class="stage">${views()}</section><aside class="dossier panel glass">${cityPanel(activeCity())}</aside></main></div>`;
    bind();
    if(state.view === 'map') requestAnimationFrame(initMap);
  }
  function score(title,big,small,value){return `<article class="score-card"><span class="kicker">${esc(title)}</span><b>${esc(big)}</b><small>${esc(small)}</small><div class="meter" style="--v:${value}%"><i></i></div></article>`;}
  function rail(){const total=cities.reduce((sum,c)=>sum+c.visits,0);return `<span class="kicker">Route index</span><h2>城市熱度</h2><p class="copy">點選城市會同步地圖、右側詳情與歌單。去過越多次，地圖熱點越大、色彩越強。</p><div class="pill-row"><span class="pill">${total} 熱度</span><span class="pill">${cities.length} 城市</span></div><div class="city-list">${cities.map(c=>`<button class="city-btn ${c.city===state.city?'active':''}" data-city="${esc(c.city)}"><b>${esc(c.city)}</b><span>${c.visits}</span><small>${esc(c.venue)}</small></button>`).join('')}</div>`;}
  function views(){return `<section class="view ${state.view==='map'?'active':''}" data-page="map">${mapView()}</section><section class="view ${state.view==='albums'?'active':''}" data-page="albums">${albumsView()}</section><section class="view ${state.view==='songs'?'active':''}" data-page="songs">${songsView()}</section><section class="view ${state.view==='books'?'active':''}" data-page="books">${booksView()}</section><section class="view ${state.view==='timeline'?'active':''}" data-page="timeline">${timelineView()}</section>${player()}`;}
  function mapView(){return `<article class="map-card panel glass"><div class="section-head"><div><span class="kicker">Zoom-style heat map</span><h2>巡演熱度地圖</h2><p class="copy">使用真實 Web 地圖層。城市熱度以圓點半徑與透明度呈現，避免再用假地圖。</p></div><div class="layer-tabs"><button class="chip" data-layer="street">街道</button><button class="chip" data-layer="dark">深色</button></div></div><div id="tourMap" class="map-wrap"></div><div class="legend"><span><i class="dot"></i>高熱度城市</span><span><i class="dot" style="background:var(--gold)"></i>年度主線</span><span><i class="dot" style="background:var(--pink)"></i>待補素材</span></div></article><article class="panel glass"><div class="section-head"><div><span class="kicker">Editorial direction</span><h2>下一步不再亂加卡片</h2></div></div><div class="wide-grid"><div class="card"><h3>一個頁面，一個主任務</h3><p>地圖頁負責探索城市；唱片室負責作品；歌曲頁負責歌單；來源牆負責可信度。</p></div><div class="card"><h3>不再使用 fixed 浮層堆疊</h3><p>播放器和詳情都在正常文檔流內，降低遮擋風險。</p></div></div></article>`;}
  function cityPanel(c){return `<div class="city-visual" style="background:linear-gradient(135deg,#091426,${c.tone},#13253d)"><div><span class="kicker">City dossier</span><h2>${esc(c.city)}</h2><p>${esc(c.level)} · ${esc(c.years)}</p></div></div><div class="pill-row"><span class="pill">${c.visits} 次熱度</span><span class="pill">完成度 ${c.score}%</span><span class="pill">${esc(c.venue)}</span></div><p class="copy">${esc(c.mood)}</p><section><div class="section-head"><h2>推薦歌單</h2></div><div class="setlist">${c.set.map((s,i)=>`<div class="track"><span>${i+1}. ${esc(s)}</span><button data-track="${esc(s)}">播放</button></div>`).join('')}</div></section><section><div class="section-head"><h2>補完 Roadmap</h2></div><ul class="roadmap">${c.tasks.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></section>${c.source !== '#' ? `<a class="primary source" href="${esc(c.source)}" target="_blank" rel="noopener">官方來源</a>` : `<div class="empty">此城市仍需要補官方來源與授權圖片。</div>`}`;}
  function albumsView(){return `<article class="panel glass"><div class="section-head"><div><span class="kicker">Discography room</span><h2>時光唱片室</h2><p class="copy">先使用官方封面入口作為素材基底，後續補曲目、製作資訊與巡演關聯。</p></div></div><div class="grid">${albums.map(a=>`<article class="album-card"><span class="cover"><img src="${esc(a[2])}" alt="${esc(a[0])}" loading="lazy"></span><b>${esc(a[0])}</b><small>${esc(a[1])} · 官方封面入口</small></article>`).join('')}</div></article>`;}
  function songsView(){return `<article class="panel glass"><div class="section-head"><div><span class="kicker">Setlist universe</span><h2>歌曲宇宙</h2><p class="copy">以城市歌單切入，讓歌曲和地圖產生關係，而不是孤立列表。</p></div></div><div class="wide-grid">${cities.slice(0,6).map(c=>`<article class="card"><span class="kicker">${esc(c.city)} setlist</span><h3>${esc(c.level)}</h3><div class="setlist">${c.set.map(s=>`<div class="track"><span>${esc(s)}</span><button data-track="${esc(s)}">播放</button></div>`).join('')}</div></article>`).join('')}</div></article>`;}
  function booksView(){return `<article class="panel glass"><div class="section-head"><div><span class="kicker">Books & source wall</span><h2>書籍出版與來源牆</h2><p class="copy">出版品、場刊、票根、照片牆會放在乾淨資料結構內，避免再用浮層亂堆。</p></div></div><div class="wide-grid"><article class="card"><h3>出版品待補</h3><p>書籍、樂譜、場刊、票根、巡演特刊需要逐項補封面與來源。</p></article><article class="card"><h3>素材規則</h3><p>圖片只使用官方可訪問入口或自有素材，不再用無來源佔位圖冒充完成品。</p></article></div><div class="source-wall" style="margin-top:14px">${sourceLinks.map(s=>`<a href="${esc(s[2])}" target="_blank" rel="noopener"><span><b>${esc(s[0])}</b><small>${esc(s[1])}</small></span><b>↗</b></a>`).join('')}</div></article>`;}
  function timelineView(){return `<article class="panel glass"><div class="section-head"><div><span class="kicker">Timeline</span><h2>歷程展覽牆</h2><p class="copy">時間線保持單一展覽牆形式，後續每個節點連回專輯、城市和官方來源。</p></div></div><div class="timeline">${timeline.map(t=>`<div class="timeline-item"><b>${esc(t[0])}</b><span>${esc(t[1])}</span></div>`).join('')}</div></article>`;}
  function player(){return `<footer class="player glass"><div class="now"><i class="disc"></i><span><small>MAYDAYLAND RADIO</small><b id="nowTrack">${esc(state.track)}</b></span></div><div class="player-actions"><button data-player="prev">‹</button><button data-player="play">▶</button><button data-player="next">›</button></div></footer>`;}
  function bind(){
    $$('[data-view]').forEach(btn=>btn.addEventListener('click',e=>{e.preventDefault();const target=btn.getAttribute('data-view');if(target&&viewLabels[target]){state.view=target;render();}}));
    $$('[data-city]').forEach(btn=>btn.addEventListener('click',()=>{state.city=btn.getAttribute('data-city')||state.city;state.view='map';render();}));
    $$('[data-track]').forEach(btn=>btn.addEventListener('click',()=>{state.track=`${btn.getAttribute('data-track')} · ${state.city} 現場版`;const now=$('#nowTrack');if(now)now.textContent=state.track;}));
    $$('[data-layer]').forEach(btn=>btn.addEventListener('click',()=>setLayer(btn.getAttribute('data-layer')||'street')));
    const search=$('#search');if(search){search.addEventListener('input',()=>{const q=search.value.trim().toLowerCase();const match=cities.find(c=>(c.city+c.venue+c.set.join('')).toLowerCase().includes(q));if(q&&match){state.city=match.city;updateCityOnly();}});}
  }
  function updateCityOnly(){const dossier=$('.dossier');if(dossier)dossier.innerHTML=cityPanel(activeCity());$$('.city-btn').forEach(btn=>btn.classList.toggle('active',btn.getAttribute('data-city')===state.city));focusMap(activeCity());bind();}
  function initMap(){if(typeof L==='undefined')return;const el=$('#tourMap');if(!el)return;if(state.map){state.map.remove();state.map=null;}state.map=L.map(el,{zoomControl:true,attributionControl:true}).setView([27.8,116.5],5);setLayer('street');L.polyline(cities.map(c=>[c.lat,c.lng]),{color:'#64e8ff',weight:2,opacity:.65,dashArray:'6 8'}).addTo(state.map);state.markers=cities.map(c=>{const marker=L.circleMarker([c.lat,c.lng],{radius:Math.max(8,Math.min(28,c.visits*1.15)),color:'#fff',weight:1.5,fillColor:c.tone,fillOpacity:Math.min(.82,.34+c.visits/32)}).addTo(state.map);marker.bindPopup(`<b>${esc(c.city)}</b><br>${esc(c.venue)}<br>熱度 ${c.visits}`);marker.on('click',()=>{state.city=c.city;updateCityOnly();});return marker;});focusMap(activeCity(),false);}
  function setLayer(type){if(!state.map)return;if(state.tile)state.map.removeLayer(state.tile);const dark='https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png';const street='https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';const url=type==='dark'?dark:street;const attr=type==='dark'?'&copy; OpenStreetMap &copy; CARTO':'&copy; OpenStreetMap contributors';state.tile=L.tileLayer(url,{maxZoom:18,attribution:attr}).addTo(state.map);}
  function focusMap(c,openPopup=true){if(!state.map)return;state.map.setView([c.lat,c.lng],Math.max(state.map.getZoom(),6),{animate:true});const idx=cities.findIndex(x=>x.city===c.city);if(openPopup&&state.markers[idx])state.markers[idx].openPopup();}
  document.addEventListener('DOMContentLoaded',render);
})();
