(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const css=`
.city-evidence{margin-top:14px;padding:14px;border-radius:16px;border:1px solid rgba(255,255,255,.09);background:linear-gradient(145deg,rgba(255,255,255,.045),rgba(255,255,255,.018))}.city-evidence[data-level="official-primary"]{border-color:rgba(40,215,255,.34)}.city-evidence[data-level="verified"]{border-color:rgba(255,211,106,.34)}.city-evidence[data-level="pending"]{border-style:dashed}.e-head{display:flex;justify-content:space-between;gap:12px;align-items:center}.e-badge{display:inline-flex;align-items:center;gap:7px;padding:6px 8px;border-radius:999px;border:1px solid rgba(255,255,255,.12);font:900 10px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.04em}.e-badge:before{content:"";width:7px;height:7px;border-radius:50%;background:#71869b}.city-evidence[data-level="official-primary"] .e-badge:before{background:#28d7ff;box-shadow:0 0 14px rgba(40,215,255,.8)}.city-evidence[data-level="verified"] .e-badge:before{background:#ffd36a}.e-count{color:#8499ac;font:800 10px ui-monospace,SFMono-Regular,Menlo,monospace}.e-venue{margin:12px 0 4px;font-size:14px}.e-scope{margin:0;color:#8fa4b7;font-size:11px;line-height:1.55}.e-record{margin:10px 0 0;padding:9px 10px;border-radius:11px;background:rgba(255,211,106,.07);font-size:11px;color:#d8c895}.e-dates{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.e-date{padding:5px 7px;border-radius:8px;background:rgba(255,255,255,.05);font:800 10px ui-monospace,SFMono-Regular,Menlo,monospace;color:#b9c8d6}.e-links{display:flex;gap:7px;flex-wrap:wrap;margin-top:11px}.e-links a{padding:6px 8px;border-radius:9px;border:1px solid rgba(255,255,255,.1);font-size:10px;color:#9fdfff;text-decoration:none}.e-links a:hover{border-color:rgba(40,215,255,.45)}.city-card-certified{position:relative;overflow:hidden}.city-card-certified:before{content:"";position:absolute;left:0;top:0;bottom:0;width:2px;background:rgba(40,215,255,.55)}.city-editorial-note{display:inline-flex;margin-top:9px;padding:5px 7px;border-radius:8px;background:rgba(255,255,255,.04);color:#8297aa;font:800 9px ui-monospace,SFMono-Regular,Menlo,monospace}.city-evidence-summary{grid-column:1/-1;padding:20px 22px;border-radius:22px;border:1px solid rgba(40,215,255,.18);background:radial-gradient(circle at 90% 10%,rgba(40,215,255,.1),transparent 28%),rgba(255,255,255,.025)}.city-evidence-summary h2{margin:7px 0 8px;font-size:clamp(28px,4vw,48px)}.city-evidence-summary p{max-width:780px;color:#95a9bb}.city-evidence-summary .summary-stats{display:flex;gap:8px;flex-wrap:wrap;margin-top:13px}.city-evidence-summary .summary-stats span{padding:7px 9px;border-radius:999px;background:rgba(255,255,255,.05);font:800 10px ui-monospace,SFMono-Regular,Menlo,monospace;color:#a8bac9}@media(max-width:620px){.e-head{align-items:flex-start;flex-direction:column}.city-evidence{padding:12px}.e-links a{max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}}
`;
let registry=null,observer=null;
const nameMap={'臺北':'台北','臺中':'台中','高雄市':'高雄'};
function normalize(n){return nameMap[n]||String(n||'').trim()}
function injectCss(){if($('#city-v121-style'))return;const s=document.createElement('style');s.id='city-v121-style';s.textContent=css;document.head.appendChild(s)}
function findEvidenceByName(name){if(!registry?.cities)return null;name=normalize(name);return Object.values(registry.cities).find(x=>normalize(x.city)===name)||null}
function badgeLabel(e){return e?.presentation?.venueBoardBadge||({'official-primary':'OFFICIAL PRIMARY','verified':'VERIFIED','editorial':'EDITORIAL MODEL','pending':'PENDING EVIDENCE'}[e?.status]||'PENDING EVIDENCE')}
function evidenceHtml(e,compact=false){if(!e)return `<section class="city-evidence" data-level="pending"><div class="e-head"><span class="e-badge">PENDING EVIDENCE</span><span class="e-count">0 VERIFIED DATES</span></div><p class="e-scope">此城市目前保留產品／編輯模型資料，尚未把未核實場次包裝成官方歷史紀錄。</p></section>`;
const p=e.presentation||{},dates=Array.isArray(e.verifiedDates)?e.verifiedDates:[],sources=Array.isArray(e.sources)?e.sources:[],shown=dates.slice(0,compact?4:8),total=p.verifiedHistoricalTotal??p.historicalVisitTotal,scope=p.historicalTotalScope||p.confidence||'verified venue/date claims only';
return `<section class="city-evidence" data-level="${esc(e.status||'verified')}"><div class="e-head"><span class="e-badge">${esc(badgeLabel(e))}</span><span class="e-count">${dates.length} VERIFIED DATE${dates.length===1?'':'S'}</span></div><div class="e-venue"><b>${esc(e.venue||'Venue evidence')}</b></div><p class="e-scope">${esc(scope)}</p>${typeof total==='number'?`<div class="e-record"><b>${total} SHOWS</b> · ${esc(p.historicalTotalScope||'scoped verified record')}</div>`:''}${shown.length?`<div class="e-dates">${shown.map(d=>`<span class="e-date">${esc(d)}</span>`).join('')}${dates.length>shown.length?`<span class="e-date">+${dates.length-shown.length}</span>`:''}</div>`:''}${sources.length?`<div class="e-links">${sources.slice(0,compact?1:3).map((s,i)=>`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.publisher||`SOURCE ${i+1}`)}</a>`).join('')}</div>`:''}</section>`}
function decorateCityCards(){const page=$('#page-city');if(!page||!registry)return;const grid=$('.grid',page);if(!grid)return;if(!$('.city-evidence-summary',grid)){const rows=Object.values(registry.cities||{}),official=rows.filter(x=>x.status==='official-primary').length,verified=rows.filter(x=>x.status==='verified').length,dates=rows.reduce((n,x)=>n+(x.verifiedDates?.length||0),0);grid.insertAdjacentHTML('afterbegin',`<section class="city-evidence-summary"><span class="kicker">EVIDENCE-NATIVE CITY DOSSIER · v121</span><h2>城市不是熱度數字，而是可追溯的場館記憶。</h2><p>Venue Board 現在直接讀取 evidence registry。官方與可靠來源、已核實日期、scoped historical record 和產品 editorial heat 分開呈現，避免把視覺 KPI 誤當官方歷史總場次。</p><div class="summary-stats"><span>${official} OFFICIAL PRIMARY</span><span>${verified} VERIFIED</span><span>${dates} VERIFIED DATES</span><span>EDITORIAL HEAT ≠ SHOW TOTAL</span></div></section>`)}
$$(':scope > article.card',grid).forEach(card=>{if(card.dataset.evidenceV121)return;const h=$('h3',card);if(!h)return;const name=normalize(h.textContent.split('·')[0]);const e=findEvidenceByName(name);card.dataset.evidenceV121='1';if(e)card.classList.add('city-card-certified');const legend=$('.legend',card);if(legend){const first=$('span',legend);if(first){const m=first.textContent.match(/\d+/);if(m)first.innerHTML=`<i style="background:#ffd36a"></i>EDITORIAL HEAT · ${m[0]}`}}
card.insertAdjacentHTML('beforeend',`<div class="city-editorial-note">VISITS / HEAT = EDITORIAL MODEL</div>${evidenceHtml(e,false)}`)})}
function decorateCityBox(){const box=$('#cityBox');if(!box||!registry)return;const h=$('.city-hero h2',box)||$('h2',box);if(!h)return;const name=normalize(h.textContent);const key=`${name}:${registry.version||''}`;if(box.dataset.evidenceV121===key)return;box.dataset.evidenceV121=key;$('.city-evidence',box)?.remove();const e=findEvidenceByName(name);box.insertAdjacentHTML('beforeend',evidenceHtml(e,true));const kv=$('.kv',box);if(kv){const heat=$('.kv div:first-child small',box);if(heat)heat.textContent='EDITORIAL HEAT'}}
function decorate(){decorateCityCards();decorateCityBox()}
async function load(){try{const r=await fetch('./data/city-evidence-v94.json?v=121.0.0',{cache:'no-cache'});if(!r.ok)throw new Error(`HTTP ${r.status}`);registry=await r.json();decorate();observer=new MutationObserver(()=>queueMicrotask(decorate));const box=$('#cityBox');if(box)observer.observe(box,{childList:true,subtree:true});window.MAYDAYLAND_CITY_EVIDENCE={version:'v121',registryVersion:registry.version,cities:Object.keys(registry.cities||{}).length,status:'ready'}}catch(err){console.warn('[Maydayland v121] city evidence unavailable',err);window.MAYDAYLAND_CITY_EVIDENCE={version:'v121',status:'degraded',error:String(err)}}}
function polish(){const brand=$('.brand small');if(brand)brand.textContent='v121 · City Evidence';const perf=$('.perf span');if(perf)perf.textContent='lightweight shell · evidence + media on demand';const footer=$('.footer .wrap');if(footer)footer.textContent='Maydayland v121 · evidence-native City Dossier + Album Room + Songs Universe · external media stays on demand.';document.documentElement.dataset.maydaylandRelease='v121';document.documentElement.dataset.maydaylandRuntime='v121-ready'}
function activateV122(){if(document.querySelector('script[data-books-v122]'))return;const s=document.createElement('script');s.src='./books-v122.js?v=122.0.0';s.defer=true;s.dataset.booksV122='1';document.head.appendChild(s)}
function activateV123(){if(document.querySelector('script[data-timeline-v123]'))return;const s=document.createElement('script');s.src='./timeline-v123.js?v=123.0.0';s.defer=true;s.dataset.timelineV123='1';document.head.appendChild(s)}
function init(){injectCss();polish();load();activateV122();activateV123()}
if(document.readyState==='complete')setTimeout(init,0);else addEventListener('load',()=>setTimeout(init,0),{once:true});
})();