const DAY=86400000;
export function parseDate(value){if(!value)return null;const d=new Date(`${value}T00:00:00`);return Number.isNaN(d.getTime())?null:d}
export function formatISO(date){if(!(date instanceof Date)||Number.isNaN(date.getTime()))return'';return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
export function weekdayLabel(date,locale='zh-HK'){if(!(date instanceof Date)||Number.isNaN(date.getTime()))return'';return new Intl.DateTimeFormat(locale,{weekday:'long'}).format(date)}
export function daysBetween(a,b){const da=parseDate(a),db=parseDate(b);if(!da||!db)return null;return Math.round((db-da)/DAY)}
export function addToDate(value,{days=0,months=0,years=0}={}){const d=parseDate(value);if(!d)return null;const out=new Date(d);if(years)out.setFullYear(out.getFullYear()+Number(years||0));if(months)out.setMonth(out.getMonth()+Number(months||0));if(days)out.setDate(out.getDate()+Number(days||0));return out}
export function describeDate(value,locale='zh-HK'){const d=parseDate(value);if(!d)return null;return{iso:formatISO(d),weekday:weekdayLabel(d,locale),timestamp:d.getTime()}}
export function parseHolidayList(value=''){return new Set(String(value).split(/[\s,;，；]+/).map(x=>x.trim()).filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x)))}
export function workdaysBetween(start,end,holidays=''){let a=parseDate(start),b=parseDate(end);if(!a||!b)return null;const reversed=a>b;if(reversed)[a,b]=[b,a];const holidaySet=holidays instanceof Set?holidays:parseHolidayList(holidays);let workdays=0,weekends=0,holidayCount=0,total=0;for(let d=new Date(a);d<=b;d.setDate(d.getDate()+1)){total++;const iso=formatISO(d),day=d.getDay();if(day===0||day===6){weekends++;continue}if(holidaySet.has(iso)){holidayCount++;continue}workdays++}return{workdays,weekends,holidays:holidayCount,total,reversed}}
