// Context-specific pushback and firm rebukes. Keys are private to the reply picker.
;(function(){
const rows=[
// id, retort (Traditional, Simplified, English, Cantonese), reprimand (same order)
["w01",["你說今天交，今天還剩幾個小時？","你说今天交，今天还剩几个小时？","You said today. How much of today is left?","你話今日交，今日仲剩幾多個鐘？"],["資料一直沒交，已經影響整合。現在請給我檔案或明確時間。","资料一直没交，已经影响整合。现在请给我文件或明确时间。","The missing file is holding up the work. Send it now or give me a firm time.","份資料一直未交，已經阻住整合。依家請俾檔案或者確實時間。"]],
["w07",["這項任務什麼時候悄悄改了負責人？","这项任务什么时候悄悄换了负责人？","When did this task quietly change owners?","呢項工作幾時靜雞雞換咗負責人？"],["不要把你負責的事情說成是我沒做。請把分工講清楚。","不要把你负责的事说成是我没做。请把分工说清楚。","Stop presenting your task as my failure. Let's state who owns it.","唔好將你負責嘅事講成我冇做。請講清楚分工。"]],
["w15",["責任可以追，但不能跳過真正的經手人。","责任可以追，但不能跳过真正经手的人。","We can trace responsibility, starting with who actually handled it.","責任可以追，但唔可以跳過真正經手嗰個。"],["這項失誤不在我的交付範圍內。請先核對紀錄，再指責我。","这项失误不在我的交付范围内。请先核对记录，再指责我。","This error is outside my work. Check the record before assigning blame.","呢個錯唔喺我交付範圍。請先對紀錄，再怪我。"]],
["w17",["今天下班前才說今晚要做，時間不會跟著變長。","今天下班前才说今晚要做，时间也不会跟着变长。","A late request doesn't make tonight any longer.","就嚟放工先話今晚要做，時間唔會跟住變長。"],["這麼晚才通知我加班，我無法安排。下次請提前確認。","这么晚才通知我加班，我无法安排。下次请提前确认。","You can't assign tonight's overtime at the last minute. Please plan it earlier.","咁遲先通知我加班，我安排唔到。下次請早啲確認。"]],
["w20",["我的待辦清單還沒開放認領你的工作。","我的待办清单还没开放认领你的工作。","My to-do list isn't taking ownership of your tasks.","我張待辦清單未開放認領你啲工作。"],["這是你負責的工作，不要一再交給我代做。","这是你负责的工作，不要一再交给我代做。","This is your task. Stop repeatedly handing it to me to do for you.","呢件係你負責嘅工作，唔好再三交俾我代做。"]],
["w21",["成果可以分享，作者名單也請寫對。","成果可以分享，作者名单也请写对。","Share the result, but credit the right person.","成果可以分享，作者名單都請寫啱。"],["剛才那部分由我完成。請立即更正對外的歸屬。","刚才那部分由我完成。请立即更正对外的归属。","I completed that part. Please correct the credit now.","頭先嗰部分係我做。請即刻更正對外嘅歸屬。"]],
["w24",["「大家一起」怎麼最後只剩我的名字？","“大家一起”怎么最后只剩我的名字？","How did 'everyone's responsibility' become just my name?","『大家一齊』點解最後淨係剩我個名？"],["請按實際分工追查問題，不要只找一個人承擔。","请按实际分工查问题，不要只找一个人承担。","Review the actual ownership. Don't place the whole problem on one person.","請按實際分工查問題，唔好淨係搵一個人孭。"]],
["s02",["小組作業不是我們替你的部分倒數。","小组作业不是我们替你的部分倒数。","The group deadline isn't a countdown for us to do your part.","小組功課唔係我哋幫你嗰部分倒數。"],["你答應的部分還沒交，大家無法整合。今晚請交出來。","你答应的部分还没交，大家无法整合。今晚请交出来。","Your part is still missing and we can't combine the work. Send it tonight.","你應承嗰部分仲未交，大家整合唔到。今晚請交。"]],
["s04",["借筆記可以，借我的名字交作業不行。","借笔记可以，借我的名字交作业不行。","You can borrow my notes, not my answer sheet.","借筆記可以，借我份功課當自己嘅就唔得。"],["不要再要求抄我的作業。請自己完成。","不要再要求抄我的作业。请自己完成。","Stop asking to copy my homework. Do your own work.","唔好再叫我俾你抄功課。請自己做。"]],
["st07",["分組不代表有人的名字能代替工作。","分组不代表有人只写名字就算做了。","Being in the group isn't the same as doing the work.","分咗組唔代表寫個名就當做咗。"],["目前分工不公平。請今天完成你答應的部分。","目前分工不公平。请今天完成你答应的部分。","The workload is uneven. Complete the part you agreed to today.","依家分工唔公平。請今日做完你應承嗰部分。"]],
["fa05",["照顧是全家的事，我不是唯一的值班表。","照顾是全家的事，我不是唯一的值班表。","Care is a family job. I can't be the entire rota.","照顧係全家嘅事，我唔係唯一一張當值表。"],["別再把所有照顧安排默認交給我。今天把分工排出來。","别再默认把所有照顾安排交给我。今天把分工排出来。","Stop assigning all the care to me by default. Let's divide it today.","唔好再當所有照顧都係我做。今日排清楚分工。"]],
["fa07",["親密不等於把手機交出去受檢查。","亲密不等于把手机交出去接受检查。","Being close doesn't turn my phone into something you inspect.","親密唔等於要交部手機出嚟俾你查。"],["不要再要求查我的手機。我願意談不安，但要尊重彼此私隱。","不要再要求查我的手机。我愿意谈不安，但要尊重彼此隐私。","Stop demanding to inspect my phone. We can discuss trust while respecting privacy.","唔好再要求查我部手機。我願意傾不安，但要尊重彼此私隱。"]],
["e04",["孩子不是拿來排親戚榜的。","孩子不是拿来排亲戚榜的。","Children aren't entries on a family leaderboard.","小朋友唔係用嚟排親戚榜嘅。"],["請不要再當著孩子比較成績。這樣會傷到他。","请不要再当着孩子比较成绩。这样会伤到他。","Please stop comparing children in front of them. It hurts them.","請唔好再當住小朋友比較成績，咁樣會傷到佢。"]],
["e05",["「偷偷給」不會讓約定自動失效。","“偷偷给”也不会让约定自动失效。","Giving it secretly doesn't cancel our agreement.","『偷偷俾』唔會令個約定自動失效。"],["已經說過不要給孩子吃這個，請停止瞞著我們餵。","已经说过不要给孩子吃这个，请别再瞒着我们喂。","We said not to give the child that food. Please stop doing it behind our backs.","已經講過唔好俾小朋友食呢樣，請唔好再瞞住我哋餵。"]],
["fr03",["我的時間不是你改主意時的緩衝區。","我的时间不是你改主意时的缓冲区。","My time isn't a buffer for your last-minute changes.","我嘅時間唔係你臨時改主意嘅緩衝區。"],["你又臨時取消，我已經為此留了時間。下次請提前說。","你又临时取消，我已经为此留了时间。下次请提前说。","You canceled again after I set time aside. Please tell me earlier next time.","你又臨時取消，我已經預咗時間。下次請早啲講。"]],
["fr06",["約的時間是見面時間，不是你的出門提醒。","约的时间是见面时间，不是你的出门提醒。","Our meeting time isn't your reminder to leave home.","約嗰個時間係見面時間，唔係提醒你出門嘅時間。"],["你每次都遲到很久。下次若做不到準時，請先說清楚。","你每次都迟到很久。下次如果不能准时，请提前说清楚。","You're late every time. If you can't make the time, say so in advance.","你次次都遲到好耐。下次準時唔到，請早啲講清楚。"]],
["fr07",["我借你用，不是送你收藏。","我借你用，不是送你收藏。","I lent it to you; I didn't donate it to your collection.","我借俾你用，唔係送俾你收藏。"],["這件東西已經借了很久。請在週五前還給我。","这件东西已经借了很久。请在周五前还给我。","You've kept it long enough. Return it by Friday.","件嘢借咗好耐。請星期五之前還俾我。"]],
["r04",["我出門是生活，不是啟動即時定位直播。","我出门是生活，不是开启实时定位直播。","Going out isn't a live location broadcast.","我出街係生活，唔係開即時定位直播。"],["不要再要求我每一刻報備位置。我會告知安排，但不接受監控。","不要再要求我每一刻报备位置。我会告诉你安排，但不接受监控。","Stop asking for my location every moment. I'll share plans, but I won't be monitored.","唔好再要求我每刻報位置。我會講安排，但唔接受監控。"]],
["r06",["需要空間可以說，消失幾天不會讓問題自己解決。","需要空间可以说，消失几天不会让问题自己解决。","You can ask for space. Disappearing for days won't resolve this.","要空間可以講，消失幾日唔會令問題自己解決。"],["請停止用幾天不回話來處理衝突。至少告訴我何時能談。","请别再用几天不回话来处理冲突。至少告诉我何时能谈。","Stop going silent for days during conflict. Tell me when we can talk.","請唔好再用幾日唔覆嚟處理衝突。至少話我知幾時可以傾。"]],
["so02",["夜深了，這音量比我的鬧鐘還積極。","夜深了，这音量比我的闹钟还积极。","It's late, and that noise is working harder than my alarm.","夜喇，呢個音量比我個鬧鐘仲積極。"],["已經深夜了，噪音仍然很大。請現在降低音量。","已经深夜了，噪音还是很大。请现在降低音量。","It's late and the noise is still loud. Please turn it down now.","已經夜深，聲仲係好大。請依家細聲啲。"]],
["so03",["我說不喝，不是在等下一輪勸酒。","我说不喝，不是在等下一轮劝酒。","I said no to the drink, not yes to another sales pitch.","我話唔飲，唔係等你再勸多輪。"],["請停止勸我喝酒。我已經明確拒絕。","请别再劝我喝酒。我已经明确拒绝了。","Stop pressuring me to drink. I've given you my answer.","請唔好再勸我飲酒。我已經講清楚唔飲。"]],
["so04",["隊伍的起點在後面，不在我前面。","队伍从后面开始，不是从我前面开始。","The queue starts behind us, not in front of me.","條隊由後面開始，唔係我前面。"],["這裡大家都在排隊。請回到隊尾。","这里大家都在排队。请到队尾。","Everyone here is waiting. Please go to the back of the queue.","呢度大家都排緊隊。請去返隊尾。"]],
["sv04",["貨是你們發錯的，售後也不能寄給我處理。","货是你们发错的，售后也不能寄给我处理。","You shipped the wrong item; you can't ship the fix to me too.","貨係你哋發錯，售後都唔可以寄埋俾我處理。"],["發錯貨是商家的責任。請你們聯繫物流並給我處理方案。","发错货是商家的责任。请你们联系物流并给我处理方案。","The shipping error is yours to resolve. Contact the carrier and give me a solution.","發錯貨係商家責任。請你哋聯絡物流，同我講處理方案。"]],
["sv06",["這筆費用事前沒出現，結帳時倒是很準時。","这笔费用事前没出现，结账时倒是很准时。","That fee was absent up front but right on time for the bill.","呢筆費用事前唔見影，埋單就好準時。"],["這筆費用事前沒有告知。我不同意直接收取，請先說明依據。","这笔费用事前没有告知。我不同意直接收取，请先说明依据。","This fee wasn't disclosed. Don't charge it without explaining the basis first.","呢筆費用事前冇通知。我唔同意直接收，請先講清楚依據。"]],
["j05",["這份試做已經接近正式交付了，報酬在哪一步？","这份试做已经接近正式交付了，报酬在哪一步？","This test looks like client work. Where does payment come in?","呢份試做都就嚟變正式交付，報酬喺邊一步？"],["這超出合理的面試作業範圍。若要使用成果，請先談報酬。","这超出合理的面试作业范围。如果要使用成果，请先谈报酬。","This goes beyond an interview exercise. Discuss payment before using my work.","呢份嘢超出面試作業範圍。要用成果，請先傾報酬。"]],
["b01",["新需求可以加，原來的報價可不會自己長大。","新需求可以加，原来的报价不会自己长大。","The scope can grow; the original quote doesn't grow by itself.","新需求可以加，原本個報價唔會自己長大。"],["這項工作不在原範圍內。請先確認新增費用和交期。","这项工作不在原范围内。请先确认新增费用和交期。","This is outside the agreed scope. Confirm the added cost and timeline first.","呢項工作唔喺原範圍。請先確認加幾多錢同交期。"]],
["b02",["發票已經過期，付款日期也別再流浪了。","发票已经逾期，付款日期也别再漂着了。","The invoice is overdue. Let's give the payment date a home.","張發票已經過期，付款日子都唔好再飄喇。"],["付款期限已過。請今天確認具體到帳日期。","付款期限已过。请今天确认具体到账日期。","Payment is overdue. Confirm the exact payment date today.","付款限期已過。請今日確認確實到帳日子。"]],
["b04",["每次都叫「最後一改」，這個最後已經續了好幾季。","每次都叫“最后一改”，这个最后已经续了好几季。","Every edit is 'the last one.' We're several seasons in.","次次都話『最後一改』，呢個最後都續咗幾季。"],["修改已超出約定次數。請彙總剩餘意見並確認新增費用。","修改已超出约定次数。请汇总剩余意见并确认新增费用。","The agreed revision rounds are over. Consolidate feedback and approve the extra cost.","修改已經超出約定次數。請整合剩低意見，同確認額外費用。"]],
["tr03",["飛機可以延誤，資訊總不能一起失聯。","飞机可以延误，信息总不能一起失联。","The flight is delayed; the updates shouldn't be missing too.","班機可以延誤，資訊唔好一齊失聯。"],["延誤已經很久，現場仍沒有說明。請告知最新時間和安排。","延误已经很久，现场仍没有说明。请告知最新时间和安排。","This delay has gone on without an update. Tell us the latest time and arrangements.","延誤咗咁耐，現場都冇交代。請講最新時間同安排。"]],
["on03",["你這句要是有具體意見，歡迎把暗示換成文字。","你这句要是有具体意见，欢迎把暗示换成文字。","If there's a point behind that hint, feel free to say it plainly.","你句話如果有具體意見，不如將暗示換成文字。"],["請停止在我的動態下反覆挖苦。有意見就直接說。","请别再在我的动态下反复挖苦。有意见就直接说。","Stop leaving repeated digs on my posts. Say your point directly.","請唔好再喺我動態下面反覆挖苦。有意見就直接講。"]],
["on08",["我說了不好笑，笑點就別再靠我承擔。","我说了不好笑，笑点就别再让我承担。","I said it isn't funny. Don't make me carry your punchline.","我講咗唔好笑，笑點唔好再靠我孭。"],["不要再拿這件事開玩笑。我已經說過我不舒服。","不要再拿这件事开玩笑。我已经说过我不舒服。","Stop joking about this. I've already told you it makes me uncomfortable.","唔好再攞呢件事講笑。我已經講過我唔舒服。"]],
["wave7-001",["這份交接的主角目前還沒登場。","这份交接的主角目前还没登场。","The main part of this handover hasn't shown up yet.","呢份交接嘅主角暫時仲未出場。"],["只有標題無法接手。請把實際步驟和進度補齊。","只有标题没法接手。请把实际步骤和进度补齐。","Headings aren't enough to take this over. Fill in the steps and status.","得標題接唔到手。請補齊實際步驟同進度。"]],
["wave7-004",["我可以幫忙補課，但不能代你每週出席。","我可以帮你补课，但不能替你每周出席。","I can help you catch up, but I can't attend class for you each week.","我可以幫你補堂，但唔可以每星期代你上堂。"],["別再每次缺課都要求我拍整本筆記。請自己找課件。","别再每次缺课都让我拍整本笔记。请自己找课件。","Stop asking for my entire notebook every time you miss class. Get the materials yourself.","唔好再次次缺課都叫我影成簿筆記。請自己搵課件。"]],
["wave7-006",["介紹是好意，但我的答覆還輪不到別人代發。","介绍是好意，但我的答复还轮不到别人代发。","The introduction is kind; the answer is still mine to give.","介紹係好意，但我個答覆唔使其他人代發。"],["請不要未經我同意就替我接受工作安排。","请不要没经过我同意就替我接受工作安排。","Please don't accept a job arrangement on my behalf without asking me.","請唔好未經我同意就代我接受工作安排。"]],
["wave7-012",["我的聊天框不接受兩邊輪流投遞戰書。","我的聊天框不接受两边轮流投递战书。","My inbox isn't a drop box for both sides of the argument.","我個 chat 唔收兩邊輪流寄嚟嘅戰書。"],["不要再讓我替你傳傷人的話。你們需要直接談。","别再让我替你传伤人的话。你们需要直接谈。","Stop asking me to pass on hurtful messages. Talk to each other directly.","唔好再叫我幫你傳啲傷人嘅話。你哋需要直接傾。"]],
["wave7-014",["回得慢不代表感情掉線，只是我正在上班。","回得慢不代表感情掉线，只是我正在上班。","A slow reply doesn't mean my feelings went offline. I'm at work.","覆得慢唔代表感情斷線，只係我返緊工。"],["請不要因為我工作時沒秒回就反覆責怪我。","请别因为我工作时没秒回就反复责怪我。","Stop repeatedly blaming me for not replying instantly during work.","請唔好因為我返工冇秒覆就反覆怪我。"]],
["wave7-016",["這張合照還缺一個條件：我答應了嗎？","这张合照还缺一个条件：我答应了吗？","The photo is missing one thing: my agreement.","呢張合照仲差一樣：我應承咗未？"],["我已經說不拍。請放下手機，也不要上傳我的照片。","我已经说不拍了。请放下手机，也别上传我的照片。","I said no to the photo. Put the phone down and don't post me.","我已經講咗唔影。請放低部手機，亦唔好上載我張相。"]],
["wave7-027",["私聊長了翅膀，我可沒有同意它飛到群裡。","私聊长了翅膀，我可没同意它飞到群里。","That private chat grew wings without my permission.","私聊生咗翼，但我冇同意佢飛去群組。"],["沒有問過我就公開私訊，這不可以。請現在刪除截圖。","没问过我就公开私信，这不行。请现在删除截图。","Sharing our private chat without asking isn't okay. Delete it now.","冇問過我就公開私訊，咁唔得。請依家刪咗截圖。"]],
["wave7-028",["我的帳號不是你廣告的免費看板。","我的账号不是你广告的免费展板。","My account isn't a free billboard for your ads.","我個帳號唔係你啲廣告嘅免費看板。"],["我已經要求停止標註。請刪掉現有標註，不要再加。","我已经要求别再标记。请删掉现有标记，别再加。","I asked you to stop tagging me. Remove the existing tags and don't add more.","我已經叫你唔好再 tag。請刪咗依家啲 tag，唔好再加。"]]
];
const scenes=new Map((window.CHAT_SCENARIOS||[]).map(s=>[s.id,s]));
for(const [id,retort,reprimand] of rows){
 const scene=scenes.get(id);if(!scene)throw Error('Missing retort scene '+id);
 for(const [key,lines] of [['retort',retort],['reprimand',reprimand]]){
  const [hant,hans,en,yue]=lines;
  scene.replies.zh[key]={hant,hans};scene.replies.en[key]=en;scene.replies.yue[key]=yue;
 }
}
})();
