;(function(){
var D={
 workplace:{hant:"職場",hans:"职场",en:"Work"},
 study:{hant:"學習",hans:"学习",en:"Study"},
 family:{hant:"家庭",hans:"家庭",en:"Family"},
 parenting:{hant:"育兒",hans:"育儿",en:"Parenting"},
 elder:{hant:"長輩",hans:"长辈",en:"Elders"},
 friends:{hant:"朋友",hans:"朋友",en:"Friends"},
 relationship:{hant:"感情",hans:"感情",en:"Relationship"},
 social:{hant:"社交",hans:"社交",en:"Social"},
 service:{hant:"服務",hans:"服务",en:"Service"},
 job:{hant:"求職",hans:"求职",en:"Job Search"},
 business:{hant:"商務",hans:"商务",en:"Business"},
 travel:{hant:"旅行",hans:"旅行",en:"Travel"},
 medical:{hant:"醫療",hans:"医疗",en:"Medical"},
 online:{hant:"網絡",hans:"网络",en:"Online"}
};
var A=[];
function add(id,domain,relation,goal,title,zhf,zhd,zhr,enf,end,enr,yf,yd,yr){
 A.push({id:id,domain:domain,domainLabel:D[domain],relation:relation,goal:goal,title:title,replies:{
  zh:{formal:{hant:zhf[0],hans:zhf[1]},dark:{hant:zhd[0],hans:zhd[1]},roast:{hant:zhr[0],hans:zhr[1]}},
  en:{formal:enf,dark:end,roast:enr},
  yue:{formal:yf,dark:yd,roast:yr}
 }});
}
add("w15","workplace",
{hant:"上司",hans:"上司",en:"Manager"},{hant:"拒絕背鍋",hans:"拒绝背锅",en:"Refuse misplaced blame"},
{hant:"上司把別人的失誤算到你頭上",hans:"上司把别人的失误算到你头上",en:"Your manager attributes someone else's mistake to you"},
["我想澄清一下這件事的責任邊界。A 是我負責的部分，出現問題的 B 當時由 XX 處理。","我想澄清一下这件事的责任边界。A 是我负责的部分，出现问题的 B 当时由 XX 处理。"],
["我可以對自己的部分負責，但不希望責任範圍在出問題後才突然擴大。","我可以对自己的部分负责，但不希望责任范围在出问题后才突然扩大。"],
["我的職責可以更新，但最好不要在事故發生後才自動新增章節。","我的职责可以更新，但最好不要在事故发生后才自动新增章节。"],
"I'd like to clarify ownership. I was responsible for A, while the issue in B was handled by XX.",
"I'm accountable for my part, but I don't want the scope of responsibility to expand only after something goes wrong.",
"My job description can evolve, but ideally not by adding new chapters after an incident.",
"我想澄清返責任範圍。A 係我負責，出問題嘅 B 當時係 XX 處理。",
"我可以對自己嗰部分負責，但唔想責任範圍出事之後先突然擴大。",
"我份 JD 可以更新，但最好唔好每次出事先自動加新章節。");

add("w16","workplace",
{hant:"同事",hans:"同事",en:"Colleague"},{hant:"請對方別頻繁打斷",hans:"请对方别频繁打断",en:"Ask not to interrupt"},
{hant:"同事不停在你專注工作時插話",hans:"同事不停在你专注工作时插话",en:"A colleague keeps interrupting while you're focused"},
["我現在需要一段不被打斷的時間把這部分做完。你先把問題記著，我 X 點後一起看可以嗎？","我现在需要一段不被打断的时间把这部分做完。你先把问题记着，我 X 点后一起看可以吗？"],
["我現在每被切一次，腦子都要重新開機。X 點後我們集中處理。","我现在每被切一次，脑子都要重新开机。X 点后我们集中处理。"],
["我的腦袋今天不是多分頁瀏覽器，先讓我把這一頁跑完。","我的脑袋今天不是多分页浏览器，先让我把这一页跑完。"],
"I need an uninterrupted block to finish this. Could you note the questions and we review them together after X?",
"Every interruption makes my brain reboot. Let's batch these after X.",
"My brain isn't a multi-tab browser today. Let me finish this tab first.",
"我而家要一段唔被打斷嘅時間做完呢部分。你記低啲問題，X 點後一齊睇得唔得？",
"我而家每俾人 cut 一次，個腦都要重新開機。X 點後集中處理。",
"我個腦今日唔係多分頁 browser，俾我跑完呢一頁先。");

add("st06","study",
{hant:"老師",hans:"老师",en:"Teacher"},{hant:"質疑評分",hans:"质疑评分",en:"Question a grade"},
{hant:"你覺得作業評分可能有誤",hans:"你觉得作业评分可能有误",en:"You think an assignment may have been graded incorrectly"},
["老師您好，我想請教一下這題的扣分標準。我目前的答案是 XX，想了解和標準答案的差異在哪裡。","老师您好，我想请教一下这题的扣分标准。我目前的答案是 XX，想了解和标准答案的差异在哪里。"],
["我不是想爭分數，只是希望知道這幾分到底是輸在哪一步。","我不是想争分数，只是希望知道这几分到底是输在哪一步。"],
["這幾分走得有點突然，我想問問它們具體是在哪一站下車的。","这几分走得有点突然，我想问问它们具体是在哪一站下车的。"],
"Could you help me understand the marking on this question? My answer was XX, and I'd like to see where it differs from the expected approach.",
"I'm not trying to argue for points; I'd just like to know exactly where they were lost.",
"Those marks disappeared rather suddenly. Could you show me which stop they got off at?",
"老師你好，我想問下呢題嘅扣分標準。我答案係 XX，想了解同標準答案差喺邊。",
"我唔係想爭分，只係想知呢幾分究竟輸喺邊一步。",
"呢幾分走得幾突然，我想問下佢哋究竟喺邊個站落咗車。");

add("st07","study",
{hant:"組員",hans:"组员",en:"Teammate"},{hant:"重新分工",hans:"重新分工",en:"Rebalance group work"},
{hant:"小組裡有人工作量明顯太少",hans:"小组里有人工作量明显太少",en:"One group member has significantly less work than others"},
["我們目前的工作量差異比較大，不如重新把剩下的部分攤開分一次，讓每個人負責量更接近。","我们目前的工作量差异比较大，不如重新把剩下的部分摊开分一次，让每个人负责量更接近。"],
["現在這個分工比較像有人做小組作業，有人參觀小組作業。需要重新分。","现在这个分工比较像有人做小组作业，有人参观小组作业。需要重新分。"],
["我們這組好像同時開了參與者席和觀眾席，先把剩下工作重新發牌吧。","我们这组好像同时开了参与者席和观众席，先把剩下工作重新发牌吧。"],
"The workload is uneven right now. Let's redistribute the remaining tasks so everyone's share is closer.",
"The current split looks a bit like some people are doing the group project while others are observing it.",
"Our group seems to have both participant seats and audience seats. Let's redeal the remaining work.",
"而家工作量差得幾遠，不如重新分一次剩低啲部分，等大家負責量接近啲。",
"而家個分工有啲似有人做 group project，有人參觀 group project。要重新分。",
"我哋呢組好似同時有參與席同觀眾席，剩低啲工作重新發牌啦。");

add("fa03","family",
{hant:"伴侶",hans:"伴侣",en:"Partner"},{hant:"談共同開支",hans:"谈共同开支",en:"Discuss shared expenses"},
{hant:"共同生活後開支分擔一直不清楚",hans:"共同生活后开支分担一直不清楚",en:"Shared expenses have been unclear since living together"},
["我想把共同開支的規則定清楚，例如房租、日用品和外食怎麼分，這樣之後不用每次臨時算。","我想把共同开支的规则定清楚，例如房租、日用品和外食怎么分，这样之后不用每次临时算。"],
["感情可以感性一點，帳單最好理性一點。","感情可以感性一点，账单最好理性一点。"],
["愛情可以不算分，但水電煤最好還是算一下。","爱情可以不算分，但水电煤最好还是算一下。"],
"I'd like us to set clear rules for shared expenses such as rent, groceries and eating out so we don't negotiate every time.",
"The relationship can be emotional. The bills should probably be a little more rational.",
"Love doesn't need a scoreboard, but utilities probably still need a calculation.",
"我想定清楚共同開支點分，例如租、日用品同食飯，之後唔使次次臨時計。",
"感情可以感性啲，帳單最好理性啲。",
"愛情可以唔計分，但水電煤最好都係計一計。");

add("p05","parenting",
{hant:"孩子",hans:"孩子",en:"Child"},{hant:"不肯吃飯",hans:"不肯吃饭",en:"Refuses to eat"},
{hant:"孩子一到吃飯就說什麼都不吃",hans:"孩子一到吃饭就说什么都不吃",en:"Your child refuses to eat at mealtimes"},
["你可以選擇吃多少，但我們先坐下來一起吃。今天不用把全部吃完，先試一小口。","你可以选择吃多少，但我们先坐下来一起吃。今天不用把全部吃完，先试一小口。"],
["吃不吃多少可以選，完全不來餐桌不是今天的選項。","吃不吃多少可以选，完全不来餐桌不是今天的选项。"],
["不用跟這碗飯結婚，先認識一口就好。","不用跟这碗饭结婚，先认识一口就好。"],
"You can choose how much to eat, but let's sit together first. You don't have to finish it — just try one bite.",
"You can choose the amount. Skipping the table entirely isn't today's option.",
"You don't have to marry the meal. Just meet one bite first.",
"你可以揀食幾多，但先一齊坐低食。唔使食晒，試一啖先。",
"食幾多可以揀，完全唔上枱就唔係今日選項。",
"唔使同碗飯結婚，認識一啖先就得。");

add("p06","parenting",
{hant:"孩子",hans:"孩子",en:"Child"},{hant:"兄弟姐妹吵架",hans:"兄弟姐妹吵架",en:"Sibling conflict"},
{hant:"兩個孩子都說是對方先動手",hans:"两个孩子都说是对方先动手",en:"Both children say the other one started the fight"},
["我會分別聽你們說，但先不判誰贏。先確認有沒有人受傷，再一個一個說發生了什麼。","我会分别听你们说，但先不判谁赢。先确认有没有人受伤，再一个一个说发生了什么。"],
["現在先停止搶著當原告，兩邊都按順序說。","现在先停止抢着当原告，两边都按顺序说。"],
["法庭現在開庭，但一次只能有一個律師發言。","法庭现在开庭，但一次只能有一个律师发言。"],
"I'll listen to both of you, but we're not deciding a winner first. Let's check for injuries and then hear each version one at a time.",
"Stop competing to be the plaintiff for a moment. Each side gets a turn.",
"Court is now in session, but only one lawyer gets the microphone at a time.",
"我會分開聽你哋講，但唔會先判邊個贏。先睇有冇人整親，再一個一個講。",
"而家先唔好爭住做原告，兩邊輪住講。",
"法庭而家開庭，但一次只可以一個律師發言。");

add("e04","elder",
{hant:"長輩",hans:"长辈",en:"Elder"},{hant:"拒絕比較孩子",hans:"拒绝比较孩子",en:"Stop comparisons"},
{hant:"長輩總拿你家孩子和別人比較",hans:"长辈总拿你家孩子和别人比较",en:"An elder keeps comparing your child with other children"},
["每個孩子的節奏不一樣，我希望我們多看他自己的進步，先不要拿他和別人比較。","每个孩子的节奏不一样，我希望我们多看他自己的进步，先不要拿他和别人比较。"],
["比較可以很快得到一句話，但不一定能幫孩子變得更好。","比较可以很快得到一句话，但不一定能帮孩子变得更好。"],
["別人家的孩子已經很忙了，就先不請他來我們家兼職當 KPI。","别人家的孩子已经很忙了，就先不请他来我们家兼职当 KPI。"],
"Every child develops at a different pace. I'd rather focus on his own progress than compare him with others.",
"Comparisons produce quick comments, but not necessarily better children.",
"Other people's children are busy enough. Let's not hire them as our family's KPI too.",
"每個小朋友節奏唔同，我想多啲睇佢自己進步，唔好成日同人比較。",
"比較可以好快有一句結論，但未必真係幫到小朋友。",
"人哋屋企個小朋友都夠忙，唔好再請佢嚟我哋屋企兼職做 KPI。");

add("fr04","friends",
{hant:"朋友",hans:"朋友",en:"Friend"},{hant:"拒絕八卦",hans:"拒绝八卦",en:"Decline gossip"},
{hant:"朋友一直追問別人的私事",hans:"朋友一直追问别人的私事",en:"A friend keeps pressing you for someone else's private information"},
["這件事是他的私事，我不太方便替他說。如果他想分享，還是讓他自己講比較好。","这件事是他的私事，我不太方便替他说。如果他想分享，还是让他自己讲比较好。"],
["我手上有資訊，但沒有代替本人發布的權限。","我手上有信息，但没有代替本人发布的权限。"],
["我不是他的官方發言人，這場記者會先不開。","我不是他的官方发言人，这场记者会先不开。"],
"That's their private matter, so I don't think it's mine to share. If they want to talk about it, better to let them do so themselves.",
"I may know something, but I don't have publishing rights on their behalf.",
"I'm not their official spokesperson, so this press conference is cancelled.",
"呢件係佢私人事，我唔方便代佢講。佢想分享就等佢自己講會好啲。",
"我手上可能有資料，但冇代本人發布嘅權限。",
"我唔係佢官方發言人，呢場記者會唔開住。");

add("fr05","friends",
{hant:"朋友",hans:"朋友",en:"Friend"},{hant:"安慰失戀",hans:"安慰失恋",en:"Comfort after breakup"},
{hant:"朋友剛失戀，情緒很低落",hans:"朋友刚失恋，情绪很低落",en:"A friend has just gone through a breakup and feels awful"},
["你現在難受很正常，不用急著想開。想說我就聽，不想說我也可以陪你待著。","你现在难受很正常，不用急着想开。想说我就听，不想说我也可以陪你待着。"],
["今天先不要替整段關係做總結，人在最難受的時候通常不是最佳審稿人。","今天先不要替整段关系做总结，人在最难受的时候通常不是最佳审稿人。"],
["今晚先不發表「全人類都不值得」研究報告，樣本量目前只有一個。","今晚先不发表“全人类都不值得”研究报告，样本量目前只有一个。"],
"It's normal to feel awful right now. You don't need to make sense of it yet. If you want to talk, I'll listen; if not, I'll just stay with you.",
"Don't write the final report on the relationship today. We're rarely our best editors at the worst moment.",
"Let's postpone the 'all humans are terrible' research paper tonight. The sample size is currently one.",
"你而家難受好正常，唔使急住睇開。想講我就聽，唔想講我都可以陪你坐住。",
"今日唔好急住幫成段關係寫總結，最難受嗰陣通常唔係最佳審稿人。",
"今晚先唔發表『全人類都唔值得』研究報告，樣本量暫時得一個。");

add("r04","relationship",
{hant:"伴侶",hans:"伴侣",en:"Partner"},{hant:"需要私人空間",hans:"需要私人空间",en:"Ask for personal space"},
{hant:"伴侶希望你時刻報備行蹤",hans:"伴侣希望你时刻报备行踪",en:"Your partner expects constant updates on where you are"},
["我願意讓你知道重要安排，但我不希望日常變成每一步都要報備。我需要保留一些正常的私人空間。","我愿意让你知道重要安排，但我不希望日常变成每一步都要报备。我需要保留一些正常的私人空间。"],
["安全感可以討論，但我不想把關係做成即時定位系統。","安全感可以讨论，但我不想把关系做成实时定位系统。"],
["我是伴侶，不是物流包裹，不需要每個節點都更新軌跡。","我是伴侣，不是物流包裹，不需要每个节点都更新轨迹。"],
"I'm happy to share important plans, but I don't want everyday life to require constant reporting. I need some normal personal space.",
"We can talk about reassurance, but I don't want the relationship to become a live tracking system.",
"I'm your partner, not a parcel. I don't need a tracking update at every checkpoint.",
"我願意講重要安排，但唔想日常每一步都要報備。我都需要正常私人空間。",
"安全感可以傾，但我唔想段關係變成即時定位系統。",
"我係伴侶，唔係物流件，唔使每個節點都更新軌跡。");

add("r05","relationship",
{hant:"曖昧對象",hans:"暧昧对象",en:"Someone you're dating"},{hant:"拒絕繼續發展",hans:"拒绝继续发展",en:"End dating politely"},
{hant:"見了幾次面後你覺得不適合繼續",hans:"见了几次面后你觉得不适合继续",en:"After a few dates you don't want to continue"},
["這幾次相處我很開心，但我感覺我們更適合停在這裡。我不想模糊地拖著，所以想直接跟你說。","这几次相处我很开心，但我感觉我们更适合停在这里。我不想模糊地拖着，所以想直接跟你说。"],
["我不想用慢慢消失代替答案，所以直接說：我不打算繼續往感情方向發展。","我不想用慢慢消失代替答案，所以直接说：我不打算继续往感情方向发展。"],
["這幾次約會體驗不錯，但系統判定比較適合停在體驗版。","这几次约会体验不错，但系统判定比较适合停在体验版。"],
"I've enjoyed spending time together, but I don't feel this is something I want to continue romantically. I didn't want to leave that vague.",
"I don't want to use slow disappearance as an answer, so I'll be clear: I don't want to continue romantically.",
"The dates were a good experience, but the system recommends staying on the trial version.",
"呢幾次相處幾開心，不過我感覺我哋比較適合停喺呢度。我唔想拖住唔講，所以直接話你知。",
"我唔想用慢慢消失代替答案，所以直接講：我唔打算繼續向感情方向發展。",
"呢幾次約會體驗唔錯，不過系統判定比較適合停喺體驗版。");

add("so02","social",
{hant:"鄰居",hans:"邻居",en:"Neighbour"},{hant:"提醒噪音",hans:"提醒噪音",en:"Ask to reduce noise"},
{hant:"鄰居深夜經常很吵",hans:"邻居深夜经常很吵",en:"Your neighbour is often noisy late at night"},
["不好意思想跟你說一下，最近晚上 XX 點後聲音比較明顯，會影響休息。可以麻煩晚一點盡量小聲一些嗎？","不好意思想跟你说一下，最近晚上 XX 点后声音比较明显，会影响休息。可以麻烦晚一点尽量小声一些吗？"],
["白天都好商量，凌晨的低音炮就真的比較難建立鄰里感情。","白天都好商量，凌晨的低音炮就真的比较难建立邻里感情。"],
["我們很想做安靜的好鄰居，不太想做隔牆一起參加派對的鄰居。","我们很想做安静的好邻居，不太想做隔墙一起参加派对的邻居。"],
"Hi, the noise after around XX has been quite noticeable lately and is affecting sleep. Could you please keep it a little quieter late at night?",
"Daytime is easy to negotiate. Late-night bass is a little harder on neighbourly relations.",
"We'd love to be good quiet neighbours, rather than neighbours attending the party through the wall.",
"唔好意思想提一提，最近夜晚 XX 點後聲音幾明顯，會影響休息。可唔可以夜少少盡量細聲啲？",
"日頭乜都好傾，凌晨低音炮就真係比較難建立鄰里感情。",
"我哋想做好鄰居，唔太想隔住幅牆一齊參加 party。");

add("so03","social",
{hant:"飯局",hans:"饭局",en:"Dinner group"},{hant:"拒絕喝酒",hans:"拒绝喝酒",en:"Decline alcohol"},
{hant:"飯局上別人一直勸你喝酒",hans:"饭局上别人一直劝你喝酒",en:"People at dinner keep pressuring you to drink alcohol"},
["謝謝，我今天不喝酒，用這杯一起敬大家就好。","谢谢，我今天不喝酒，用这杯一起敬大家就好。"],
["感情我收下，酒就不需要一起收下了。","感情我收下，酒就不需要一起收下了。"],
["友情可以滿杯，酒杯今天就不用滿了。","友情可以满杯，酒杯今天就不用满了。"],
"Thanks, I'm not drinking today. I'll toast everyone with this instead.",
"I'll happily accept the goodwill. The alcohol doesn't have to come with it.",
"The friendship can be full-strength. The glass doesn't have to be.",
"多謝，我今日唔飲酒，用呢杯一齊敬大家就得。",
"感情我收下，酒就唔使一齊收。",
"友情可以滿杯，酒杯今日就唔使滿。");

add("sv03","service",
{hant:"客服",hans:"客服",en:"Customer service"},{hant:"催處理進度",hans:"催处理进度",en:"Chase support case"},
{hant:"客服案件拖了很多天沒有進展",hans:"客服案件拖了很多天没有进展",en:"A support case has had no progress for days"},
["想跟進一下案件 XX，目前已經 X 天沒有更新。麻煩確認現在的處理狀態和預計下一步時間。","想跟进一下案件 XX，目前已经 X 天没有更新。麻烦确认现在的处理状态和预计下一步时间。"],
["目前我收到最多的更新是「正在處理」，想問一下處理本身有沒有更新。","目前我收到最多的更新是“正在处理”，想问一下处理本身有没有更新。"],
["案件 XX 已經很熟悉等待室了，想問問什麼時候可以輪到它看醫生。","案件 XX 已经很熟悉等待室了，想问问什么时候可以轮到它看医生。"],
"I'm following up on case XX. There has been no update for X days. Could you confirm the current status and expected next step?",
"The update I've received most often is 'being processed'. Could I get an update on the processing itself?",
"Case XX has become very familiar with the waiting room. Any idea when it gets to see the doctor?",
"想跟一跟 case XX，而家已經 X 日冇 update。麻煩確認目前狀態同預計下一步時間。",
"目前我收得最多嘅 update 係『處理中』，想問下個處理本身有冇 update。",
"Case XX 已經好熟等待室，想問下幾時輪到佢睇醫生。");

add("j03","job",
{hant:"面試官",hans:"面试官",en:"Interviewer"},{hant:"不知道答案",hans:"不知道答案",en:"Handle not knowing"},
{hant:"面試時被問到你不會的問題",hans:"面试时被问到你不会的问题",en:"You're asked an interview question you don't know"},
["這個問題我目前沒有足夠把握直接回答。如果讓我處理，我會先從 A、B 兩個方向確認，再驗證 XX。","这个问题我目前没有足够把握直接回答。如果让我处理，我会先从 A、B 两个方向确认，再验证 XX。"],
["我不想現場編一個看起來很像答案的答案。我可以說一下我會怎麼找答案。","我不想现场编一个看起来很像答案的答案。我可以说一下我会怎么找答案。"],
["這題我現在沒有現成答案，但搜尋路線我有，不如我把解題導航先打開。","这题我现在没有现成答案，但搜索路线我有，不如我把解题导航先打开。"],
"I don't have enough confidence to give a direct answer right now. I can explain how I'd investigate it, starting with A and B.",
"I'd rather not invent something that merely looks like an answer. I can explain how I'd find the answer.",
"I don't have the destination yet, but I do have the navigation route. Let me walk you through it.",
"呢題我而家冇足夠把握直接答。如果要我處理，我會先由 A、B 兩個方向確認，再驗證 XX。",
"我唔想現場作一個睇落似答案嘅答案。我可以講下我會點樣搵答案。",
"呢題我而家冇現成答案，但搵答案條路我有，不如先開導航。");

add("b03","business",
{hant:"合作方",hans:"合作方",en:"Partner company"},{hant:"拒絕壓價",hans:"拒绝压价",en:"Push back on price"},
{hant:"合作方要求大幅降價但不減工作量",hans:"合作方要求大幅降价但不减工作量",en:"A partner asks for a large discount without reducing scope"},
["目前報價是按現有範圍和交付要求計算。如果預算需要下降，我們可以一起調整範圍或交付方式。","目前报价是按现有范围和交付要求计算。如果预算需要下降，我们可以一起调整范围或交付方式。"],
["價格可以討論，但工作量和價格不能只有其中一個參加談判。","价格可以讨论，但工作量和价格不能只有其中一个参加谈判。"],
["預算想減肥可以，但 scope 也要一起參加健身計畫。","预算想减肥可以，但 scope 也要一起参加健身计划。"],
"The current price reflects the current scope and delivery requirements. If the budget needs to come down, we can adjust scope or delivery together.",
"Price can be negotiated, but workload and price both need to attend the negotiation.",
"If the budget wants to go on a diet, the scope needs to join the fitness plan too.",
"而家報價係按現有 scope 同交付要求計。如果 budget 要落，可以一齊調整範圍或者交付方式。",
"價錢可以傾，但工作量同價錢唔可以得一個參加談判。",
"Budget 想減肥可以，不過 scope 都要一齊參加健身計劃。");

add("tr03","travel",
{hant:"航空公司",hans:"航空公司",en:"Airline staff"},{hant:"航班延誤",hans:"航班延误",en:"Flight delay"},
{hant:"航班大幅延誤但現場沒有清楚說明",hans:"航班大幅延误但现场没有清楚说明",en:"Your flight is heavily delayed with little explanation"},
["您好，航班目前已延誤 X 小時。麻煩確認最新預計起飛時間，以及目前可提供的改簽或協助方案。","您好，航班目前已延误 X 小时。麻烦确认最新预计起飞时间，以及目前可提供的改签或协助方案。"],
["我理解延誤可能不可避免，但資訊不應該一起延誤。想要一個明確更新。","我理解延误可能不可避免，但信息不应该一起延误。想要一个明确更新。"],
["飛機晚到可以理解，消息最好不要也搭同一班飛機。","飞机晚到可以理解，消息最好不要也搭同一班飞机。"],
"The flight is now delayed by X hours. Could you confirm the latest expected departure time and available rebooking or assistance options?",
"I understand delays happen, but the information doesn't need to be delayed too. I'd like a clear update.",
"I can understand the aircraft arriving late. The information doesn't need to be on the same delayed flight.",
"你好，航班而家已經 delay X 個鐘。麻煩確認最新預計起飛時間，同而家有咩改簽或者協助方案。",
"我明白 delay 可能避免唔到，但資訊唔使一齊 delay。想要一個清楚 update。",
"飛機遲到可以理解，消息最好唔好都搭同一班 delay 航班。");

add("m01","medical",
{hant:"醫生",hans:"医生",en:"Doctor"},{hant:"問清楚治療方案",hans:"问清楚治疗方案",en:"Clarify treatment"},
{hant:"醫生講得很快，你沒有完全聽懂",hans:"医生讲得很快，你没有完全听懂",en:"The doctor explained quickly and you didn't fully understand"},
["不好意思，我想確認一下我理解得對不對：目前主要問題是 A，先做 B，如果 C 出現就需要再回來，是這樣嗎？","不好意思，我想确认一下我理解得对不对：目前主要问题是 A，先做 B，如果 C 出现就需要再回来，是这样吗？"],
["我怕回家之後只記得『醫生說過』，但忘了醫生到底說什麼，能不能再幫我整理一次重點？","我怕回家之后只记得“医生说过”，但忘了医生到底说什么，能不能再帮我整理一次重点？"],
["我的腦袋剛才沒有跟上醫療倍速播放，可以麻煩切回 1× 再講一次重點嗎？","我的脑袋刚才没有跟上医疗倍速播放，可以麻烦切回 1× 再讲一次重点吗？"],
"Sorry, I'd like to check my understanding: the main issue is A, I should do B first, and return if C happens. Is that correct?",
"I'm worried I'll go home remembering only that 'the doctor said something'. Could you summarise the key points once more?",
"My brain didn't quite keep up with the medical playback speed. Could we switch back to 1x for the key points?",
"唔好意思，我想確認下自己理解啱唔啱：主要問題係 A，先做 B，如果有 C 就再返嚟，係咪咁？",
"我驚返屋企之後淨係記得『醫生講過』，但唔記得講過乜。可唔可以再幫我總結一次重點？",
"我個腦頭先跟唔上醫療倍速播放，可唔可以切返 1× 再講次重點？");

add("m02","medical",
{hant:"家人",hans:"家人",en:"Family member"},{hant:"勸去看醫生",hans:"劝去看医生",en:"Encourage medical care"},
{hant:"家人症狀持續但一直不肯就醫",hans:"家人症状持续但一直不肯就医",en:"A family member has persistent symptoms but refuses to see a doctor"},
["我不是說一定有問題，只是這個症狀已經持續 X 天。去檢查一次是為了排除需要處理的情況，我可以陪你去。","我不是说一定有问题，只是这个症状已经持续 X 天。去检查一次是为了排除需要处理的情况，我可以陪你去。"],
["最好的結果就是醫生說沒事，這也比我們在家靠猜測當檢查設備可靠。","最好的结果就是医生说没事，这也比我们在家靠猜测当检查设备可靠。"],
["人體的『再等等』功能很常用，但醫院的檢查設備通常還是比較專業。","人体的“再等等”功能很常用，但医院的检查设备通常还是比较专业。"],
"I'm not saying something is definitely wrong, but the symptom has lasted X days. A check-up helps rule things out, and I can go with you.",
"The best result is the doctor saying it's nothing. That's still more reliable than using guessing as our diagnostic equipment.",
"The human 'wait and see' function is popular, but hospital equipment is usually a bit more professional.",
"我唔係話一定有問題，只係個症狀已經持續 X 日。去檢查係為咗排除要處理嘅情況，我可以陪你去。",
"最好結果就係醫生話冇事，都比我哋喺屋企靠估做檢查設備可靠。",
"人體個『再等等』功能好常用，不過醫院啲檢查設備通常專業啲。");

add("on01","online",
{hant:"群聊",hans:"群聊",en:"Group chat"},{hant:"拒絕無效爭論",hans:"拒绝无效争论",en:"Exit an unproductive argument"},
{hant:"群聊裡有人反覆和你抬槓",hans:"群聊里有人反复和你抬杠",en:"Someone keeps arguing with you in a group chat"},
["我們看法不一樣很正常，我的觀點已經說清楚了，這裡我就不再反覆展開了。","我们看法不一样很正常，我的观点已经说清楚了，这里我就不再反复展开了。"],
["我的觀點不會因為同一句話重複十次就自動升級，所以先到這裡。","我的观点不会因为同一句话重复十次就自动升级，所以先到这里。"],
["這個副本已經刷了好幾輪，經驗值沒有增加，我先退出。","这个副本已经刷了好几轮，经验值没有增加，我先退出。"],
"It's fine that we disagree. I've explained my view, so I'm not going to keep repeating the same argument here.",
"My position isn't going to level up because the same point is repeated ten times, so I'll leave it there.",
"We've replayed this level several times and gained no XP. I'm exiting.",
"大家睇法唔同好正常，我觀點已經講清楚，呢度唔再重複展開。",
"我個觀點唔會因為同一句講十次就自動升級，所以到呢度先。",
"呢個副本已經刷咗幾輪，經驗值冇加，我退出先。");

add("on02","online",
{hant:"私訊",hans:"私信",en:"Direct message"},{hant:"拒絕陌生推銷",hans:"拒绝陌生推销",en:"Decline unsolicited sales"},
{hant:"陌生人不停私訊推銷產品",hans:"陌生人不停私信推销产品",en:"A stranger keeps sending sales messages"},
["謝謝，不過我目前沒有相關需求，之後也不用再跟進了。","谢谢，不过我目前没有相关需求，之后也不用再跟进了。"],
["我沒有需求，這條銷售線索可以放心關閉。","我没有需求，这条销售线索可以放心关闭。"],
["恭喜你完成了推銷流程，我這邊的購買流程沒有啟動。","恭喜你完成了推销流程，我这边的购买流程没有启动。"],
"Thanks, but I don't have a need for this and you don't need to follow up further.",
"I don't have a need for this. You can safely close this lead.",
"Congratulations on completing the sales flow. My purchase flow has not started.",
"多謝，不過我而家冇需要，之後都唔使再 follow up。",
"我冇需求，呢條 sales lead 可以放心 close。",
"恭喜你完成推銷流程，我呢邊嘅購買流程冇啟動。");

add("on03","online",
{hant:"朋友圈",hans:"朋友圈",en:"Social media"},{hant:"回應陰陽評論",hans:"回应阴阳评论",en:"Respond to a snide comment"},
{hant:"有人在你的動態下面陰陽怪氣",hans:"有人在你的动态下面阴阳怪气",en:"Someone leaves a snide comment under your post"},
["如果你有具體不同意的地方，可以直接說，我比較容易回應具體內容。","如果你有具体不同意的地方，可以直接说，我比较容易回应具体内容。"],
["話裡有話比較累，有話不如直接說。","话里有话比较累，有话不如直接说。"],
["評論區不用玩密室逃脫，有意思可以直接放在明面上。","评论区不用玩密室逃脱，有意思可以直接放在明面上。"],
"If there's something specific you disagree with, feel free to say it directly. It's easier to respond to something concrete.",
"Reading between the lines is tiring. If there's a point, it's easier to say it directly.",
"The comment section doesn't need to be an escape room. The meaning can stay out in the open.",
"如果你有具體唔同意，可以直接講，我比較容易回應實際內容。",
"說話有話幾攰，有嘢不如直接講。",
"留言區唔使玩密室逃脫，有意思可以直接擺明面。");

window.CHAT_SCENARIOS=(window.CHAT_SCENARIOS||[]).concat(A);
})();