// Individually authored situation titles and reply stems in four spoken forms.
;(function(){
const domains={workplace:['職場','职场','Work'],study:['學習','学习','Study'],family:['家庭','家庭','Family'],parenting:['育兒','育儿','Parenting'],elder:['長輩','长辈','Elders'],friends:['朋友','朋友','Friends'],relationship:['感情','感情','Relationship'],social:['社交','社交','Social'],service:['服務','服务','Service'],job:['求職','求职','Job Search'],business:['商務','商务','Business'],travel:['旅行','旅行','Travel'],medical:['醫療','医疗','Medical'],online:['網絡','网络','Online']};
const relations={colleague:['同事','同事','Colleague'],manager:['上司','上司','Manager'],teacher:['老師','老师','Teacher'],classmate:['同學','同学','Classmate'],relative:['家人','家人','Family member'],parent:['父母','父母','Parent'],child:['孩子','孩子','Child'],elder:['長輩','长辈','Elder'],friend:['朋友','朋友','Friend'],partner:['伴侶','伴侣','Partner'],stranger:['陌生人','陌生人','Stranger'],neighbor:['鄰居','邻居','Neighbor'],staff:['服務人員','服务人员','Service staff'],recruiter:['招聘方','招聘方','Recruiter'],client:['客戶','客户','Client'],vendor:['供應商','供应商','Supplier'],companion:['同行者','同行者','Travel companion'],clinician:['醫護人員','医护人员','Clinician'],user:['網友','网友','Online user']};
function split(s,n){const a=s.split('|');if(a.length!==n||a.some(x=>!x.trim()))throw Error('Incomplete wave7 translation: '+s);return a}
function tri(s){const a=split(s,3);return {hant:a[0],hans:a[1],en:a[2]}}
const rows=[
// domain, relation, goal, title, measured, short, direct, light (Traditional | Simplified | English | Cantonese)
['workplace','colleague','確認交接|确认交接|Confirm handover','交接文件只有標題沒有實際內容|交接文件只有标题没有实际内容|A handover document has headings but no actual instructions','我看了交接文件，還缺操作步驟和目前進度。請在交接前補上，方便我接手。|我看了交接文件，还缺操作步骤和当前进度。请在交接前补上，方便我接手。|I’ve read the handover. Please add the steps and current status before I take over.|我睇咗份交接，仲差操作步驟同而家進度。交接前麻煩補返，等我接到手。','目前只有標題，內容呢？|现在只有标题，内容呢？|I see the headings. Where are the details?|依家得標題，內容呢？','沒有操作資料，我不能確認交接完成。|没有操作资料，我不能确认交接完成。|I can’t sign off on the handover without working instructions.|冇操作資料，我確認唔到交接完成。','這份交接目前像目錄，正文麻煩也發我。|这份交接目前像目录，正文麻烦也发我。|This reads like a table of contents; could you send the chapters too?|呢份交接暫時似目錄，正文都麻煩發俾我。'],
['workplace','manager','釐清會議任務|厘清会议任务|Clarify an action item','會議上突然被指派一項你沒聽清楚的任務|会上突然被指派一项你没听清楚的任务|You are assigned a task in a meeting but miss its details','我確認一下剛才分給我的項目：成果要交什麼、由誰提供資料、何時完成？|我确认一下刚才分给我的项目：要交什么成果、谁提供资料、何时完成？|Can I confirm my action item: the deliverable, source of information and deadline?|我想對返頭先分俾我嗰項：交咩成果、邊個俾資料、幾時完成？','我這項交付是什麼？|我这项要交什么？|What exactly am I delivering?|我呢項要交乜？','請把任務範圍和截止時間再說一次。|请把任务范围和截止时间再说一次。|Please repeat the scope and deadline.|麻煩再講一次範圍同限期。','我記下自己被點名了，細節也想一起記下來。|我记下自己被点名了，细节也想一起记下来。|I caught my name; I’d like to catch the assignment too.|我聽到自己個名，細節都想一齊聽清楚。'],
['study','teacher','要求補充講解|要求补充讲解|Ask for another explanation','老師講完公式後全班仍不知道如何套用|老师讲完公式后全班仍不知道怎么套用|The class knows a formula but not how to use it','我們記下公式了，但還不清楚何時套用。能否用一道完整例題示範選擇步驟？|我们记下公式了，但还不清楚什么时候套用。能否用一道完整例题示范选择步骤？|We have the formula, but not when to apply it. Could you walk through one full example?|我哋抄咗條公式，但仲唔知幾時用。可唔可以用一題完整例子示範？','可以示範一題嗎？|可以示范一题吗？|Could you show one example?|可唔可以示範一題？','請講一下如何判斷這題要用哪個公式。|请讲一下怎么判断这题该用哪个公式。|Please explain how to choose the formula for this problem.|麻煩講下點樣判斷呢題用邊條公式。','公式已到手，使用說明還在路上。|公式已经到手，使用说明还在路上。|We’ve got the formula; now we need its user manual.|條公式到手喇，仲差份使用說明。'],
['study','classmate','守住筆記界線|守住笔记界线|Set a note-sharing limit','同學每次不來上課都要你拍整本筆記|同学每次不来上课都让你拍整本笔记|A classmate repeatedly asks you to photograph all your notes','這次我能告訴你課堂重點，但整本筆記不方便每週拍給你；請也向老師取課件。|这次我能告诉你课堂重点，但整本笔记不方便每周拍给你；也请向老师要课件。|I can share the key points this time, but I can’t photograph all my notes each week. Ask for the class materials too.|今次我可以講重點，但唔方便每星期影成簿筆記俾你；你都可以向老師攞課件。','整本筆記我不拍了。|整本笔记我不拍了。|I can’t photograph the whole notebook again.|成簿筆記我唔影喇。','你需要自己補課，我不能一直代整理。|你得自己补课，我不能一直替你整理。|You’ll need to catch up yourself; I can’t keep compiling it for you.|你要自己補返堂，我唔可以一直代你整理。','我本筆記快變成你的遠距課程了。|我这本笔记快成你的远程课程了。|My notebook is becoming your remote course.|我本筆記就快變咗你個網上課程。'],
['family','relative','協調節日安排|协调节日安排|Coordinate a holiday visit','兩邊家人都要求你們在節日當天到場|两边家人都要求你们节日当天到场|Both sides of the family insist on a same-day holiday visit','我們想見兩邊家人，但一天跑兩場會太趕。今年一邊當天、一邊隔天，明年對調。|我们想见两边家人，但一天跑两场太赶。今年一边当天、一边次日，明年对调。|We want to see both families. We’ll visit one on the day and the other the next day, then swap next year.|我哋想見兩邊屋企人，但一日跑兩場太趕。今年一邊正日，一邊第二日，出年掉轉。','當天只能去一邊，另一邊隔天。|当天只能去一边，另一边第二天。|We can visit one family that day and the other the next.|正日只去到一邊，另一邊第二日。','請不要替我們答應兩邊同一天的飯局。|请不要替我们答应两边同一天的饭局。|Please don’t commit us to two dinners on the same day.|請唔好幫我哋應承同一日去兩邊食飯。','我們沒有分身術，今年用日曆來解決。|我们没有分身术，今年用日历解决。|We can’t clone ourselves, so let’s use a calendar.|我哋冇分身術，今年用日曆搞掂。'],
['family','parent','保留職涯決定|保留职业决定|Keep a career decision yours','家人未問你就替你答應一份熟人介紹的工作|家人没问你就替你答应了一份熟人介绍的工作|A parent accepts a job referral on your behalf','謝謝你想到我，但應徵與否需要由我決定。請先給我職位資料，不要替我承諾。|谢谢你想到我，但应聘与否需要由我决定。请先给我职位信息，别替我承诺。|Thanks for thinking of me. Let me review the role and decide whether to apply; please don’t commit for me.|多謝你諗到我，不過應唔應徵要由我決定。請先俾職位資料我，唔好代我應承。','工作我自己選，先給我資料。|工作我自己选，先给我资料。|I’ll choose my own job. Send me the details first.|份工我自己揀，先俾資料我。','請先問過我，再替我回覆對方。|请先问过我，再替我回复对方。|Ask me before answering on my behalf.|請先問過我，先好代我覆人。','介紹可以收，錄用決定還沒到代簽的環節。|介绍可以收，但还没到代我签字的环节。|I’ll take the introduction, but not a decision made for me.|介紹可以收，但未到代我簽名嗰一步。'],
['parenting','child','處理推撞|处理推搡|Respond to pushing','孩子生氣時推了另一個孩子|孩子生气时推了另一个孩子|Your child pushes another child in anger','先停下，讓我們看看對方有沒有受傷。生氣可以說出來，但不能推人；等你冷靜，我們一起想下一步。|先停下，看看对方有没有受伤。生气可以说出来，但不能推人；等你冷静，我们一起想下一步。|Stop. Let’s check whether they’re hurt. It’s okay to be angry, but not to push. We’ll work out what to do once you’re calmer.|停一停，睇下對方有冇受傷。嬲可以講，但唔可以推人。你冷靜啲我哋再諗下一步。','停手，先看他有沒有受傷。|停手，先看他有没有受伤。|Stop. Let’s check they’re okay.|停手，先睇佢有冇受傷。','你可以生氣，但不能推人。現在先分開。|你可以生气，但不能推人。现在先分开。|You can feel angry, but you can’t push. Let’s step apart now.|你可以嬲，但唔可以推人。依家先分開。','手先休息，嘴巴說出你想要什麼。|手先休息，用嘴巴说出你想要什么。|Hands take a break; words can tell me what you need.|對手休息先，用把口講你想點。'],
['parenting','child','安排睡前協議|安排睡前约定|Agree on bedtime','孩子每晚說還要再聽一個故事而拖延睡覺|孩子每晚说还要再听一个故事而拖延睡觉|Your child asks for one more story every night to delay bed','今晚讀完這一本就關燈。明天你可以提前選兩本，我們在睡前讀。|今晚读完这一本就关灯。明天你可以提前选两本，我们睡前读。|We’ll finish this book and turn off the light. Tomorrow you can choose two books ahead of bedtime.|今晚讀完呢本就熄燈。聽日你可以早啲揀兩本，我哋瞓前讀。','這本讀完就睡。|这本读完就睡。|This book, then sleep.|呢本讀完就瞓。','今晚的故事到這裡，明天再讀新的。|今晚的故事到这里，明天再读新的。|That’s tonight’s story. We’ll read a new one tomorrow.|今晚故事到呢度，聽日再讀新嘅。','故事有續集，今晚的眼皮也要下班了。|故事有续集，今晚的眼皮也该下班了。|The story has a sequel, and our eyelids need a break.|故事有續集，今晚對眼都要收工喇。'],
['elder','elder','慢慢教手機|慢慢教手机|Teach a phone feature','長輩反覆問你同一個手機功能怎麼用|长辈反复问你同一个手机功能怎么用|An elder asks how to use the same phone feature again','我們再做一次，我先示範，然後你按一遍；我把步驟寫大一點放在旁邊。|我们再做一次，我先示范，然后你按一遍；我把步骤写大一点放在旁边。|Let’s try once more. I’ll show you, then you can do it; I’ll write the steps in large print.|我哋再做一次，我先示範，跟住你按一次；我寫大隻字步驟擺旁邊。','來，我們再按一次。|来，我们再按一次。|Come on, let’s do it once more.|嚟，我哋再按一次。','先按這裡，再按藍色按鈕。你試一次。|先按这里，再按蓝色按钮。你试一次。|Tap here, then the blue button. Your turn.|先撳呢度，再撳藍色掣。你試一次。','手機功能藏得深，我們做張自己的小地圖。|手机功能藏得深，咱们做张自己的小地图。|That button likes to hide. Let’s make our own little map.|呢個功能匿得深，我哋整張自己嘅小地圖。'],
['elder','elder','婉拒轉發圖片|婉拒转发图片|Decline forwarded images','長輩每天轉很多問候圖片，希望你逐張回覆|长辈每天转很多问候图片，希望你一张张回复|An elder sends many greeting images and expects a reply to each','我知道你想問候我，我都收到了。工作時未必能逐張回，但晚上有空會給你發訊息。|我知道你想问候我，我都收到了。工作时未必能逐张回，但晚上有空会给你发消息。|I know you’re thinking of me. I see the pictures, but can’t answer each one at work; I’ll message in the evening.|我知你想問候我，啲相我收到喇。返工未必逐張覆到，夜晚得閒我會發訊息。','圖片收到啦，晚上再聊。|图片收到了，晚上再聊。|Got the pictures. Let’s chat tonight.|啲圖收到了，夜晚再傾。','上班時我不會逐張回圖，急事請直接打電話。|上班时我不会一张张回图，急事请直接打电话。|I can’t reply to every picture at work. Call if it’s urgent.|返工我唔會逐張圖覆，急事直接打電話。','今日的早安圖我收齊了，晚上換我發一句真的晚安。|今天的早安图我收齐了，晚上换我发一句真的晚安。|I’ve got the good morning pictures; I’ll send a real good night later.|今日早晨圖我收齊喇，夜晚換我講句真嘅晚安。'],
['friends','friend','拒絕當中間人|拒绝当中间人|Stay out of a dispute','兩個朋友吵架，都要你替自己傳話|两个朋友吵架，都要你替自己传话|Two friends in conflict both ask you to relay messages','我在乎你們兩個，但不適合替任何一方傳話。你想說的話請直接告訴對方。|我在乎你们两个，但不适合替任何一方传话。你想说的话请直接告诉对方。|I care about both of you, but I won’t relay messages. Please say it to each other directly.|我關心你哋兩個，但唔適合幫任何一邊傳話。你想講嘅，請直接同對方講。','這句請你自己跟他說。|这句话请你自己跟他说。|Please tell them yourself.|呢句請你自己同佢講。','我不會繼續當你們的傳聲筒。|我不会继续当你们的传声筒。|I won’t keep acting as the messenger between you.|我唔會繼續做你哋嘅傳聲筒。','我的聊天框不適合當雙方的轉運站。|我的聊天框不适合做双方的中转站。|My inbox isn’t a transfer station for this argument.|我個 chat 唔適合做你哋嘅轉運站。'],
['friends','friend','確認分帳|确认分账|Split a group bill','聚餐有人總說下次再轉錢但一直沒轉|聚餐有人总说下次转钱却一直没转|A friend repeatedly promises to pay their share later','上次聚餐你那份我先付了，金額是 XX。請今天轉給我，之後我們當場分帳。|上次聚餐你那份我先付了，金额是 XX。请今天转给我，以后我们当场分账。|I covered your XX share last time. Please send it today; we can split bills on the spot from now on.|上次食飯你嗰份我先俾咗，係 XX。今日麻煩轉返俾我，下次即場分帳。','上次那筆 XX 何時轉？|上次那笔 XX 什么时候转？|When will you send the XX from last time?|上次嗰筆 XX 幾時轉？','請今天還清上次的餐費，下次不要再記帳。|请今天结清上次的餐费，下次别再记账了。|Please settle the last meal today. Next time, let’s pay on the spot.|請今日清返上次餐費，下次唔好再記住先。','「下次轉」已經吃了好幾頓飯，先讓它到帳吧。|“下次转”已经吃了好几顿饭，先让它到账吧。|“Next time” has had a few dinners already. Let’s settle up.|『下次轉』都食咗幾餐飯，等佢到帳先啦。'],
['relationship','partner','討論回覆頻率|讨论回复频率|Discuss response time','伴侶因你在上班時沒有秒回而生氣|伴侣因为你上班时没有秒回而生气|Your partner gets upset when you cannot reply instantly at work','我在上班時不能一直看手機，但看到訊息會回。急事可以打電話，我們一起約個彼此舒服的方式。|我上班时不能一直看手机，但看到消息会回。急事可以打电话，我们一起约个都舒服的方式。|I can’t check my phone constantly at work, but I’ll reply when I can. Call for urgent things; let’s agree on what works for us.|我返工唔可以成日睇手機，但見到會覆。急事可以打電話，我哋傾個大家舒服嘅方法。','我在工作，忙完會回。|我在工作，忙完会回。|I’m working. I’ll reply when I’m free.|我返緊工，忙完會覆。','工作時我不能秒回，請不要因此指責我。|工作时我没法秒回，请别因此责怪我。|I can’t reply instantly at work. Please don’t blame me for that.|返工我冇辦法秒覆，請唔好因此怪我。','我不是已讀機器人，下班後好好聊。|我不是已读机器人，下班后好好聊。|I’m not an instant-reply bot. Let’s talk properly after work.|我唔係秒覆機械人，放工後好好傾。'],
['relationship','partner','提出分擔情緒|提出分担情绪|Ask for shared emotional effort','你每次提出感受，對方都只說你想太多|你每次说出感受，对方都只说你想太多|Your partner dismisses your feelings as overthinking','我希望你先聽完具體讓我難過的事，再告訴我你的看法。「想太多」會讓我們談不下去。|我希望你先听完具体让我难过的事，再告诉我你的看法。“想太多”会让我们没法继续谈。|Please hear what actually upset me before responding. Calling it overthinking ends the conversation.|我想你先聽完邊件事令我難過，再講你點睇。話我諗太多，我哋就傾唔落去。','先聽我說完，好嗎？|先听我说完，好吗？|Can you hear me out first?|先聽我講完，好嗎？','請不要再用「想太多」打發我的感受。|请别再用“想太多”打发我的感受。|Please stop dismissing my feelings as overthinking.|請唔好再用『諗太多』打發我嘅感受。','我的感受不需要先過「想太多」那一關。|我的感受不需要先过“想太多”这一关。|My feelings shouldn’t have to pass an overthinking test.|我啲感受唔使先過『諗太多』嗰關。'],
['social','stranger','拒絕拍照|拒绝拍照|Decline a photo','聚會上剛認識的人一直要跟你合照並上傳|聚会上刚认识的人一直要和你合照上传|A new acquaintance insists on posting a photo of you together','我今天不想被拍或上傳，謝謝理解。你們可以拍，我先走開一下。|我今天不想被拍或上传，谢谢理解。你们可以拍，我先走开一下。|I don’t want to be photographed or posted today. Go ahead without me; I’ll step aside.|我今日唔想俾人影或者上載，多謝理解。你哋影啦，我行開一陣。','我不入鏡，謝謝。|我不入镜，谢谢。|No photo of me, thanks.|我唔入鏡，多謝。','請不要拍我，也不要上傳我的照片。|请不要拍我，也不要上传我的照片。|Please don’t photograph or post me.|請唔好影我，亦唔好上載我張相。','今天我的相機角色是攝影師，不是模特。|今天我的相机角色是摄影师，不是模特。|I’ll be behind the camera today, not in front of it.|今日我做攝影師，唔做模特。'],
['social','neighbor','要求移車|要求挪车|Ask to move a vehicle','鄰居的車擋住了你家車庫出口|邻居的车挡住了你家车库出口|A neighbor’s car blocks your garage exit','你好，你的車擋住我家車庫出口了，我需要現在開車出去。麻煩立刻移一下。|你好，你的车挡住我家车库出口了，我现在需要开车出去。麻烦马上挪一下。|Hi, your car is blocking my garage and I need to leave now. Could you move it immediately?|你好，你架車擋住我屋企車庫出口，我依家要開車出去，麻煩即刻移一移。','麻煩移車，我出不去。|麻烦挪车，我出不去。|Please move your car; I can’t get out.|麻煩移車，我出唔到去。','請現在移開車輛，別再堵住出口。|请现在把车挪开，别再堵住出口。|Move your car now, and please keep the exit clear.|請依家移開架車，唔好再塞住出口。','我的車庫今天不想變停車場，麻煩讓個出口。|我的车库今天不想变停车场，麻烦让出出口。|My garage didn’t sign up to be a car park. Please clear the exit.|我個車庫今日唔想變停車場，麻煩讓返個出口。'],
['service','staff','要求書面憑證|要求书面凭证|Request written confirmation','客服口頭說已退款但帳戶一直沒收到|客服口头说已退款但账户一直没收到|Support says a refund was issued but it has not appeared','我還沒收到退款。請提供退款日期、金額及交易編號，並以訊息確認。|我还没收到退款。请提供退款日期、金额和交易编号，并通过消息确认。|The refund hasn’t arrived. Please send the date, amount and transaction reference in writing.|我仲未收到退款。麻煩俾退款日期、金額同交易編號，並用訊息確認。','退款編號可以發我嗎？|退款编号能发我吗？|Can you send the refund reference?|退款編號可唔可以發俾我？','目前沒有到帳，請提供可查詢的退款憑證。|目前没有到账，请提供可以查询的退款凭证。|It hasn’t arrived. Please provide a traceable refund confirmation.|依家未到帳，請提供查到嘅退款憑證。','口頭退款還在空中，給我一個能追蹤的編號吧。|口头退款还在空中，给我一个能追踪的编号吧。|The spoken refund is still airborne. Please send a tracking reference.|口頭退款仲喺半空，麻煩俾個查到嘅編號。'],
['service','staff','要求重開發票|要求重开发票|Correct an invoice','商家開的發票抬頭與你提供的資料不同|商家开的发票抬头和你提供的信息不同|A business issues an invoice with the wrong name','我提供的抬頭是 A，這張發票寫成 B。請更正後重新開立，並告知預計時間。|我提供的抬头是 A，这张发票写成 B。请更正后重新开具，并告知预计时间。|I provided A, but the invoice says B. Please correct and reissue it, and tell me when to expect it.|我俾嘅抬頭係 A，張單寫咗 B。麻煩改返重開，同我講幾時有。','抬頭錯了，請重開。|抬头错了，请重开。|The invoice name is wrong. Please reissue it.|抬頭錯咗，麻煩重開。','請按我提供的資料重開發票。|请按我提供的信息重开发票。|Please reissue the invoice with the details I supplied.|請跟返我俾嘅資料重開發票。','A 和 B 差了一個字母，報銷卻差了整張單。|A 和 B 差了一个字母，报销却差了整张单。|A and B look close, but accounting won’t think so.|A 同 B 差個字母，報銷就差成張單。'],
['job','recruiter','確認工作地點|确认工作地点|Clarify the work location','面試邀請只寫「到公司」卻沒有具體地址|面试邀请只写“到公司”却没有具体地址|An interview invite says to come to the office but gives no address','謝謝邀請。請問面試的完整地址、樓層和抵達後的聯絡方式？|谢谢邀请。请问面试的完整地址、楼层和到达后的联系方式？|Thanks for the invitation. Could you send the full address, floor and arrival contact?|多謝邀請。想問面試完整地址、樓層，同到咗之後搵邊位？','面試地址可以發我嗎？|面试地址能发我吗？|Could you send the interview address?|面試地址可唔可以發俾我？','請提供具體地址和到場指引。|请提供具体地址和到场指引。|Please provide the full address and arrival instructions.|請提供詳細地址同到場指引。','我很樂意準時到，前提是先找到門。|我很愿意准时到，前提是先找到门。|Happy to be on time once I know which door to find.|我好樂意準時到，前提係知道道門喺邊。'],
['job','recruiter','拒絕臨時改面試|拒绝临时改面试|Reschedule an interview','招聘方提前十分鐘把線上面試改成到場|招聘方提前十分钟把线上面试改成现场面试|A recruiter changes a video interview to in-person ten minutes before it starts','我按原通知準備了線上面試，現在無法在十分鐘內到場。可以按原方式進行，或另約現場時間。|我按原通知准备了线上面试，现在无法在十分钟内到场。可以按原方式进行，或另约现场时间。|I prepared for the video interview and can’t arrive in ten minutes. We can keep the video call or reschedule on-site.|我按原通知準備咗線上面試，十分鐘內到唔到現場。可以照原本視像進行，或者再約現場時間。','十分鐘內到不了現場，請保留線上安排。|十分钟内到不了现场，请保留线上安排。|I can’t get there in ten minutes. Please keep the video call.|十分鐘內到唔到現場，請照原本線上安排。','臨時改現場我無法配合，請重新約時間。|临时改成现场我无法配合，请重新约时间。|I can’t accommodate that last-minute change. Please reschedule.|臨時改現場我配合唔到，請重新約時間。','視像會議能瞬間改地點，我本人不能瞬間傳送。|视频会议能瞬间改地点，我本人不能瞬间传送。|A meeting link can move instantly; I can’t teleport.|視像會議可以即刻改地點，我本人唔識瞬間轉移。'],
['business','client','確認驗收標準|确认验收标准|Agree on acceptance criteria','客戶要求開始製作卻一直不確認驗收標準|客户要求开工却一直不确认验收标准|A client wants production started without approving acceptance criteria','開始前請確認交付格式、範圍及驗收方式。收到書面確認後，我會按此安排製作。|开始前请确认交付格式、范围和验收方式。收到书面确认后，我会按此安排制作。|Before production, please confirm the format, scope and acceptance criteria in writing.|開工前麻煩確認交付格式、範圍同驗收方法。收到書面確認，我就安排製作。','先定驗收標準，再開工。|先定验收标准，再开工。|Let’s agree on acceptance criteria first.|先定驗收標準，再開工。','沒有確認標準，我無法承諾交付時間。|没有确认标准，我无法承诺交付时间。|I can’t commit to a delivery date without agreed criteria.|標準未確認，我承諾唔到交期。','起跑線可以畫，終點線也先畫一下。|起跑线能画，终点线也先画一下。|We have a starting line; let’s mark the finish line too.|起點畫咗，終點都先畫一下。'],
['business','vendor','追交貨證明|催交货证明|Request proof of shipment','供應商說貨已寄出卻一直給不出追蹤號|供应商说货已寄出却一直给不出快递单号|A supplier says goods shipped but cannot provide tracking','請提供承運商、寄出日期和追蹤號。我們需要據此安排收貨。|请提供承运商、寄出日期和快递单号。我们需要据此安排收货。|Please send the carrier, dispatch date and tracking number so we can plan receipt.|請俾承運商、寄出日期同追蹤號，我哋要安排收貨。','追蹤號呢？|快递单号呢？|Where’s the tracking number?|追蹤號呢？','沒有寄件憑證，我們不能按已發貨安排。|没有寄件凭证，我们不能按已发货安排。|Without dispatch proof, we can’t treat this as shipped.|冇寄件憑證，我哋唔可以當已發貨咁安排。','貨說它出門了，麻煩給我看車票。|货说它出门了，麻烦给我看看车票。|If the goods have left, please show me their ticket.|啲貨話出咗門，麻煩俾張車飛我睇下。'],
['travel','staff','確認延誤接駁|确认延误接驳|Check a missed connection','列車延誤讓你可能趕不上已訂好的接駁車|列车延误让你可能赶不上预订的接驳车|A delayed train may make you miss a booked shuttle','我的列車延誤，可能趕不上原訂接駁車。請問能否改搭下一班，以及如何辦理？|我的列车延误，可能赶不上原订接驳车。请问能否改搭下一班，以及怎么办理？|My train is delayed and I may miss the booked shuttle. Can I take the next one, and how do I change it?|我班火車延誤，可能趕唔到原定接駁車。可唔可以改搭下一班，點辦手續？','接駁車能改下一班嗎？|接驳车能改下一班吗？|Can I switch to the next shuttle?|接駁車可唔可以改下一班？','請確認延誤後可用的改乘安排。|请确认延误后可以怎么改乘。|Please confirm my options for changing the connection.|麻煩確認延誤後點樣改搭。','火車慢了一步，我想請接駁車留個下一班的位置。|火车慢了一步，我想请接驳车留个下一班的位置。|The train is running late; could the next shuttle save me a seat?|火車慢咗一步，想請下一班接駁車留個位。'],
['travel','companion','分開安排飲食|分开安排饮食|Handle different food needs','同行朋友想吃的餐廳沒有你能吃的餐點|同行朋友想去的餐厅没有你能吃的餐点|Your companion chooses a restaurant with nothing you can eat','你們可以在這裡吃，我先去附近找合適的餐點，一小時後在門口會合。|你们可以在这里吃，我先去附近找合适的餐点，一小时后在门口会合。|You can eat here. I’ll find something suitable nearby and meet you outside in an hour.|你哋可以喺度食，我去附近搵啱食嘅，一個鐘後門口會合。','這裡沒有我能吃的，我去隔壁。|这里没有我能吃的，我去隔壁。|There’s nothing I can eat here. I’ll go next door.|呢度冇我食到嘅，我去隔離。','我需要選一間有合適餐點的店，晚點再會合。|我需要选一家有合适餐点的店，晚点再会合。|I need a place with food I can eat. Let’s meet afterwards.|我要搵間有嘢啱我食嘅店，遲啲再會合。','你們點你們的，我去給胃找個合適的隊友。|你们点你们的，我去给胃找个合适的队友。|Enjoy your meal; I’ll find my stomach a better teammate.|你哋照叫，我去幫個胃搵個合適隊友。'],
['medical','clinician','核對檢查目的|核对检查目的|Understand a test','醫生建議做檢查，你不清楚它要回答什麼問題|医生建议做检查，你不清楚它要回答什么问题|A clinician recommends a test but you do not know what it is for','我想明白這項檢查主要在排查什麼，以及結果會如何影響下一步安排。可以解釋一下嗎？|我想弄明白这项检查主要排查什么，以及结果会怎样影响下一步安排。能解释一下吗？|What is this test looking for, and how would the result affect the next step? Could you explain?|我想知呢項檢查主要查咩，同結果會點影響下一步。可唔可以解釋一下？','這項檢查是查什麼的？|这项检查是查什么的？|What is this test checking for?|呢項檢查係查乜嘅？','請說明檢查目的和結果如何使用。|请说明检查目的和结果会怎么使用。|Please explain the test’s purpose and what the result will change.|麻煩講清楚檢查目的，同結果會點用。','我想先弄懂這道題，再去做這項檢查。|我想先弄懂这道题，再去做这项检查。|I’d like to understand the question before taking the test.|我想先知問緊咩，再去做呢項檢查。'],
['medical','clinician','核對過敏紀錄|核对过敏记录|Check an allergy record','你的藥物過敏紀錄在新診所的資料裡沒有顯示|你的药物过敏记录在新诊所的资料里没显示|Your medication allergy is missing from a new clinic record','我對 XX 有過敏史，但這份紀錄沒有顯示。請先更新病歷，並確認目前用藥安排已考慮這點。|我对 XX 有过敏史，但这份记录没有显示。请先更新病历，并确认目前用药安排已考虑这一点。|I have a recorded allergy to XX, but it’s missing here. Please update my chart and check the treatment plan against it.|我對 XX 有過敏史，但份紀錄冇顯示。麻煩先更新病歷，再確認用藥安排有考慮到。','我對 XX 過敏，請補進病歷。|我对 XX 过敏，请补进病历。|I’m allergic to XX. Please add that to my chart.|我對 XX 過敏，請補返落病歷。','在記錄過敏資料前，請先不要完成處方。|在记录过敏信息前，请先不要完成处方。|Please update the allergy record before finalizing the prescription.|未記錄過敏資料之前，請先唔好完成處方。','這項資料不能靠我的記憶在每張單之間旅行。|这项信息不能只靠我在每张单之间重复提醒。|This shouldn’t have to travel between forms in my memory alone.|呢項資料唔可以淨係靠我每張單都再講一次。'],
['online','user','要求刪除截圖|要求删除截图|Request removal of a screenshot','朋友未問你就把你們的私人對話截圖發到群組|朋友没问你就把你们的私聊截图发到群里|A friend posts your private chat screenshot to a group without asking','那段對話是私下說的，我沒有同意公開。請先刪除截圖，以後發之前先問我。|那段对话是私下说的，我没有同意公开。请先删除截图，以后发之前先问我。|That was a private conversation and I didn’t agree to share it. Please delete the screenshot and ask before posting next time.|嗰段對話係私下講，我冇同意公開。請先刪咗張截圖，以後發之前先問我。','請把截圖刪掉。|请把截图删掉。|Please delete the screenshot.|請刪咗張截圖。','未經我同意不要公開我們的私訊，現在請刪除。|没经过我同意不要公开我们的私信，现在请删除。|Don’t post our private messages without my consent. Remove it now.|未經我同意唔好公開我哋私訊，依家請刪咗佢。','私訊不是群組公告，先撤回吧。|私信不是群公告，先撤回吧。|A private chat isn’t a group announcement. Please take it down.|私訊唔係群組公告，先撤回啦。'],
['online','user','停止標註|停止标记|Stop unwanted tagging','熟人反覆把你標註在無關的廣告貼文中|熟人反复在无关广告帖里标记你|An acquaintance repeatedly tags you in unrelated ads','我不想被標註在這些廣告裡。請移除現有標註，之後也不要再標我。|我不想被标记在这些广告里。请移除现在的标记，以后也别再标我。|I don’t want to be tagged in these ads. Please remove the current tags and stop adding me.|我唔想俾你 tag 喺啲廣告度。請移除依家啲 tag，之後都唔好再 tag 我。','別再標我了。|别再标记我了。|Please stop tagging me.|唔好再 tag 我。','請立即移除標註，往後不要把我放進廣告。|请马上移除标记，以后别把我放进广告里。|Remove the tags now and don’t include me in future ads.|請即刻移除標註，以後唔好將我放入廣告。','你的廣告客串名單可以少我一個。|你的广告客串名单可以少我一个。|Your ads can manage without my cameo.|你個廣告客串名單可以少我一個。'],
];
const additions=rows.map((r,i)=>{
 const [domain,relation,goal,title,...lines]=r;
 if(lines.length!==4)throw Error('Incomplete wave7 voices: '+title);
 const translations=lines.map(v=>split(v,4)),replies={zh:{},en:{},yue:{}};
 for(const [j,key] of ['formal','short','direct','humor'].entries()){
  const [hant,hans,en,yue]=translations[j];
  replies.zh[key]={hant,hans};replies.en[key]=en;replies.yue[key]=yue;
 }
 return {id:'wave7-'+String(i+1).padStart(3,'0'),domain,domainLabel:tri(domains[domain].join('|')),relation:tri(relations[relation].join('|')),goal:tri(goal),title:tri(title),replies};
});
window.CHAT_SCENARIOS=(window.CHAT_SCENARIOS||[]).concat(additions);
})();
