;(function(){
const D={
 workplace:{hant:"職場",hans:"职场",en:"Work"},
 study:{hant:"學習",hans:"学习",en:"Study"},
 family:{hant:"家庭",hans:"家庭",en:"Family"},
 parenting:{hant:"育兒",hans:"育儿",en:"Parenting"},
 elder:{hant:"長輩",hans:"长辈",en:"Elders"},
 friends:{hant:"朋友",hans:"朋友",en:"Friends"},
 relationship:{hant:"感情",hans:"感情",en:"Relationship"},
 social:{hant:"社交",hans:"社交",en:"Social"},
 service:{hant:"服務",hans:"服务",en:"Service"},
 job:{hant:"求職",hans:"求职",en:"Job Search"},
 business:{hant:"商務",hans:"商务",en:"Business"},
 travel:{hant:"旅行",hans:"旅行",en:"Travel"}
};
const A=[];
function add(id,domain,relation,goal,title,replies){A.push({id,domain,domainLabel:D[domain],relation,goal,title,replies})}

add("w06","workplace",{hant:"上司",hans:"上司",en:"Manager"},{hant:"彙報延誤",hans:"汇报延误",en:"Report a delay"},{hant:"你的工作可能無法按原時間完成",hans:"你的工作可能无法按原时间完成",en:"Your work may miss the original deadline"},
{zh:{formal:{hant:"目前 XX 的進度比預期慢，主要卡在 A。我預計需要延至 X 日完成，今天會先交付 B，並在明天下午再更新一次進度。",hans:"目前 XX 的进度比预期慢，主要卡在 A。我预计需要延至 X 日完成，今天会先交付 B，并在明天下午再更新一次进度。"},dark:{hant:"與其在 deadline 當天表演驚喜，不如現在先把延誤和原因講清楚。XX 目前卡在 A。",hans:"与其在 deadline 当天表演惊喜，不如现在先把延误和原因讲清楚。XX 目前卡在 A。"},roast:{hant:"XX 目前跟原計畫有一點時差，我先提早報備，免得 deadline 到時候親自介紹自己。",hans:"XX 目前跟原计划有一点时差，我先提早报备，免得 deadline 到时候亲自介绍自己。"}},en:{formal:"XX is running behind due to A. I now expect completion by X. I'll deliver B today and send another progress update tomorrow afternoon.",dark:"Rather than turn the deadline into a surprise event, I'm flagging the delay and cause now. XX is currently blocked by A.",roast:"XX and the original plan are experiencing a small time-zone difference, so I'm reporting it before the deadline introduces itself."},yue:{formal:"XX 而家進度比預期慢，主要卡喺 A。我預計要延到 X 日完成，今日會先交 B，聽日下午再 update 一次。",dark:"與其 deadline 嗰日先整驚喜，不如而家講清楚延誤同原因。XX 目前卡喺 A。",roast:"XX 而家同原計劃有少少時差，我提早報備，免得 deadline 到時親自介紹自己。"}});

add("w07","workplace",{hant:"同事",hans:"同事",en:"Colleague"},{hant:"防止甩鍋",hans:"防止甩锅",en:"Clarify ownership"},{hant:"同事把原本不是你的責任推給你",hans:"同事把原本不是你的责任推给你",en:"A colleague is shifting responsibility for something that wasn't yours"},
{zh:{formal:{hant:"我補充一下分工紀錄：A 由我負責，B 當時確認由 XX 跟進。為避免資訊混亂，我們按原分工繼續處理比較清楚。",hans:"我补充一下分工记录：A 由我负责，B 当时确认由 XX 跟进。为避免信息混乱，我们按原分工继续处理比较清楚。"},dark:{hant:"我可以協助解決，但不希望「協助」最後自動翻譯成「原本就是我負責」。",hans:"我可以协助解决，但不希望“协助”最后自动翻译成“原本就是我负责”。"},roast:{hant:"我可以幫忙滅火，但消防員不等於縱火者。先把原分工對回去。",hans:"我可以帮忙灭火，但消防员不等于纵火者。先把原分工对回去。"}},en:{formal:"Just to clarify the ownership record: I was responsible for A, while B was assigned to XX. It's clearer if we continue with the original split.",dark:"I'm happy to help resolve it, but I don't want 'helping' to be automatically translated into 'it was mine all along'.",roast:"I can help put out the fire, but the firefighter isn't automatically the arsonist. Let's check the original ownership."},yue:{formal:"補充返原本分工：A 係我負責，B 當時確認由 XX 跟。為免亂，我哋跟返原分工會清楚啲。",dark:"我可以幫手解決，但唔想『幫手』最後自動翻譯成『原本就係我負責』。",roast:"我可以幫手救火，但消防員唔等於放火嗰個。先對返原分工。"}});

add("w08","workplace",{hant:"上司",hans:"上司",en:"Manager"},{hant:"談加薪",hans:"谈加薪",en:"Discuss a raise"},{hant:"你想正式提出加薪",hans:"你想正式提出加薪",en:"You want to formally ask for a raise"},
{zh:{formal:{hant:"我想跟你討論一下薪酬調整。過去 X 個月我承擔了 A、B、C，並取得了 XX 的結果。我希望能基於目前職責和產出重新評估薪酬。",hans:"我想跟你讨论一下薪酬调整。过去 X 个月我承担了 A、B、C，并取得了 XX 的结果。我希望能基于目前职责和产出重新评估薪酬。"},dark:{hant:"我的職責和輸出已經升級了一段時間，我想確認薪酬是不是也準備一起升級。",hans:"我的职责和输出已经升级了一段时间，我想确认薪酬是不是也准备一起升级。"},roast:{hant:"工作內容已經成功解鎖進階版，我想聊聊薪酬是否也能解除新手模式。",hans:"工作内容已经成功解锁进阶版，我想聊聊薪酬是否也能解除新手模式。"}},en:{formal:"I'd like to discuss a salary adjustment. Over the past X months I've taken on A, B and C and delivered XX results. I'd like my compensation to be reviewed against my current scope and impact.",dark:"My responsibilities and output have been upgraded for a while. I'd like to check whether compensation is ready for the same upgrade.",roast:"The job has successfully unlocked advanced mode. I'd like to discuss whether the salary can leave beginner mode too."},yue:{formal:"我想同你傾下薪酬調整。過去 X 個月我負責咗 A、B、C，亦做到 XX 結果，希望可以按而家職責同產出重新評估。",dark:"我嘅職責同輸出升級咗一段時間，想確認薪酬係咪都準備一齊升級。",roast:"工作內容已經成功解鎖進階版，我想傾下人工可唔可以都解除新手模式。"}});

add("w09","workplace",{hant:"上司",hans:"上司",en:"Manager"},{hant:"提出離職",hans:"提出离职",en:"Resign"},{hant:"你準備正式提出離職",hans:"你准备正式提出离职",en:"You are ready to formally resign"},
{zh:{formal:{hant:"我想正式告知，我決定提出離職。這不是臨時決定，我會按公司流程完成通知期和交接，盡量把影響降到最低。",hans:"我想正式告知，我决定提出离职。这不是临时决定，我会按公司流程完成通知期和交接，尽量把影响降到最低。"},dark:{hant:"這個決定我已經考慮清楚，所以今天是通知，不是開啟新一輪勸留辯論。",hans:"这个决定我已经考虑清楚，所以今天是通知，不是开启新一轮劝留辩论。"},roast:{hant:"我準備從這個副本畢業了，接下來會把裝備和任務完整交接。",hans:"我准备从这个副本毕业了，接下来会把装备和任务完整交接。"}},en:{formal:"I'd like to formally let you know that I've decided to resign. This is a considered decision, and I'll complete the notice period and handover properly.",dark:"I've thought this through, so today's conversation is a notification rather than the opening round of a retention debate.",roast:"I'm ready to graduate from this level. I'll make sure the inventory and quests are handed over properly."},yue:{formal:"我想正式通知，我決定提出離職。呢個唔係臨時決定，我會跟公司流程做完通知期同交接。",dark:"呢個決定我已經諗清楚，所以今日係通知，唔係開新一輪勸留辯論。",roast:"我準備由呢個副本畢業，之後會完整交接裝備同任務。"}});

add("w10","workplace",{hant:"會議參與者",hans:"会议参与者",en:"Meeting participants"},{hant:"拉回主題",hans:"拉回主题",en:"Refocus a meeting"},{hant:"會議一直跑題，時間快用完",hans:"会议一直跑题，时间快用完",en:"The meeting keeps drifting off topic and time is running out"},
{zh:{formal:{hant:"我們先把今天需要決定的 A 收斂一下，其他延伸問題可以另外記下來。現在還剩 10 分鐘，我建議先確認結論和責任人。",hans:"我们先把今天需要决定的 A 收敛一下，其他延伸问题可以另外记下来。现在还剩 10 分钟，我建议先确认结论和责任人。"},dark:{hant:"這些都值得聊，但如果今天的目標是決定 A，我們可能要先把會議從漫遊模式切回導航。",hans:"这些都值得聊，但如果今天的目标是决定 A，我们可能要先把会议从漫游模式切回导航。"},roast:{hant:"我們已經從 A 聊到宇宙邊緣了，剩 10 分鐘先回地球把 A 定掉。",hans:"我们已经从 A 聊到宇宙边缘了，剩 10 分钟先回地球把 A 定掉。"}},en:{formal:"Let's bring this back to the decision we need on A. We have ten minutes left, so I suggest we confirm the conclusion and owner first.",dark:"These are all worth discussing, but if today's goal is A, we may need to switch the meeting from roaming mode back to navigation.",roast:"We've travelled from A to the edge of the universe. With ten minutes left, let's return to Earth and decide A."},yue:{formal:"我哋先收返今日要決定嘅 A，其他延伸問題可以另外記低。仲有 10 分鐘，建議先確認結論同 owner。",dark:"呢啲都值得傾，但如果今日目標係決定 A，我哋可能要由漫遊模式切返導航。",roast:"我哋由 A 已經傾到宇宙邊緣，剩 10 分鐘先返地球定咗 A。"}});

add("s04","study",{hant:"同學",hans:"同学",en:"Classmate"},{hant:"拒絕抄作業",hans:"拒绝抄作业",en:"Refuse cheating"},{hant:"同學想直接抄你的作業",hans:"同学想直接抄你的作业",en:"A classmate asks to copy your assignment"},
{zh:{formal:{hant:"我可以跟你講思路或一起看你卡住的地方，但作業我不方便直接給你抄。",hans:"我可以跟你讲思路或一起看你卡住的地方，但作业我不方便直接给你抄。"},dark:{hant:"我可以共享腦路，不共享提交結果。",hans:"我可以共享脑路，不共享提交结果。"},roast:{hant:"答案可以討論，作業不能一鍵複製貼上，不然老師會以為我們共用一個帳號。",hans:"答案可以讨论，作业不能一键复制粘贴，不然老师会以为我们共用一个账号。"}},en:{formal:"I can explain the approach or help with the part you're stuck on, but I'm not comfortable letting you copy my assignment.",dark:"I can share the thinking, not the submission.",roast:"We can discuss the answer, but not Ctrl-C/Ctrl-V the whole assignment unless we want the teacher to think we share one account."},yue:{formal:"我可以同你講思路，或者一齊睇你卡住嗰部分，但份功課我唔方便直接俾你抄。",dark:"我可以 share 思路，唔 share 提交結果。",roast:"答案可以傾，功課唔可以一鍵 copy paste，唔係老師會以為我哋共用一個 account。"}});

add("fa01","family",{hant:"家人",hans:"家人",en:"Family member"},{hant:"拒絕臨時借車",hans:"拒绝临时借车",en:"Decline lending a car"},{hant:"家人臨時要借你的車，但你不放心",hans:"家人临时要借你的车，但你不放心",en:"A family member suddenly wants to borrow your car and you're not comfortable"},
{zh:{formal:{hant:"這次車我不方便借，主要是我對保險和使用安排有顧慮。如果你需要，我可以幫你一起找其他交通方式。",hans:"这次车我不方便借，主要是我对保险和使用安排有顾虑。如果你需要，我可以帮你一起找其他交通方式。"},dark:{hant:"親情可以共享，保單責任我想先各自保管。",hans:"亲情可以共享，保单责任我想先各自保管。"},roast:{hant:"人可以借你陪，車這次不加入家庭共享方案。",hans:"人可以借你陪，车这次不加入家庭共享方案。"}},en:{formal:"I'm not comfortable lending the car this time, mainly because of insurance and usage concerns. I can help you find another option.",dark:"I'm happy to share family affection; I'd prefer to keep insurance liability separately owned.",roast:"You can borrow my company, but the car isn't joining the family-sharing plan this time."},yue:{formal:"今次架車我唔方便借，主要係保險同使用安排方面我有顧慮。如果你要，我可以幫你搵其他交通方法。",dark:"親情可以 share，保單責任我想各自保管。",roast:"人可以借你陪，架車今次唔加入家庭共享方案。"}});

add("p03","parenting",{hant:"孩子",hans:"孩子",en:"Child"},{hant:"孩子撒謊",hans:"孩子撒谎",en:"Address lying"},{hant:"你發現孩子為了逃避責任而撒謊",hans:"你发现孩子为了逃避责任而撒谎",en:"You discover your child lied to avoid responsibility"},
{zh:{formal:{hant:"我現在更在意你能不能把真實情況告訴我。做錯事情會處理，但你現在願意說實話，我們就能一起解決。",hans:"我现在更在意你能不能把真实情况告诉我。做错事情会处理，但你现在愿意说实话，我们就能一起解决。"},dark:{hant:"錯誤本身通常能修，版本越改越多反而比較難修。",hans:"错误本身通常能修，版本越改越多反而比较难修。"},roast:{hant:"我們先退出「編故事模式」，切回真實版本，這樣才知道怎麼收尾。",hans:"我们先退出“编故事模式”，切回真实版本，这样才知道怎么收尾。"}},en:{formal:"What matters most now is that you tell me what really happened. We can deal with the mistake, but honesty helps us solve it together.",dark:"The original mistake is usually fixable. Multiple edited versions are harder to repair.",roast:"Let's exit story-writing mode and switch back to the real version so we know what we're actually fixing."},yue:{formal:"我而家最想你講返真實情況。做錯咗我哋可以處理，但你肯講真，我哋先可以一齊解決。",dark:"個錯誤本身通常修到，版本改得愈多反而愈難修。",roast:"我哋先退出『編故事模式』，切返真實版本，先知點樣收尾。"}});

add("p04","parenting",{hant:"孩子",hans:"孩子",en:"Child"},{hant:"不肯睡覺",hans:"不肯睡觉",en:"Bedtime resistance"},{hant:"孩子到了睡覺時間還一直拖延",hans:"孩子到了睡觉时间还一直拖延",en:"Your child keeps delaying bedtime"},
{zh:{formal:{hant:"現在是睡覺時間。你可以選擇先刷牙還是先換睡衣，但今晚的睡覺時間不再往後延。",hans:"现在是睡觉时间。你可以选择先刷牙还是先换睡衣，但今晚的睡觉时间不再往后延。"},dark:{hant:"選項可以談，睡覺這件事今晚不開公投。",hans:"选项可以谈，睡觉这件事今晚不开公投。"},roast:{hant:"你的腦袋可能還想加班，但身體已經到法定下班時間。",hans:"你的脑袋可能还想加班，但身体已经到法定下班时间。"}},en:{formal:"It's bedtime now. You can choose whether to brush your teeth or change first, but bedtime itself isn't moving later tonight.",dark:"The options are negotiable; bedtime itself is not going to a vote tonight.",roast:"Your brain may still want overtime, but your body has reached its legal closing time."},yue:{formal:"而家係瞓覺時間。你可以揀先刷牙定先換衫，但今晚瞓覺時間唔再向後延。",dark:"選項可以傾，瞓覺呢件事今晚唔開公投。",roast:"你個腦可能仲想加班，但身體已經到法定收工時間。"}});

add("e03","elder",{hant:"長輩",hans:"长辈",en:"Elder"},{hant:"回應催生",hans:"回应催生",en:"Handle baby pressure"},{hant:"長輩反覆問你什麼時候生孩子",hans:"长辈反复问你什么时候生孩子",en:"An elder keeps asking when you'll have children"},
{zh:{formal:{hant:"我知道你是關心我們，不過要不要孩子、什麼時候要，是我們需要自己決定的事情。有消息我們會主動告訴你。",hans:"我知道你是关心我们，不过要不要孩子、什么时候要，是我们需要自己决定的事情。有消息我们会主动告诉你。"},dark:{hant:"這個專案目前不接受外部排期，內部有進度會主動發布。",hans:"这个项目目前不接受外部排期，内部有进度会主动发布。"},roast:{hant:"生育計畫不是快遞，暫時沒有可查詢的預計送達時間。",hans:"生育计划不是快递，暂时没有可查询的预计送达时间。"}},en:{formal:"I know you're asking because you care, but whether and when we have children is something we need to decide ourselves. We'll tell you if there's news.",dark:"This project isn't accepting external scheduling at the moment. We'll publish updates internally when there are any.",roast:"Family planning isn't a parcel, so there isn't an estimated delivery date to track right now."},yue:{formal:"我知你係關心我哋，不過要唔要小朋友、幾時要，係我哋自己決定嘅事。有消息會主動話你知。",dark:"呢個 project 暫時唔接受外部排期，內部有進度會主動發布。",roast:"生育計劃唔係快遞，暫時冇預計送達時間可以查。"}});

add("fr03","friends",{hant:"朋友",hans:"朋友",en:"Friend"},{hant:"朋友失約",hans:"朋友失约",en:"Address a no-show"},{hant:"朋友多次臨時放你鴿子",hans:"朋友多次临时放你鸽子",en:"A friend has cancelled on you at the last minute several times"},
{zh:{formal:{hant:"我理解臨時有事，但最近幾次都是很接近約定時間才取消，對我的安排影響比較大。下次如果不確定，我們可以晚一點再確認。",hans:"我理解临时有事，但最近几次都是很接近约定时间才取消，对我的安排影响比较大。下次如果不确定，我们可以晚一点再确认。"},dark:{hant:"我不介意計畫改變，但希望我的時間不要每次都成為最容易被取消的那一格。",hans:"我不介意计划改变，但希望我的时间不要每次都成为最容易被取消的那一格。"},roast:{hant:"我們最近的約會出席率有點像限量活動，我想先提高成功率再約下一場。",hans:"我们最近的约会出席率有点像限量活动，我想先提高成功率再约下一场。"}},en:{formal:"I understand things come up, but the last few cancellations have been very close to the agreed time and affect my plans. Next time, let's confirm later if you're unsure.",dark:"I don't mind plans changing; I just don't want my time to be the easiest slot to cancel every time.",roast:"Our recent attendance rate is starting to look like a limited-release event. Let's improve the success rate before booking the next one."},yue:{formal:"我明白臨時會有事，不過最近幾次都係好近約定時間先取消，對我安排影響幾大。下次如果未肯定，不如遲啲先 confirm。",dark:"我唔介意計劃有變，但唔想我嘅時間每次都係最容易被取消嗰格。",roast:"我哋最近約會嘅出席率有啲似限量活動，想提高成功率先再約下一場。"}});

add("r03","relationship",{hant:"伴侶",hans:"伴侣",en:"Partner"},{hant:"提出分手",hans:"提出分手",en:"End a relationship"},{hant:"你已經決定結束這段關係",hans:"你已经决定结束这段关系",en:"You have decided to end the relationship"},
{zh:{formal:{hant:"我認真想過了，我決定結束這段關係。這不是希望你改變什麼來挽回，而是我已經做出的決定。我希望我們把後續事情平靜處理好。",hans:"我认真想过了，我决定结束这段关系。这不是希望你改变什么来挽回，而是我已经做出的决定。我希望我们把后续事情平静处理好。"},dark:{hant:"這次我想把話說清楚：這不是暫停鍵，也不是測試你會不會挽留，是結束。",hans:"这次我想把话说清楚：这不是暂停键，也不是测试你会不会挽留，是结束。"},roast:{hant:"這段關係我決定不再續訂，不是免費試用結束後提醒付款，是正式取消。",hans:"这段关系我决定不再续订，不是免费试用结束后提醒付款，是正式取消。"}},en:{formal:"I've thought this through carefully, and I've decided to end the relationship. I'm not asking you to change in order to reverse the decision. I hope we can handle the practical next steps calmly.",dark:"I want to be clear: this isn't a pause button or a test of whether you'll chase me. It's the end.",roast:"I've decided not to renew this relationship. This isn't a free-trial payment reminder; it's a full cancellation."},yue:{formal:"我認真諗過，我決定結束呢段關係。呢個唔係想你改變去挽回，而係我已經做咗決定。希望之後嘅事可以平靜處理。",dark:"今次我想講清楚：呢個唔係 pause，亦唔係測試你會唔會挽留，係結束。",roast:"呢段關係我決定唔再續訂，唔係免費試用完提醒付款，係正式取消。"}});

add("sv02","service",{hant:"餐廳",hans:"餐厅",en:"Restaurant staff"},{hant:"禮貌投訴",hans:"礼貌投诉",en:"Make a complaint"},{hant:"餐點明顯有問題，你想要求處理",hans:"餐点明显有问题，你想要求处理",en:"There is a clear problem with your meal and you want it addressed"},
{zh:{formal:{hant:"不好意思，這份餐點有 XX 的問題，和正常狀態差異比較明顯。麻煩幫我看一下是否可以重新製作或換一份，謝謝。",hans:"不好意思，这份餐点有 XX 的问题，和正常状态差异比较明显。麻烦帮我看一下是否可以重新制作或换一份，谢谢。"},dark:{hant:"我不想讓它變成餐桌上的研究課題，麻煩幫我換一份正常版本。",hans:"我不想让它变成餐桌上的研究课题，麻烦帮我换一份正常版本。"},roast:{hant:"這份看起來像主廚今天推出的實驗版，能不能幫我換回正式版？",hans:"这份看起来像主厨今天推出的实验版，能不能帮我换回正式版？"}},en:{formal:"Excuse me, there's a clear issue with this dish: XX. Could you please check whether it can be remade or replaced?",dark:"I'd rather not turn this into a table-side research project. Could I get a normal version instead?",roast:"This looks like today's experimental build from the kitchen. Could I swap it for the release version?"},yue:{formal:"唔好意思，呢份餐有 XX 問題，同正常狀態差得比較明顯。麻煩幫我睇下可唔可以重整或者換一份。",dark:"我唔想佢變成餐枱上嘅研究課題，麻煩幫我換返正常版本。",roast:"呢份睇落似廚房今日推出嘅實驗版，可唔可以幫我換返正式版？"}});

add("j02","job",{hant:"招聘方",hans:"招聘方",en:"Recruiter"},{hant:"談薪資",hans:"谈薪资",en:"Discuss salary"},{hant:"招聘方問你的期望薪資",hans:"招聘方问你的期望薪资",en:"A recruiter asks for your salary expectation"},
{zh:{formal:{hant:"基於這個職位的職責範圍、我的經驗和市場水平，我目前的期望區間是 X–Y。當然我也會綜合考慮整體職責、福利和成長空間。",hans:"基于这个职位的职责范围、我的经验和市场水平，我目前的期望区间是 X–Y。当然我也会综合考虑整体职责、福利和成长空间。"},dark:{hant:"如果工作內容按完整版來談，我也希望薪酬不要按試用版來定。我的期望是 X–Y。",hans:"如果工作内容按完整版来谈，我也希望薪酬不要按试用版来定。我的期望是 X–Y。"},roast:{hant:"職責看起來是 Pro 版，所以我的薪資期待也會按 Pro 版來談，大約 X–Y。",hans:"职责看起来是 Pro 版，所以我的薪资期待也会按 Pro 版来谈，大约 X–Y。"}},en:{formal:"Based on the scope of the role, my experience and the market, my current expectation is in the X–Y range. I'm also considering the total package and growth opportunity.",dark:"If we're discussing the full version of the role, I'd prefer the compensation not to be priced as a trial version. My range is X–Y.",roast:"The responsibilities look like the Pro plan, so I'm discussing compensation on the Pro plan too: roughly X–Y."},yue:{formal:"按呢個職位嘅職責、我嘅經驗同市場水平，我而家期望係 X–Y。當然我都會綜合考慮福利同發展空間。",dark:"如果工作內容係完整版，我都希望人工唔好按試用版定價。期望係 X–Y。",roast:"職責睇落係 Pro 版，所以我嘅人工期待都會按 Pro 版傾，大約 X–Y。"}});

add("b02","business",{hant:"客戶",hans:"客户",en:"Client"},{hant:"催付款",hans:"催付款",en:"Chase payment"},{hant:"發票已逾期，但客戶仍未付款",hans:"发票已逾期，但客户仍未付款",en:"An invoice is overdue and the client still hasn't paid"},
{zh:{formal:{hant:"想跟進一下發票 XX，目前已超過原定付款日期。如已安排付款，麻煩提供預計到賬時間；如需要我們補充任何資料，也請告知。",hans:"想跟进一下发票 XX，目前已超过原定付款日期。如已安排付款，麻烦提供预计到账时间；如需要我们补充任何资料，也请告知。"},dark:{hant:"項目已經按時交付，現在想確認付款這一半是不是也準備完成自己的交付。",hans:"项目已经按时交付，现在想确认付款这一半是不是也准备完成自己的交付。"},roast:{hant:"發票 XX 已經在應收帳款區住了一陣子，想問它大概什麼時候可以搬家。",hans:"发票 XX 已经在应收账款区住了一阵子，想问它大概什么时候可以搬家。"}},en:{formal:"I'm following up on invoice XX, which is now past the agreed payment date. If payment is scheduled, please share the expected date; let us know if you need any documents from us.",dark:"The project was delivered on time. I'm checking whether the payment side is ready to complete its half of the delivery.",roast:"Invoice XX has been living in accounts receivable for a while. Do we know when it might be moving out?"},yue:{formal:"想跟一跟 invoice XX，而家已經過咗原定付款日期。如果已安排付款，麻煩提供預計到賬時間；如果要補資料都可以話我知。",dark:"項目已經準時交付，想確認付款嗰一半係咪都準備完成自己嘅交付。",roast:"Invoice XX 喺應收帳款區住咗一排，想問下佢大概幾時搬屋。"}});

add("t02","travel",{hant:"酒店",hans:"酒店",en:"Hotel staff"},{hant:"房間問題",hans:"房间问题",en:"Room issue"},{hant:"酒店房間與預訂內容不符",hans:"酒店房间与预订内容不符",en:"Your hotel room doesn't match the booking"},
{zh:{formal:{hant:"您好，我預訂的是 A 房型，但目前安排的是 B。這和訂單確認內容不一致，麻煩幫我查一下是否可以按原預訂調整。",hans:"您好，我预订的是 A 房型，但目前安排的是 B。这和订单确认内容不一致，麻烦帮我查一下是否可以按原预订调整。"},dark:{hant:"如果訂單寫 A、入住變 B，我想我們對「確認預訂」的理解可能需要重新對齊。",hans:"如果订单写 A、入住变 B，我想我们对“确认预订”的理解可能需要重新对齐。"},roast:{hant:"我訂的是 A，不是酒店現場盲盒。麻煩幫我換回訂單上的版本。",hans:"我订的是 A，不是酒店现场盲盒。麻烦帮我换回订单上的版本。"}},en:{formal:"Hello, I booked room type A but was assigned B. This doesn't match my booking confirmation. Could you please check and adjust it to the booked room type?",dark:"If the confirmation says A and check-in becomes B, I think our definition of 'confirmed booking' may need some alignment.",roast:"I booked A, not the hotel's live mystery box. Could you switch me back to the version on the confirmation?"},yue:{formal:"你好，我訂嘅係 A 房型，但而家安排咗 B，同確認訂單唔一致。麻煩幫我查下可唔可以按原訂單調整。",dark:"如果訂單寫 A、入住變 B，我諗大家對『確認預訂』嘅理解要重新對一對。",roast:"我訂嘅係 A，唔係酒店現場盲盒。麻煩幫我換返訂單版本。"}});

window.CHAT_SCENARIOS=(window.CHAT_SCENARIOS||[]).concat(A);
})();