// Hand-authored situation titles and three reply stems per language.
// The tone names are internal only; the card never exposes them.
;(function(){
const domainNames={
 workplace:["職場","职场","Work"],study:["學習","学习","Study"],family:["家庭","家庭","Family"],
 parenting:["育兒","育儿","Parenting"],elder:["長輩","长辈","Elders"],friends:["朋友","朋友","Friends"],
 relationship:["感情","感情","Relationship"],social:["社交","社交","Social"],service:["服務","服务","Service"],
 job:["求職","求职","Job Search"],business:["商務","商务","Business"],travel:["旅行","旅行","Travel"],
 medical:["醫療","医疗","Medical"],online:["網絡","网络","Online"]
};
const relations={
 colleague:["同事","同事","Colleague"],manager:["上司","上司","Manager"],teacher:["老師","老师","Teacher"],
 classmate:["同學","同学","Classmate"],parent:["父母","父母","Parent"],relative:["家人","家人","Family member"],
 child:["孩子","孩子","Child"],elder:["長輩","长辈","Elder"],friend:["朋友","朋友","Friend"],
 partner:["伴侶","伴侣","Partner"],neighbor:["鄰居","邻居","Neighbor"],stranger:["陌生人","陌生人","Stranger"],
 staff:["服務人員","服务人员","Service staff"],recruiter:["招聘方","招聘方","Recruiter"],
 client:["客戶","客户","Client"],vendor:["供應商","供应商","Supplier"],companion:["同行者","同行者","Travel companion"],
 clinician:["醫護人員","医护人员","Clinician"],user:["網友","网友","Online user"]
};
const parts={
 hant:{soft:"我想先好好商量一下。",cold:"我只確認一點：",rude:"這件事我不想再反覆說了。",dark:"免得之後又要重新解釋：",yin:"既然都談到這裡了，我也把話說明白。",tea:"可能是我想得太多，不過",roast:"換個直白的說法："},
 hans:{soft:"我想先好好商量一下。",cold:"我只确认一点：",rude:"这件事我不想再反复说了。",dark:"免得之后又要重新解释：",yin:"既然都谈到这里了，我也把话说明白。",tea:"可能是我想得太多，不过",roast:"换个直白的说法："},
 en:{soft:"Could we talk this through? ",cold:"Just to be clear: ",rude:"I don't want to keep repeating this. ",dark:"So we don't have to revisit this later: ",yin:"Since we're being candid, let me be clear. ",tea:"Maybe I'm overthinking this. ",roast:"To put it plainly: "},
 yue:{soft:"不如我哋好好傾下先。",cold:"我只確認一點：",rude:"呢件事我唔想再講好多次。",dark:"免得之後又要重新解釋：",yin:"既然講到呢度，我都講清楚。",tea:"可能係我諗多咗，不過",roast:"講白啲就係："}
};
function tri(s){const a=s.split("|");if(a.length!==3||a.some(v=>!v.trim()))throw Error("Incomplete authored translation: "+s);return {hant:a[0],hans:a[1],en:a[2]}}
function four(s){const a=s.split("|");if(a.length!==4||a.some(v=>!v.trim()))throw Error("Incomplete reply translation: "+s);return a}
function makeReply(f,d,h,domain){const F=four(f),D=four(d),H=four(h),out={zh:{},en:{},yue:{}};
 for(const [lang,key,n] of [["zh","hant",0],["zh","hans",1],["en","en",2],["yue","yue",3]]){
  const p=parts[key],a=F[n],b=D[n],c=H[n];
  const variants={formal:a,soft:p.soft+a,direct:b,cold:p.cold+b,humor:c,tea:p.tea+a};
  if(!["parenting","elder","medical"].includes(domain))Object.assign(variants,{rude:p.rude+b,dark:p.dark+b,yin:p.yin+c,roast:p.roast+c});
  for(const [tone,text] of Object.entries(variants)){
   if(lang==="zh"){out.zh[tone]??={};out.zh[tone][key]=text}
   else out[lang][tone]=text;
  }
 }
 return out;
}
const rows=[
// domain, relation, goal, title, measured / direct / playful replies (Hant | Hans | English | Cantonese)
["workplace","manager","確認優先級|确认优先级|Clarify priority","上司同時交給你兩件都標為最緊急的工作|上司同时交给你两件都标为最紧急的工作|Your manager marks two tasks as equally urgent","A 和 B 都需要今天完成，請幫我確認先做哪項，以及另一項可以延至何時。|A 和 B 都需要今天完成，请帮我确认先做哪项，以及另一项可以延至何时。|Both A and B are due today. Which should I do first, and when can the other move to?|A 同 B 都要今日做完，麻煩你幫我定邊樣先做，另一樣可以延到幾時。","兩項我無法同時先做。請選一項優先。|两项我无法同时先做。请选一项优先。|I can't do both first. Please choose the priority.|兩樣冇辦法同時行先，請揀一樣優先。","如果兩項都是第一名，我需要一個決勝方法；你幫我排一下吧。|如果两项都是第一名，我需要一个决胜办法；你帮我排一下吧。|If both are number one, I need a tie breaker. Could you rank them?|如果兩樣都係第一名，我要個決勝方法；幫我排一排啦。"],
["workplace","colleague","確認會議決定|确认会议决定|Confirm a meeting decision","會議後大家對決定的理解不一樣|会议后大家对决定的理解不一样|People remember the meeting decision differently","我把剛才的結論寫成 A、B、C，請大家在今天內指出有沒有理解偏差。|我把刚才的结论写成 A、B、C，请大家在今天内指出有没有理解偏差。|I've recorded the decisions as A, B and C. Please flag any differences today.|我將頭先結論寫成 A、B、C，大家今日內睇下有冇理解唔同。","先確認會議到底決定了甚麼，再繼續做。|先确认会议到底决定了什么，再继续做。|Let's confirm what was actually decided before proceeding.|先對返個會究竟決定咗乜，再繼續做。","趁會議還沒長出三個平行宇宙，我先發一版結論給大家確認。|趁会议还没长出三个平行宇宙，我先发一版结论给大家确认。|Before this meeting develops three alternate realities, I'll share one summary for confirmation.|趁個會未分裂成三個平行宇宙，我先出一版結論俾大家確認。"],
["workplace","manager","拒絕無償待命|拒绝无偿待命|Set after-hours boundaries","上司要求你週末隨時在線但沒有安排值班|上司要求你周末随时在线但没有安排值班|Your manager expects weekend availability without an on-call plan","若週末需要我值班，請先確認時段、緊急事項範圍和補休安排。|若周末需要我值班，请先确认时段、紧急事项范围和补休安排。|If weekend cover is needed, let's agree on hours, urgent issues and time off in lieu.|如果週末要我當值，請先定時段、緊急事項範圍同補假安排。","我週末不會全天待命；需要值班請正式安排。|我周末不会全天待命；需要值班请正式安排。|I won't be available all weekend. Please arrange formal cover if needed.|我週末唔會全日待命；要當值請正式安排。","週末可以有值班表，但不能靠我的手機自動變成值班表。|周末可以有值班表，但不能靠我的手机自动变成值班表。|We can have an on-call rota, but my phone can't become the rota by default.|週末可以有當值表，但唔可以靠我部手機自動變成當值表。"],
["study","teacher","要求具體反饋|要求具体反馈|Ask for specific feedback","老師只說你的文章不夠好，沒有說哪裡要改|老师只说你的文章不够好，没有说哪里要改|A teacher says your essay needs work without saying where","謝謝您的意見。能否指出最需要修改的兩個段落，以及您希望看到的改進方向？|谢谢您的意见。能否指出最需要修改的两个段落，以及您希望看到的改进方向？|Thank you for the feedback. Which two paragraphs most need revision, and what should improve?|多謝老師意見，可唔可以指出最要改嘅兩段，同埋希望我點改善？","請指出具體問題，我才能修改。|请指出具体问题，我才能修改。|Please point to the specific issues so I can revise them.|麻煩指出具體問題，我先可以改。","我願意改，但『不夠好』這四個字還沒有告訴我從哪一行開始。|我愿意改，但“不够好”这三个字还没有告诉我从哪一行开始。|I'm happy to revise, but 'needs work' doesn't tell me which line to start with.|我願意改，但『唔夠好』未話我知由邊行開始。"],
["study","classmate","拒絕代寫|拒绝代写|Decline doing their work","同學要你替他完成整份報告|同学要你替他完成整份报告|A classmate asks you to write their entire report","我可以跟你討論大綱和資料來源，但報告內容需要你自己完成。|我可以跟你讨论大纲和资料来源，但报告内容需要你自己完成。|I can discuss an outline and sources with you, but you'll need to write the report yourself.|我可以同你傾大綱同資料來源，但份報告要你自己寫。","我不會替你寫報告。|我不会替你写报告。|I won't write the report for you.|我唔會幫你寫份報告。","我可以當讀者，不會變成你報告的隱形作者。|我可以当读者，不会变成你报告的隐形作者。|I can be a reader, not the invisible author of your report.|我可以做讀者，唔會做你份報告嘅隱形作者。"],
["study","teacher","詢問補考安排|询问补考安排|Ask about a make-up exam","你因病缺席考試，想確認補考程序|你因病缺席考试，想确认补考程序|You missed an exam due to illness and need the make-up process","我因病未能參加今天的考試，已備好相關證明。請問補考申請的期限及所需材料是甚麼？|我因病未能参加今天的考试，已备好相关证明。请问补考申请的期限及所需材料是什么？|I missed today's exam due to illness and have documentation. What are the deadline and requirements for a make-up exam?|我病咗未能參加今日考試，已經有證明。想問補考申請限期同要交咩文件？","我需要申請補考，請告訴我程序和期限。|我需要申请补考，请告诉我程序和期限。|I need to request a make-up exam. Please tell me the process and deadline.|我要申請補考，麻煩話我知程序同限期。","這次身體先替我交了缺席申請；補考我會按正式程序辦。|这次身体先替我交了缺席申请；补考我会按正式程序办。|My body filed an absence before I could; I'll follow the formal process for the make-up.|今次身體先幫我請咗假；補考我會跟正式程序申請。"],
["family","relative","分清照護分工|分清照护分工|Share care duties","家人默認只有你負責陪長輩覆診|家人默认只有你负责陪长辈复诊|Your family assumes you alone will take an elder to appointments","我願意參與照顧，但覆診接送需要大家輪流安排；不如先把下個月日期排出來。|我愿意参与照顾，但复诊接送需要大家轮流安排；不如先把下个月日期排出来。|I'm happy to help with care, but appointments need a shared rota. Let's schedule next month.|我願意幫手照顧，但覆診接送要大家輪流；不如先排下個月日子。","我不能獨自負責所有覆診，大家需要分工。|我不能独自负责所有复诊，大家需要分工。|I can't handle every appointment alone. We need to share them.|我唔可以一個人負責晒覆診，大家要分工。","照顧不是單人接力賽，我們把接棒日期排清楚吧。|照顾不是单人接力赛，我们把接棒日期排清楚吧。|Care isn't a solo relay. Let's work out when each of us takes a turn.|照顧唔係單人接力賽，我哋排清楚幾時交棒啦。"],
["family","relative","安排探訪時間|安排探访时间|Arrange visits","家人經常不通知就直接到你家|家人经常不通知就直接到你家|A relative repeatedly visits your home without warning","很高興你來看我們，但下次請先發訊息確認時間，這樣我們能好好安排。|很高兴你来看我们，但下次请先发消息确认时间，这样我们能好好安排。|We enjoy seeing you, but please message before visiting so we can plan properly.|你嚟探我哋我好開心，不過下次可唔可以先發訊息夾時間，等我哋安排好？","來之前請先約時間，不要直接上門。|来之前请先约时间，不要直接上门。|Please arrange a time before coming over; don't just turn up.|嚟之前請先約時間，唔好直接上門。","我家門鈴不是預約系統，先發個訊息我們比較接待得來。|我家门铃不是预约系统，先发个消息我们比较接待得来。|The doorbell isn't a booking system. A message first helps us actually welcome you.|我屋企門鐘唔係預約系統，先發個訊息我哋先招呼得到。"],
["family","parent","拒絕當眾比較|拒绝当众比较|Stop public comparisons","父母在親戚面前拿你的工作和表親比較|父母在亲戚面前拿你的工作和表亲比较|Your parents compare your career with a cousin's at a family gathering","我知道你們關心我的工作，但當眾比較會讓我難堪；這個話題我們私下再談。|我知道你们关心我的工作，但当众比较会让我难堪；这个话题我们私下再谈。|I know you care about my career, but comparing us in front of everyone is uncomfortable. Let's discuss it privately.|我知你哋關心我份工，但當眾比較我會尷尬；呢個話題私下再傾。","請不要在親戚面前比較我們的工作。|请不要在亲戚面前比较我们的工作。|Please don't compare our careers in front of relatives.|請唔好喺親戚面前比較我哋啲工作。","今天的家庭聚會先別開職涯排行榜，好嗎？|今天的家庭聚会先别开职业排行榜，好吗？|Could we skip the family career leaderboard at dinner today?|今日家庭聚會可唔可以唔開職涯排行榜？"],
["parenting","child","承認害怕|承认害怕|Acknowledge fear","孩子第一次去新學校，很害怕自己交不到朋友|孩子第一次去新学校，很害怕自己交不到朋友|Your child fears making no friends at a new school","第一次去新學校會緊張很正常。我們先想一個明天可以試的小步驟，放學後你再告訴我感受。|第一次去新学校会紧张很正常。我们先想一个明天可以试的小步骤，放学后你再告诉我感受。|It's normal to feel nervous at a new school. Let's choose one small thing to try tomorrow and talk after school.|第一次去新學校緊張好正常。我哋諗一個聽日可以試嘅小步驟，放學再同我講感受。","你不用第一天就交到朋友；先認識一個人就好。|你不用第一天就交到朋友；先认识一个人就好。|You don't have to make friends on day one. Start by meeting one person.|你唔使第一日就交到朋友，先識一個人就得。","交朋友不是第一天的考試，我們慢慢來。|交朋友不是第一天的考试，我们慢慢来。|Making friends isn't a first-day exam. We can take it slowly.|交朋友唔係第一日嘅考試，我哋慢慢嚟。"],
["parenting","child","處理弄壞物品|处理弄坏物品|Address a broken item","孩子不小心打碎杯子後怕被責罵|孩子不小心打碎杯子后怕被责骂|Your child breaks a cup and fears being scolded","先別碰碎片，讓我清理。杯子打碎了，我們之後一起想想怎樣拿東西更安全。|先别碰碎片，让我清理。杯子打碎了，我们之后一起想想怎样拿东西更安全。|Stay back from the glass and let me clean it. Then we can talk about carrying things safely.|唔好掂啲碎片，我嚟執。之後我哋一齊諗下點樣拎嘢會安全啲。","先離開碎片，安全最重要；之後再談怎樣避免。|先离开碎片，安全最重要；之后再谈怎样避免。|Move away from the glass first. Safety comes before discussing what happened.|先行開啲碎片，安全最緊要；之後再傾點避免。","杯子可以換，你的小腳不能換。先讓我把地上清乾淨。|杯子可以换，你的小脚不能换。先让我把地上清干净。|We can replace a cup, not your feet. Let me clear the floor first.|隻杯可以換，你對腳唔可以換。等我先執乾淨地下。"],
["parenting","child","談網絡隱私|谈网络隐私|Discuss online privacy","孩子想把校服和學校名稱一起發到公開帳號|孩子想把校服和学校名称一起发到公开账号|Your child wants to post their uniform and school name publicly","我知道你想分享照片。公開帳號上先遮住學校名稱和可辨識的位置，我們一起選一張安全的版本。|我知道你想分享照片。公开账号上先遮住学校名称和可辨认的位置，我们一起选一张安全的版本。|I know you want to share the photo. Let's hide the school name and identifiable location before posting publicly.|我知你想分享相，不過公開帳號要先遮住校名同認得出嘅位置，我哋一齊揀張安全啲嘅。","不要公開學校名稱和位置；先修改照片。|不要公开学校名称和位置；先修改照片。|Don't post your school name or location. Edit the photo first.|唔好公開校名同位置，先改好張相。","照片可以曬，回家的路線就不需要一起曬。|照片可以晒，回家的路线就不用一起晒。|Share the photo, not a map to where you go every day.|張相可以分享，返學路線就唔使一齊分享。"],
["elder","elder","商量安全扶手|商量安全扶手|Suggest a handrail","長輩覺得浴室不用加扶手|长辈觉得浴室不用加扶手|An elder thinks a bathroom handrail is unnecessary","我知道你現在還能自己走動；加扶手是讓洗澡更穩，不是說你做不到。我們一起選個不礙事的位置。|我知道你现在还能自己走动；加扶手是让洗澡更稳，不是说你做不到。我们一起选个不碍事的位置。|I know you manage well. A handrail is for extra stability, not a judgment of your ability. Let's choose a good spot.|我知你而家行動自如；加扶手係沖涼穩陣啲，唔係話你做唔到。我哋一齊揀個唔阻掟嘅位置。","浴室要加扶手，讓出入更安全。|浴室要加扶手，让进出更安全。|Let's add a handrail so the bathroom is safer.|浴室加條扶手，出入會安全啲。","扶手就像樓梯的欄杆，平常未必用，但有需要時能幫大忙。|扶手就像楼梯的栏杆，平时未必用，但有需要时能帮大忙。|A handrail is like a stair rail: you may not need it every time, but it's there when you do.|扶手好似樓梯欄杆，未必次次用，但有需要時幫到手。"],
["elder","elder","教手機操作|教手机操作|Teach phone use","長輩忘了手機付款步驟，又怕麻煩你|长辈忘了手机付款步骤，又怕麻烦你|An elder forgot mobile payment steps and worries about bothering you","不麻煩，我們再慢慢做一次。我把每一步寫在紙上，下次你可以照著看。|不麻烦，我们再慢慢做一次。我把每一步写在纸上，下次你可以照着看。|It's no trouble. Let's do it slowly again and write the steps down for next time.|唔麻煩，我哋慢慢再做一次。我將每一步寫低，下次你可以照住睇。","我們再做一遍，這次把步驟記下來。|我们再做一遍，这次把步骤记下来。|Let's go through it once more and write the steps down.|我哋再做一次，今次將步驟記低。","手機每天都在改版，忘記步驟不代表你學不會。|手机每天都在改版，忘记步骤不代表你学不会。|Phones change their menus all the time. Forgetting a step doesn't mean you can't learn it.|手機成日改版，唔記得一步唔代表你學唔識。"],
["elder","elder","安排定期聯絡|安排定期联系|Arrange regular calls","長輩抱怨你很少打電話但你工作時間不固定|长辈抱怨你很少打电话但你工作时间不固定|An elder wants more calls but your work hours vary","我也想多和你聊。平日下班時間不固定，不如每週日晚上固定通話，臨時有事再傳訊息。|我也想多和你聊。工作日下班时间不固定，不如每周日晚上固定通话，临时有事再发消息。|I'd like to talk more too. My work hours vary, so let's set a Sunday evening call and message between calls.|我都想多啲傾偈。平日放工時間唔定，不如逢星期日晚固定傾電話，有事再發訊息。","平日不能保證即時接電話；每週日晚上我會主動打給你。|工作日不能保证随时接电话；每周日晚上我会主动打给你。|I can't always answer during work, but I'll call you every Sunday evening.|平日未必即時聽到電話，不過逢星期日晚我會主動打俾你。","我們把聊天排進日曆，這樣誰都不用靠猜我哪天剛好下班。|我们把聊天排进日历，这样谁都不用猜我哪天刚好下班。|Let's put our chats on the calendar so nobody has to guess when I've finished work.|我哋將傾偈排入日曆，唔使靠估我邊日放工早。"],
["friends","friend","拒絕透露秘密|拒绝透露秘密|Keep a confidence","朋友追問另一位朋友私下告訴你的秘密|朋友追问另一位朋友私下告诉你的秘密|A friend asks you to reveal another friend's secret","這件事是對方私下告訴我的，我答應保密；如果你關心他，可以直接問他願不願意聊。|这件事是对方私下告诉我的，我答应保密；如果你关心他，可以直接问他愿不愿意聊。|They told me in confidence, so I won't share it. If you're concerned, you can ask them directly whether they want to talk.|呢件事係佢私下同我講，我答應保密；你關心佢可以直接問佢想唔想傾。","我不會轉述別人的秘密。|我不会转述别人的秘密。|I won't pass on someone else's secret.|我唔會轉述人哋嘅秘密。","我的八卦接收功能有開，但轉發功能在這件事上關閉了。|我的八卦接收功能开着，但这件事的转发功能关了。|My listening function works; the forwarding function is off for this one.|我個聽八卦功能有開，不過呢件事嘅轉發功能關咗。"],
["friends","friend","拒絕當免費司機|拒绝当免费司机|Decline repeated lifts","朋友每次聚會都默認你開車接送|朋友每次聚会都默认你开车接送|A friend assumes you'll drive everyone to every gathering","這次我不方便接送，大家可以各自安排交通；如果需要共乘，我們提前商量。|这次我不方便接送，大家可以各自安排交通；如果需要拼车，我们提前商量。|I can't give lifts this time. Let's arrange travel separately, or discuss carpooling beforehand.|今次我唔方便接送，大家各自安排交通；要夾車可以提前傾。","這次不接送，請自行安排交通。|这次不接送，请自行安排交通。|I won't be driving people this time. Please make other travel plans.|今次唔接送，麻煩自己安排交通。","我的車有座位，但沒有自動續約的接送服務。|我的车有座位，但没有自动续约的接送服务。|My car has seats, but it doesn't include an automatic chauffeur subscription.|我架車有位，但冇自動續約接送服務。"],
["friends","friend","表達需要陪伴|表达需要陪伴|Ask for company","你最近壓力很大，想請朋友陪你散步|你最近压力很大，想请朋友陪你散步|You're stressed and want a friend to walk with you","我最近壓力有點大，不需要你幫我解決問題；如果你有空，這週能陪我走走嗎？|我最近压力有点大，不需要你帮我解决问题；如果你有空，这周能陪我走走吗？|I've been under pressure. I don't need you to fix it, but would you have time for a walk this week?|我最近壓力幾大，唔使你幫我解決；你呢個禮拜有冇時間陪我行下？","我想找人陪我散步，你這週有空嗎？|我想找人陪我散步，你这周有空吗？|I'd like company for a walk. Are you free this week?|我想搵人陪我散下步，你今個禮拜得唔得閒？","我這週的腦內分頁太多，想找你陪我出門散散熱。|我这周脑内开的页面太多，想找你陪我出门散散热。|My brain has too many tabs open. Want to help me clear a few on a walk?|我個腦今個禮拜開咗太多分頁，想搵你陪我出去散下熱。"],
["relationship","partner","協商獨處時間|协商独处时间|Ask for alone time","伴侶覺得你想獨處就是不愛他|伴侣觉得你想独处就是不爱他|Your partner takes your need for alone time as rejection","我很在乎你，也需要一點獨處時間恢復精神。今晚我想自己待兩小時，之後我們再一起吃飯。|我很在乎你，也需要一点独处时间恢复精神。今晚我想自己待两小时，之后我们再一起吃饭。|I care about you and also need time alone to recharge. I'd like two hours tonight, then dinner together.|我好重視你，亦都要少少獨處時間充電。今晚想自己待兩個鐘，之後一齊食飯。","我今晚需要兩小時獨處，之後再一起相處。|我今晚需要两小时独处，之后再一起相处。|I need two hours alone tonight. We can spend time together afterwards.|我今晚要兩個鐘獨處，之後再一齊。","我需要把自己的電量充回來，不代表把我們的連線拔掉。|我需要把自己的电量充回来，不代表把我们的连接拔掉。|I need to recharge my battery, not disconnect from us.|我要幫自己叉返電，唔係要拔咗我哋條連線。"],
["relationship","partner","談共同開支|谈共同开支|Discuss shared expenses","你們搬到一起後一直沒談共同開支|你们搬到一起后一直没谈共同开支|You moved in together without discussing shared bills","我們把房租、水電和日用品列出來，再商量各自負擔的比例，避免月底才發現認知不同。|我们把房租、水电和日用品列出来，再商量各自承担的比例，避免月底才发现理解不同。|Let's list rent, utilities and groceries, then agree on a split before the end of the month.|我哋列返租金、水電同日用品，再傾各自負擔幾多，免得月底先發現理解唔同。","本週把共同開支和分攤方式定下來。|本周把共同开支和分摊方式定下来。|Let's agree on shared expenses and the split this week.|今個禮拜定好共同開支同點分。","愛情可以隨性，水電帳單通常不會；我們把數字對一對。|爱情可以随性，水电账单通常不会；我们把数字对一对。|Love can be spontaneous. Utility bills usually aren't. Let's check the numbers.|感情可以隨性，水電單通常唔得；我哋對一對啲數。"],
["relationship","partner","提出道歉後的改變|提出道歉后的改变|Offer repair after an apology","你答應改變卻又犯了同樣的錯|你答应改变却又犯了同样的错|You repeated a mistake after promising to change","我上次承諾會改，這次又發生，讓你失望是我的責任。我想先聽你受了甚麼影響，再說明具體怎樣避免重複。|我上次承诺会改，这次又发生，让你失望是我的责任。我想先听你受了什么影响，再说明具体怎样避免重复。|I promised to change and repeated it. That's on me. I want to hear how it affected you and agree on specific steps to prevent it.|我上次應承會改，今次又發生，令你失望係我責任。我想先聽你受咗咩影響，再講具體點避免。","我又犯了同樣的錯，對不起；這次我會提出可檢查的改變。|我又犯了同样的错，对不起；这次我会提出可检验的改变。|I repeated the same mistake. I'm sorry, and I'll offer a change you can actually check.|我又犯咗同一個錯，對唔住；今次我會提出可以檢查嘅改變。","道歉不是重設按鈕；我需要拿出真正不同的做法。|道歉不是重置按钮；我需要拿出真正不同的做法。|An apology isn't a reset button. I need to do something differently.|道歉唔係重設掣；我要真係做啲唔同嘅事。"],
["social","neighbor","協商公共空間|协商公共空间|Discuss shared space","鄰居把雜物長期放在共用走廊|邻居把杂物长期放在共用走廊|A neighbor keeps belongings in the shared hallway","走廊是大家共用的通道，最近放的物品影響出入。能否在本週內移回家中？|走廊是大家共用的通道，最近放的物品影响出入。能否在本周内搬回家中？|The hallway is shared and the items make access difficult. Could you move them inside this week?|走廊係共用通道，啲雜物阻住出入；可唔可以今個禮拜搬返入屋？","請把走廊的雜物移走，保持通道暢通。|请把走廊的杂物搬走，保持通道畅通。|Please clear the belongings from the shared hallway.|麻煩搬走走廊啲雜物，保持通道暢通。","走廊想繼續當走廊，不太適合兼職做儲物室。|走廊想继续当走廊，不太适合兼职做储物间。|The hallway would like to keep its day job as a hallway, not become a storage unit.|走廊都想繼續做走廊，唔太想兼職做雜物房。"],
["social","stranger","回應冒犯玩笑|回应冒犯玩笑|Respond to an offensive joke","聚會上有人拿你的口音開玩笑|聚会上有人拿你的口音开玩笑|Someone makes your accent the joke at a gathering","我知道你可能當成玩笑，但拿我的口音說笑讓我不舒服。請換個話題。|我知道你可能当成玩笑，但拿我的口音说笑让我不舒服。请换个话题。|You may mean it as a joke, but joking about my accent is uncomfortable. Please change the subject.|我知你可能當講笑，不過攞我口音講笑我唔舒服，麻煩轉個話題。","別拿我的口音開玩笑。|别拿我的口音开玩笑。|Don't make jokes about my accent.|唔好攞我口音講笑。","口音確實很多元，笑點可以再找別的。|口音确实很多元，笑点可以再找别的。|Accents are varied. I'm sure we can find a different joke.|口音係好多元，笑點都可以搵第二個。"],
["social","stranger","拒絕交換聯絡方式|拒绝交换联系方式|Decline exchanging contacts","剛認識的人堅持要你的電話號碼|刚认识的人坚持要你的电话号码|A new acquaintance insists on your phone number","謝謝，不過我暫時不交換私人電話；有需要可以透過活動平台聯絡。|谢谢，不过我暂时不交换私人电话；有需要可以通过活动平台联系。|Thanks, but I don't share my personal number with new acquaintances. The event platform works for messages.|多謝，不過我暫時唔交換私人電話；有需要可以喺活動平台聯絡。","我不提供私人電話，請不要再問。|我不提供私人电话，请不要再问。|I'm not giving you my number. Please stop asking.|我唔會俾私人電話，唔該唔好再問。","我的電話號碼今天沒有加入社交活動，活動平台見。|我的电话号码今天没报名参加社交活动，活动平台见。|My phone number didn't sign up for this event. You can reach me on the event platform.|我個電話號碼今日冇報名參加活動，平台見啦。"],
["service","staff","要求核對收費|要求核对收费|Question a charge","帳單上出現你沒有點過的項目|账单上出现你没有点过的项目|Your bill includes an item you did not order","不好意思，帳單上的 XX 不是我們點的。可以核對一下點單紀錄並更正金額嗎？|不好意思，账单上的 XX 不是我们点的。可以核对一下点单记录并更正金额吗？|Excuse me, we didn't order XX. Could you check the order and correct the bill?|唔好意思，張單上面 XX 唔係我哋叫嘅。可唔可以核對落單紀錄再改返金額？","XX 不是我們點的，請更正帳單。|XX 不是我们点的，请更正账单。|We didn't order XX. Please correct the bill.|XX 唔係我哋叫嘅，麻煩改返張單。","這道菜只在帳單上出現，沒有到桌上；能把它請下去嗎？|这道菜只在账单上出现，没到桌上；能把它从账单上请走吗？|This dish showed up only on the bill, not the table. Could you take it off?|呢道菜只係張單度出現，冇上枱；可唔可以請佢落返去？"],
["service","staff","要求維修進度|要求维修进度|Request repair status","報修一週後仍沒有人告知進度|报修一周后仍没人告知进度|You have no update a week after reporting a repair","我上週報修了 XX，至今尚未收到處理時間。請提供案件編號、目前狀態和預計上門日期。|我上周报修了 XX，至今尚未收到处理时间。请提供工单号、当前状态和预计上门日期。|I reported XX last week and haven't had an update. Please share the case number, status and expected visit date.|我上個禮拜報修咗 XX，到而家未有時間表。麻煩提供單號、進度同預計上門日子。","請告訴我報修案件的進度和上門日期。|请告诉我报修工单的进度和上门日期。|Please give me the repair status and visit date.|麻煩話我知維修進度同幾時上門。","這張維修單已經滿一週歲了，想知道它走到哪一步。|这张维修单已经满一周岁了，想知道它走到哪一步。|The repair ticket is a week old now. Has it made it to the next step?|張維修單已經過咗一個禮拜，想知佢去到邊一步。"],
["service","staff","確認無障礙安排|确认无障碍安排|Confirm accessibility","活動現場沒有標示無障礙入口|活动现场没有标示无障碍入口|An event venue has no marked accessible entrance","您好，我需要無障礙通道，但現場找不到入口標示。請問可以從哪裡進入，是否有人能協助？|您好，我需要无障碍通道，但现场找不到入口标识。请问从哪里进入，是否有人可以协助？|Hello, I need an accessible entrance but can't find one marked. Where should I go, and can someone assist?|你好，我要用無障礙通道，但現場搵唔到入口指示。請問由邊度入，有冇人可以幫手？","請指出無障礙入口並安排協助。|请指出无障碍入口并安排协助。|Please show me the accessible entrance and arrange assistance.|麻煩指出無障礙入口，同埋安排人幫手。","我想順利進場，不想把找入口變成尋寶遊戲。|我想顺利进场，不想把找入口变成寻宝游戏。|I'd like to get inside without turning the entrance into a treasure hunt.|我想順利入場，唔想搵入口變咗尋寶遊戲。"],
["job","recruiter","確認遠端政策|确认远程办公政策|Clarify remote work","職位寫可以遠端，面試時卻說必須每天到辦公室|职位写可远程，面试时却说必须每天到办公室|A job advert says remote work is possible but the interview says daily office attendance","我看到職位介紹寫可以遠端工作，剛才聽到的是每天到辦公室。想確認目前正式的工作地點政策。|我看到职位介绍写可以远程办公，刚才听到的是每天到办公室。想确认目前正式的工作地点政策。|The advert mentioned remote work, while the interview suggests daily office attendance. Could you clarify the current policy?|職位介紹寫可以 remote，頭先又話每日返 office，想確認正式安排係點。","這份工作到底可否遠端？請確認具體天數。|这份工作到底能否远程？请确认具体天数。|Is this role remote or office-based? Please confirm the number of days.|呢份工究竟可唔可以 remote？麻煩確認具體日數。","職位描述和面試似乎在不同地點上班，我想先對齊。|职位描述和面试似乎在不同地点上班，我想先对齐。|The advert and the interview seem to work in different locations. Let's align them.|職位介紹同面試好似喺兩個地方返工，想先對返。"],
["job","recruiter","要求合理考慮時間|要求合理考虑时间|Ask for decision time","公司要求你當天答覆錄用通知|公司要求你当天答复录用通知|An employer demands a same-day decision on an offer","謝謝錄用通知，我很重視這個機會。希望有時間仔細閱讀條款，可否延至週五下午回覆？|谢谢录用通知，我很重视这个机会。希望有时间仔细阅读条款，能否延至周五下午回复？|Thank you for the offer. I'd like time to review the terms carefully. May I respond by Friday afternoon?|多謝你哋嘅 offer，我好重視呢個機會。想仔細睇條款，可唔可以星期五下晝先覆？","我今天不能確認；週五下午前會答覆。|我今天不能确认；周五下午前会答复。|I can't decide today. I'll respond by Friday afternoon.|我今日確認唔到，星期五下晝前會答覆。","工作可能做幾年，讓我多看兩天條款會比較負責任。|工作可能做几年，让我多看两天条款会比较负责任。|I may be doing this job for years; two days to review the terms seems reasonable.|份工可能做幾年，俾我多兩日睇清條款會負責任啲。"],
["job","recruiter","詢問面試安排|询问面试安排|Request interview details","收到面試邀請但沒有地址或視訊連結|收到面试邀请但没有地址或视频链接|An interview invitation lacks an address or video link","謝謝邀請。我可以在週三下午參加面試，麻煩提供具體時間、地點或視訊連結，以及預計面試時長。|谢谢邀请。我可以在周三下午参加面试，麻烦提供具体时间、地点或视频链接，以及预计面试时长。|Thank you for the invitation. Wednesday afternoon works. Please send the time, location or video link, and expected duration.|多謝邀請，我星期三下晝可以面試。麻煩俾我具體時間、地點或者視像連結，同埋預計幾耐。","請補充面試的時間、地點或連結。|请补充面试时间、地点或链接。|Please send the interview time, location or link.|麻煩補返面試時間、地點或者 link。","我已經準備好面試，只差知道要去哪個房間或連結。|我已经准备好面试，只差知道要去哪个房间或链接。|I'm ready for the interview; I just need to know which room or link to enter.|我準備好面試喇，只差知道入邊間房或者邊條 link。"],
["business","client","釐清驗收標準|厘清验收标准|Clarify acceptance criteria","客戶說成果不符合期待，但沒有列出具體差異|客户说成果不符合预期，但没有列出具体差异|A client says the deliverable falls short without specifics","收到反饋。為了準確修改，請按已確認的驗收項目指出不符之處，並附上期望的示例。|收到反馈。为了准确修改，请按已确认的验收项目指出不符之处，并附上期望的示例。|Thanks for the feedback. To revise accurately, please identify gaps against the agreed acceptance criteria and share an example.|收到意見。想改得準確，麻煩按已確認嘅驗收項目指出差異，最好附個例子。","請列出具體不符合的項目和期望結果。|请列出具体不符合的项目和期望结果。|Please list the specific gaps and the expected result.|麻煩列明邊項唔符合，同埋期望結果。","我可以修改成目標版本，先讓我看到目標長甚麼樣。|我可以修改到目标版本，先让我看到目标长什么样。|I can aim for the target; first I need to see what the target looks like.|我可以改到目標版本，不過要先知個目標係點樣。"],
["business","vendor","要求列明附加費|要求列明附加费|Request itemized fees","供應商報價後又口頭追加未列出的費用|供应商报价后又口头追加未列出的费用|A supplier adds unlisted fees after quoting","麻煩把新增費用逐項列明原因、金額和適用條件，並發更新後的正式報價供我們審核。|麻烦把新增费用逐项列明原因、金额和适用条件，并发更新后的正式报价供我们审核。|Please itemize the new charges with reasons and conditions, then send an updated formal quote for review.|麻煩逐項列明新增費用嘅原因、金額同適用條件，再發正式更新報價俾我哋。","沒有書面明細前，我們不確認新增費用。|没有书面明细前，我们不确认新增费用。|We can't approve the new fees without a written breakdown.|未有書面明細之前，我哋唔會確認新增費用。","報價單不要在電話裡自己長出新欄位；請發正式版本。|报价单别在电话里自己长出新栏目；请发正式版本。|The quote shouldn't grow new columns during a phone call. Please send the revised version.|張報價單唔好喺電話度自己生出新欄位；麻煩發正式版本。"],
["business","client","確認審批人|确认审批人|Identify approver","項目每次都收到不同人的相反修改意見|项目每次都收到不同人的相反修改意见|A project receives conflicting revision requests from different stakeholders","目前收到 A 和 B 兩組相反意見。為避免反覆修改，請指定一位最終審批人，統一回覆確認版。|目前收到 A 和 B 两组相反意见。为避免反复修改，请指定一位最终审批人，统一回复确认版。|We've received conflicting comments from A and B. Could you nominate a final approver to consolidate the decision?|目前 A 同 B 嘅意見相反。為免改完又改，可唔可以指定一位最終審批人統一確認？","請指定最終審批人；我們按一份整合意見修改。|请指定最终审批人；我们按一份整合意见修改。|Please appoint one final approver. We'll revise against one consolidated set of comments.|麻煩指定最終審批人，我哋跟一份整合意見改。","我們的檔案目前被要求同時向左和向右轉，先請一位導航員定方向。|我们的文件目前被要求同时向左和向右转，先请一位导航员定方向。|The document is being asked to turn left and right at once. Could we appoint a navigator?|份文件而家要同時左轉同右轉，可唔可以先搵一位導航員定方向？"],
["travel","staff","詢問遺失行李|询问遗失行李|Report missing baggage","落地後轉盤一直沒有你的行李|落地后转盘一直没有你的行李|Your bag never appears on the arrival carousel","我的行李沒有出現在轉盤，這是行李牌號碼。請協助登記遺失，提供追蹤編號和送達方式。|我的行李没有出现在转盘，这是行李牌号码。请协助登记遗失，提供追踪编号和送达方式。|My bag hasn't arrived on the carousel. Here's the tag number. Please file a report and give me a tracking reference and delivery plan.|我件行李冇喺轉盤出現，呢個係行李牌號碼。麻煩登記，俾個追蹤編號同送達安排我。","請登記遺失行李並提供追蹤編號。|请登记遗失行李并提供追踪编号。|Please file a missing baggage report and give me a reference number.|麻煩登記遺失行李，俾個追蹤編號我。","人已經落地，行李似乎還在旅行；先幫我查它到哪裡了。|人已经落地，行李似乎还在旅行；先帮我查它到哪儿了。|I've landed, but my bag seems to be travelling on. Can we find its next stop?|我落咗地，件行李好似仲喺旅行；麻煩查下佢去咗邊。"],
["travel","companion","協商休息時間|协商休息时间|Ask for a break","同行者想連續走景點，你已經非常疲累|同行者想连续逛景点，你已经非常疲惫|Your travel companion wants another stop when you're exhausted","我現在真的走不動了，想休息一小時。你可以先去下一站，我們之後在餐廳會合。|我现在真的走不动了，想休息一小时。你可以先去下一站，我们之后在餐厅会合。|I'm exhausted and need an hour's rest. Feel free to go ahead; we can meet at the restaurant later.|我而家真係行唔郁，想抖一個鐘。你可以先去下一站，之後喺餐廳會合。","我需要休息一小時，之後再會合。|我需要休息一小时，之后再会合。|I need an hour's break. Let's meet up afterwards.|我想抖一個鐘，之後再會合。","我的腳今天已經打卡下班，你先玩，我休息後追上。|我的脚今天已经打卡下班，你先玩，我休息后追上。|My feet have clocked out for an hour. Go ahead and I'll catch up.|我對腳今日暫時收工，你先玩，我抖完追返你。"],
["travel","staff","要求說明換乘|要求说明换乘|Clarify a connection","車站臨時換月台，廣播聽不清楚|车站临时换站台，广播听不清楚|A station changes platforms and the announcement is unclear","您好，我乘坐 XX 班次，剛才沒聽清楚變更。請問現在從哪個月台上車，是否仍按原時間開出？|您好，我乘坐 XX 班次，刚才没听清楚变更。请问现在从哪个站台上车，是否仍按原时间出发？|I'm taking service XX and missed the announcement. Which platform is it now, and is departure still on time?|你好，我搭 XX 班次，頭先聽唔清廣播。依家去邊個月台？仲係原本時間開車？","XX 班次改到哪個月台？開車時間有變嗎？|XX 班次改到哪个站台？发车时间变了吗？|Which platform for XX, and has the departure time changed?|XX 班次改咗去邊個月台？開車時間有冇變？","我追得上火車，但得先知道火車搬去哪個月台。|我追得上车，但得先知道车搬到哪个站台。|I can catch the train once I know where the train has moved.|我追得上架車，不過要先知佢搬咗去邊個月台。"],
["medical","clinician","確認用藥方法|确认用药方法|Clarify medicine instructions","出院後你不確定藥物何時服用|出院后你不确定药物何时服用|You are unsure when to take a medicine after discharge","我想核對藥單：這種藥每天幾次、是否隨餐服用？我可以重述一次，請您確認我理解正確。|我想核对药单：这种药每天几次、是否随餐服用？我可以复述一次，请您确认我理解正确。|Could we review this prescription: how often should I take it and with food or not? I'll repeat it back to check I've understood.|我想對返張藥單：呢隻藥一日食幾次，要唔要跟餐？我講返一次，麻煩你確認我理解啱唔啱。","請把服藥次數和時間寫清楚給我。|请把服药次数和时间写清楚给我。|Please write down the dose schedule and timing for me.|麻煩寫清楚食藥次數同時間俾我。","我不想靠猜藥盒上的小字，麻煩我們把時間對準。|我不想靠猜药盒上的小字，麻烦把时间对准。|I don't want to guess from the tiny label; let's make the timing clear.|我唔想靠估藥盒啲細字，麻煩對清楚時間。"],
["medical","clinician","詢問警示徵狀|询问警示症状|Ask about warning signs","看診後你想知道甚麼變化需要再求醫|看诊后你想知道什么变化需要再就医|You want to know when to seek care again","回家後如果症狀加重，哪些具體情況需要立即求醫？哪些情況可以按原定時間覆診？|回家后如果症状加重，哪些具体情况需要立即就医？哪些情况可以按原计划复诊？|If symptoms change at home, which signs require urgent care and which can wait for the planned follow-up?|返屋企之後如果症狀有變，邊啲情況要即刻求醫，邊啲可以等原定覆診？","請列出需要立即求醫的警示徵狀。|请列出需要立即就医的警示症状。|Please list the warning signs that mean I should seek urgent care.|麻煩講清楚邊啲警示徵狀要即刻求醫。","我想帶走一張清楚的『甚麼時候回來』地圖，而不是靠猜。|我想带走一张清楚的“什么时候回来”路线图，而不是靠猜。|I'd like a clear map for when to come back, rather than guessing.|我想帶走一張清楚嘅『幾時返嚟睇』地圖，唔想靠估。"],
["medical","clinician","要求私下談話|要求私下谈话|Request privacy","診症時陪同親友在場，你想獨自回答敏感問題|看诊时陪同亲友在场，你想单独回答敏感问题|A relative is present but you want to answer sensitive questions privately","謝謝陪我來。接下來有些私人問題，我想和醫護人員單獨談幾分鐘，待會再請你進來。|谢谢陪我来。接下来有些私人问题，我想和医护人员单独谈几分钟，待会儿再请你进来。|Thank you for coming with me. I'd like a few minutes alone with the clinician for private questions, then you can come back in.|多謝你陪我嚟。跟住有啲私人問題，我想單獨同醫護傾幾分鐘，陣間再請你入嚟。","我需要單獨與醫護人員談一會。|我需要单独和医护人员谈一会儿。|I need a few minutes alone with the clinician.|我想單獨同醫護傾一陣。","這段先切換成一對一，談完我再叫你進來。|这段先切换成一对一，谈完再请你进来。|Let's switch this part to one-to-one; I'll invite you back afterwards.|呢段先轉一對一，傾完我再請你入嚟。"],
["online","user","拒絕公開個資|拒绝公开个人信息|Protect personal details","有人在公開留言要求你貼出身分證照片|有人在公开评论要求你贴出身份证照片|Someone asks you to post an ID photo in a public comment","我不會在公開區域提供身分證照片。如確需驗證，請提供官方、安全的提交方式和用途說明。|我不会在公开区域提供身份证照片。如确需验证，请提供官方、安全的提交方式和用途说明。|I won't post ID in a public thread. If verification is required, please provide an official secure channel and explain its purpose.|我唔會喺公開留言貼身份證相。如真係要驗證，請提供官方安全渠道同用途說明。","我不會公開身分證照片。|我不会公开身份证照片。|I won't post my ID publicly.|我唔會公開身份證相。","身分證不是留言區的貼圖，請走正式驗證渠道。|身份证不是评论区的贴图，请走正规验证渠道。|My ID isn't a comment sticker. Please use an official verification channel.|身份證唔係留言區貼圖，麻煩用正式驗證渠道。"],
["online","user","澄清冒名帳號|澄清冒名账号|Report impersonation","有人建立與你同名的帳號私訊你的朋友|有人创建同名账号私信你的朋友|An impersonation account is messaging your friends","提醒大家：這個帳號不是我，請不要點擊它發的連結或轉帳。我已向平台舉報，收到訊息可直接向我原帳號核實。|提醒大家：这个账号不是我，请不要点击它发的链接或转账。我已向平台举报，收到消息可直接向我的原账号核实。|That account isn't mine. Please don't click its links or send money. I've reported it; check with me through my original account.|提提大家：呢個帳號唔係我，唔好撳佢啲 link 或轉帳。我已經舉報，有訊息可以用我原本帳號核實。","那個帳號是假冒的，請不要回覆或轉帳。|那个账号是假冒的，请不要回复或转账。|That account is impersonating me. Don't reply or send money.|嗰個帳號係假冒，唔好覆佢或者轉帳。","我沒有開分身帳號；看到另一個『我』借錢，請先問真正的我。|我没有开分身账号；看到另一个“我”借钱，请先问真正的我。|I haven't made a clone account. If another 'me' asks for money, check with the original.|我冇開分身帳號；見到另一個『我』借錢，先問返真嘅我。"],
["online","user","拒絕移到私人平台|拒绝转到私人平台|Keep contact on platform","網購賣家要求你離開平台私下付款|网购卖家要求你离开平台私下付款|An online seller wants you to pay outside the marketplace","為保障雙方交易紀錄，我只會透過平台完成付款和溝通。若不能按平台流程交易，我會取消訂單。|为保留双方交易记录，我只会通过平台完成付款和沟通。如果不能按平台流程交易，我会取消订单。|To keep a record for both sides, I'll only pay and message through the marketplace. Otherwise I'll cancel the order.|為咗保留交易紀錄，我只會喺平台付款同溝通。如果唔可以跟平台流程，我會取消張單。","我不會私下付款，只用平台交易。|我不会私下付款，只通过平台交易。|I won't pay outside the marketplace.|我唔會私下付款，只會喺平台交易。","付款不需要走秘密通道，平台上完成就好。|付款不需要走秘密通道，在平台完成就好。|Payment doesn't need a secret side door. Let's keep it on the platform.|付款唔使行秘密通道，喺平台做就得。"],
];
const additions=rows.filter(r=>!r[3].startsWith("同行者想連續走景點，")).map((r,i)=>({id:"wave6-"+String(i+1).padStart(3,"0"),domain:r[0],domainLabel:tri(domainNames[r[0]].join("|")),relation:tri(relations[r[1]].join("|")),goal:tri(r[2]),title:tri(r[3]),replies:makeReply(r[4],r[5],r[6],r[0])}));
window.CHAT_SCENARIOS=(window.CHAT_SCENARIOS||[]).concat(additions);
})();
