window.CHAT_SCENARIOS = [
  {
    "d": "職場",
    "r": "同事",
    "g": "催進度",
    "t": "同事答應今天交資料，但一直沒交",
    "x": "希望對方盡快交付，又不想把氣氛弄僵",
    "formal": "想跟進一下 XX 資料目前的進度。我們這邊需要在今天 4 點前開始整合，如最終版本仍在整理，也可以先提供目前版本，謝謝。",
    "natural": "XX 那份資料現在大概到哪了？我這邊準備開始整合，如果還沒完全弄完，先給我目前版本也可以。",
    "eq": "不知道你那邊是不是還在整理 XX，如果方便的話可以先把目前版本給我，我這邊先開始處理，後面有更新再補也沒問題。",
    "direct": "麻煩今天 4 點前把目前版本發給我，我這邊需要開始整合。",
    "dark": "怕最後大家一起趕，所以先確認一下 XX 現在方便給到哪個版本。",
    "roast": "我已經和這份資料建立感情了，就是還沒見過它本人。現在方便讓我們見一面嗎？",
    "cantonese": "想跟一跟 XX 嗰份資料而家做到邊。如果仲執緊，可以俾住現有版本我先，我呢邊可以開始整合。",
    "english": "Just following up on the XX information. If the final version is still being prepared, feel free to send me the current version first so we can start consolidating."
  },
  {
    "d": "職場",
    "r": "上司",
    "g": "表達不同意見",
    "t": "你不同意上司提出的方案",
    "x": "指出風險，但避免直接否定",
    "formal": "我理解這個方向。補充一個可能需要考慮的風險：如果 XX 發生，可能會影響 XX。是否可以同時保留一個備選方案？",
    "natural": "這個方向我理解，不過我有一個小擔心：如果 XX 出現，後面可能會比較被動。我們要不要順手留個 Plan B？",
    "eq": "我覺得這個方向有它的優勢。我想再補一個角度，主要擔心 XX 的風險。如果能一起把這點兜住，方案會更穩。",
    "direct": "我主要反對的是 XX 風險，不是整個方向。建議先把這個問題處理掉再推。",
    "dark": "方案本身可以推，我只想先把 XX 這個風險留在紀錄裡，免得之後大家突然第一次聽說。",
    "roast": "方向可以，先把救生衣穿上再出海就更完整了。我的擔心主要是 XX。",
    "cantonese": "個方向我明白，不過我有少少擔心 XX 呢個風險。可唔可以同時留一個後備方案，會穩陣啲。",
    "english": "I understand the direction. One risk I would like to flag is XX. It may be worth keeping a fallback option in case that materialises."
  },
  {
    "d": "職場",
    "r": "同事",
    "g": "拒絕加塞",
    "t": "同事臨時把額外工作丟給你",
    "x": "不接無限責任，但保留合作空間",
    "formal": "我目前在處理 A 和 B，今天的排期已滿。如果這項需要優先處理，我們可以一起確認一下哪一項現有工作往後調整。",
    "natural": "我今天手上 A、B 都在趕。這個如果要插進來可以，但我們得先確認哪一個往後順延。",
    "eq": "我可以幫忙，不過現在手上的排期已經滿了。你看這件事是不是比 A 更急？如果是，我們一起調一下優先順序。",
    "direct": "可以接，但需要換掉目前一項工作，沒辦法三件同時今天完成。",
    "dark": "沒問題，只要我們先決定今天哪件事正式不做，我就按新的優先級排。",
    "roast": "我的工時目前沒有偷偷長出第三隻手，所以可以加，但得先拿掉一件。",
    "cantonese": "可以幫，不過我今日 A 同 B 都排滿咗。如果呢件要插隊，我哋要先定邊一樣順延。",
    "english": "I can take this on, but my schedule is already full with A and B. If this needs to take priority, let's agree which existing item should move."
  },
  {
    "d": "學習",
    "r": "老師",
    "g": "請教問題",
    "t": "上課後想問老師一個沒聽懂的問題",
    "x": "讓問題具體，避免只說「我不懂」",
    "formal": "老師您好，我在 XX 這一步沒有理解清楚。我目前理解到 A，但不知道為什麼接下來可以推出 B，方便再說明一下這一步嗎？",
    "natural": "老師，我卡在 XX 這一步。我能理解 A，但不知道怎麼從 A 到 B，可以再講一下嗎？",
    "eq": "老師，我想確認一下是不是我前面理解偏了：A 我能跟上，但到 B 這一步就接不上了。您方便幫我指出我漏了哪一層嗎？",
    "direct": "老師，我不理解 A 到 B 的推導，能再解釋這一步嗎？",
    "dark": "我目前和這一步還沒有達成共識，主要卡在 A 為什麼能推出 B。",
    "roast": "我的腦子在 A 順利上車，到 B 的時候被落在站台了。老師可以補一下中間這一步嗎？",
    "cantonese": "老師，我卡咗喺 XX 呢一步。A 我明，但唔知點樣去到 B，可唔可以再講一次中間嗰步？",
    "english": "I understand A, but I’m not clear on how it leads to B. Could you walk me through that step again?"
  },
  {
    "d": "學習",
    "r": "組員",
    "g": "催小組作業",
    "t": "小組作業快截止，組員還沒交自己的部分",
    "x": "明確截止與下一步",
    "formal": "提醒一下，我們明天需要提交作業。麻煩今晚 9 點前把你負責的部分放到共享文件，之後還需要預留時間統一格式和檢查。",
    "natural": "提醒一下，明天就要交了。你那部分今晚 9 點前能放進共享文件嗎？我們後面還得一起收尾。",
    "eq": "怕大家最後太趕，先對一下時間：你負責的部分今晚 9 點前能不能先放上去？不完整也可以先放目前版本。",
    "direct": "今晚 9 點前請把你負責的部分上傳，否則我們沒有時間整合。",
    "dark": "先把 deadline 說清楚，免得最後共享文件裡只剩大家共享焦慮。",
    "roast": "截止日期已經在門口按門鈴了，你那部分今晚 9 點前能出現嗎？",
    "cantonese": "提一提，聽日就要交。你嗰部分今晚 9 點前可唔可以放上 shared doc？之後我哋仲要執格式。",
    "english": "Just a reminder that the assignment is due tomorrow. Could you upload your section by 9 pm tonight so we still have time to consolidate and review it?"
  },
  {
    "d": "家庭",
    "r": "伴侶",
    "g": "談家務",
    "t": "你覺得家務分配長期不平衡",
    "x": "談具體工作量，不把問題上升成人格",
    "formal": "我想跟你重新分一下家務。最近做飯、洗衣和收拾大多集中在我這邊，我有點吃不消。我們能不能把固定項目重新分配一下？",
    "natural": "我最近真的有點被家務壓住了。做飯、洗衣、收拾大多都在我這邊，我想跟你重新分一下。",
    "eq": "我不是想算誰做得多誰做得少，只是現在這個安排讓我有點累。我希望我們一起調整成兩個人都能長期維持的方式。",
    "direct": "現在家務分配不平衡，我希望今天把固定項目重新分清楚。",
    "dark": "我想確認一下，我們目前是共同生活，還是我不小心升級成了免費後勤部。",
    "roast": "家務這個專案目前只有一個活躍帳號，我想申請增加一名正式成員。",
    "cantonese": "我想同你重新分一分家務。最近煮飯、洗衫同執嘢好多都落咗喺我度，我有啲頂唔順。",
    "english": "I’d like us to rebalance the household chores. Cooking, laundry and tidying have mostly fallen on me lately, and it’s becoming difficult to sustain."
  },
  {
    "d": "家庭",
    "r": "父母",
    "g": "建立界線",
    "t": "父母頻繁追問你的收入和存款",
    "x": "不吵架，但明確私人財務邊界",
    "formal": "我知道你們是關心我，不過具體收入和存款我想自己管理。如果遇到需要家庭一起商量的重大財務事情，我一定會主動說。",
    "natural": "我知道你們是擔心我，但具體收入和存款我想先自己管。有真的需要一起商量的事我會跟你們說。",
    "eq": "你們問這些我知道是出於關心。我現在也有自己的財務規劃，所以具體數字我想保留一點私人空間，重要的事情我不會瞞你們。",
    "direct": "具體收入和存款我不想公開討論，但需要家庭共同決策的事情我會主動說。",
    "dark": "我的財務目前運作正常，所以暫時不開家庭版財報發布會。",
    "roast": "等我哪天上市了，一定第一時間給你們發年報。現在先讓我的存款保持一點神秘感。",
    "cantonese": "我知你哋係關心我，不過收入同存款嘅具體數字我想自己管理。有重要財務決定我一定會同你哋講。",
    "english": "I know you’re asking because you care, but I’d prefer to keep the exact details of my income and savings private. I’ll always discuss major family financial decisions with you."
  },
  {
    "d": "育兒",
    "r": "孩子",
    "g": "催作業",
    "t": "孩子一直拖著不開始寫作業",
    "x": "減少命令，把任務拆到能開始",
    "formal": "我們先不要求一次做完。你選一科，先做 15 分鐘。15 分鐘後我們再看要不要休息。",
    "natural": "先不用想全部做完。你挑一科，我們先做 15 分鐘，開始了再說。",
    "eq": "我猜你現在一想到全部作業就覺得很煩。我們先把第一步變小一點，你選最容易的一科，先做 15 分鐘。",
    "direct": "現在先選一科，做 15 分鐘。做完這段再休息。",
    "dark": "作業不會因為我們一起看著它就自己完成，所以先處理最小的一塊。",
    "roast": "作業已經在桌上躺很久了，它看起來沒有自動完成的功能。我們先救 15 分鐘。",
    "cantonese": "唔使諗住一次過做晒。你揀一科，先做 15 分鐘，做完呢段再抖一抖。",
    "english": "You don’t have to finish everything at once. Pick one subject and work on it for 15 minutes. We’ll decide the next step after that."
  },
  {
    "d": "育兒",
    "r": "孩子",
    "g": "處理發脾氣",
    "t": "孩子因為不能繼續玩手機而大哭",
    "x": "承認情緒，但不撤回已說好的界線",
    "formal": "我知道你現在很生氣，因為你還想繼續玩。生氣可以，但今天的手機時間已經結束。你可以先哭一會，我會在這裡。",
    "natural": "我知道你還想玩，所以現在很生氣。可以生氣，但今天手機時間真的到這裡了。我陪你緩一下。",
    "eq": "你不是壞，也不是不聽話，你只是很難停下來。我懂。但我們剛才約好的時間還是算數。",
    "direct": "我知道你不高興，但今天不再加手機時間。",
    "dark": "情緒可以加時，手機不能加時。",
    "roast": "手機今天已經下班了，你可以先對它表示不滿，但它不會復工。",
    "cantonese": "我知你仲想玩，所以而家好嬲。你可以嬲，但今日手機時間已經完咗。我陪你抖一陣。",
    "english": "I know you’re upset because you want more screen time. It’s okay to be upset, but today’s screen time is still finished. I’ll stay with you while you calm down."
  },
  {
    "d": "長輩",
    "r": "長輩",
    "g": "拒絕催婚",
    "t": "長輩反覆催你結婚",
    "x": "停止重複辯論，建立柔和界線",
    "formal": "謝謝你關心我的人生安排。結婚這件事我會認真考慮，但希望由我自己決定時間。如果有好消息，我一定會主動跟你說。",
    "natural": "我知道你是關心我啦，不過這件事我自己有安排。有消息我一定第一時間告訴你，不用每次見面都考我。",
    "eq": "我知道你希望我過得穩定，這份心意我收到了。只是結婚這件事越催我反而壓力越大，讓我自己處理會比較好。",
    "direct": "結婚時間我會自己決定，之後這個話題先不用每次見面都問。",
    "dark": "放心，這件事如果真的有進度，應該不至於需要靠每次飯局人工刷新。",
    "roast": "目前婚姻系統沒有更新，有版本發布我會主動推送，不用每天手動檢查。",
    "cantonese": "我知你係關心我，不過結婚呢件事我自己有安排。有好消息我一定第一時間話你知，唔使次次見面都問啦。",
    "english": "I know you’re asking because you care. I’ll make the decision about marriage in my own time, and I promise I’ll tell you when there’s news."
  },
  {
    "d": "長輩",
    "r": "長輩",
    "g": "糾正假消息",
    "t": "長輩在家族群轉發明顯假消息",
    "x": "避免直接嘲笑，提供核實方式",
    "formal": "這條資訊我查了一下，目前沒有看到官方來源支持，而且其中 XX 的說法與官方資料不一致。先不要轉發比較穩妥。",
    "natural": "這條我剛查了下，好像不太對，官方沒有這個說法。先別轉吧，免得大家誤會。",
    "eq": "這種消息做得很像真的，很容易中招。我剛好查了一下，官方目前沒有這個通知，我把正確來源發群裡。",
    "direct": "這條是假消息，官方資料與它不一致，先停止轉發。",
    "dark": "這條消息最大的來源目前看起來就是『有人轉給我』，所以先不幫它擴大業務。",
    "roast": "這條消息跑得比官方快太多了，通常這不是它比較有能力。",
    "cantonese": "呢條我啱啱查過，官方暫時冇呢個講法，而且有啲內容對唔上。暫時唔好再轉會穩陣啲。",
    "english": "I checked this and couldn’t find an official source supporting it. Some details also conflict with official information, so it’s safer not to forward it."
  },
  {
    "d": "朋友",
    "r": "朋友",
    "g": "拒絕借錢",
    "t": "朋友向你借一筆你不想借的錢",
    "x": "不虛構理由，不留模糊期待",
    "formal": "抱歉，這筆錢我這邊不方便借出。我不想因為金錢問題影響我們的關係，希望你理解。",
    "natural": "這筆我真的不方便借，不是針對你，我只是自己有個原則，朋友之間盡量不做大額借貸。",
    "eq": "我知道你現在可能真的有需要，也謝謝你願意開口。但這筆金額我沒有辦法借，希望你不要因為我拒絕而覺得我不在乎你。",
    "direct": "抱歉，這筆錢我不借。",
    "dark": "我希望我們的友情不要突然多出本金、利息和還款日三個新角色。",
    "roast": "我們的友情目前運作良好，我想繼續維持無金融產品版本。",
    "cantonese": "唔好意思，呢筆錢我唔方便借。我唔想因為金錢問題影響我哋關係，希望你明白。",
    "english": "I’m sorry, but I’m not comfortable lending this amount. I value our friendship and don’t want money to complicate it."
  }
];
