import {createCardSDK} from './card-sdk.js';

const active=new WeakMap();
const cssCache=new Map();

async function ensureStyle(path){if(!path||cssCache.has(path))return;const link=document.createElement('link');link.rel='stylesheet';link.href=new URL(path,location.href).href;const ready=new Promise((resolve,reject)=>{link.onload=resolve;link.onerror=()=>reject(new Error(`style load failed: ${path}`))});document.head.appendChild(link);await ready;cssCache.set(path,link)}

export async function closeApp(layer){const rec=active.get(layer);if(rec){rec.abort.abort();try{await rec.cleanup?.()}catch(error){console.warn('[WebDesk V2 app cleanup]',error)}try{rec.sdk.destroy()}catch{}active.delete(layer)}layer.replaceChildren();document.body.classList.remove('wd-app-open')}

export async function openApp(layer,manifest,platform){await closeApp(layer);const entry=manifest?.entry?.[platform];if(!entry?.app)throw new Error(`${manifest?.id||'card'} missing ${platform} app entry`);const abort=new AbortController();const shell=document.createElement('section');shell.className=`wd-window wd-window-${platform}`;shell.innerHTML=`<header class="wd-window-head"><strong>${manifest.icon||'•'} ${manifest.name?.['zh-HK']||manifest.id}</strong><button type="button" data-close-window>關閉</button></header><div class="wd-window-body" data-app-mount aria-busy="true"></div>`;layer.replaceChildren(shell);document.body.classList.add('wd-app-open');shell.querySelector('[data-close-window]').onclick=()=>closeApp(layer);const mount=shell.querySelector('[data-app-mount]');const sdk=createCardSDK({manifest,platform,host:mount});active.set(layer,{abort,sdk,cleanup:null});try{if(entry.appStyle)await ensureStyle(`./cards/${manifest.id}/${entry.appStyle}`);const url=new URL(`./cards/${manifest.id}/${entry.app}`,location.href);url.searchParams.set('v',manifest.version);const mod=await Promise.race([import(url.href),new Promise((_,reject)=>setTimeout(()=>reject(new Error('app load timeout')),10000))]);if(abort.signal.aborted)return;mount.replaceChildren();const cleanup=await mod.mount?.({host:mount,sdk,manifest,platform,signal:abort.signal});const rec=active.get(layer);if(rec)rec.cleanup=typeof cleanup==='function'?cleanup:null}catch(error){if(!abort.signal.aborted)mount.innerHTML=`<div class="wd-card-error"><strong>App 載入失敗</strong><small>${String(error?.message||error)}</small></div>`}finally{mount.removeAttribute('aria-busy')}}
