import{layers,layerById,fetchPointWeather,fetchWeatherGrid,fetchWindField,supportsVisualOverlay,supportsWindField,DEFAULT_CENTER}from'../shared/global-weather-service.js';
import{mountMap,basemaps}from'../shared/map-engine.js';
export async function mount({host,signal}){
  let active='wind',data=null,timer=0,mapApi=null,weatherAbort=null,overlayAbort=null,overlayTimer=0,overlayMeta=null,view={lat:DEFAULT_CENTER.lat,lon:DEFAULT_CENTER.lon,zoom:4.5},mapState={source:'OpenFreeMap'};
  host.innerHTML=`<section class="gw-app gw-desktop-app"><div class="gw-map" data-map aria-label="全球天氣地圖"></div><div class="gw-top-glass"><strong>全球天氣</strong><span data-place>深圳附近</span></div><nav class="gw-layer-dock" aria-label="氣象圖層">${layers.map((l,i)=>`<button type="button" data-layer="${l.id}" class="${i?'':'on'}">${l.label}</button>`).join('')}</nav><nav class="gw-base-dock" aria-label="底圖">${basemaps.map((b,i)=>`<button type="button" data-base="${b.id}" class="${b.id==='weather'?'on':''}">${b.label}</button>`).join('')}</nav><div class="gw-readout" data-readout>讀取即時資料…</div><div class="gw-source" data-source></div></section>`;
  const readout=host.querySelector('[data-readout]'),source=host.querySelector('[data-source]');
  const fieldText=()=>overlayMeta?(supportsWindField(active)?` · ${active==='gust'?'陣風':'風'}場 ${overlayMeta.sampleCount} 點`:` · 圖層 ${overlayMeta.sampleCount} 點`):' · 流場載入中…';
  const paint=()=>{if(!data)return;const l=layerById(active),v=data.summary[active],t=String(data.updatedAt||'').slice(11,16)||'—';readout.textContent=`${l.label} ${v}${v==='—'?'':' '+l.unit}`;source.textContent=`天氣 ${data.source} · 更新 ${t} · 地圖 ${mapState.source||'—'}${fieldText()}`};
  const loadField=(delay=240)=>{clearTimeout(overlayTimer);overlayMeta=null;paint();overlayTimer=setTimeout(async()=>{overlayAbort?.abort();overlayAbort=new AbortController();try{let field=null;if(supportsWindField(active)){mapApi?.clearWeatherOverlay?.();field=await fetchWindField({...view,layer:active,signal:overlayAbort.signal,size:7});if(signal?.aborted||field?.layer!==active)return;overlayMeta=field;mapApi?.setWindField?.(active,field.geojson)}else if(supportsVisualOverlay(active)){mapApi?.clearWindField?.();field=await fetchWeatherGrid({...view,layer:active,signal:overlayAbort.signal});if(signal?.aborted||field?.layer!==active)return;overlayMeta=field;mapApi?.setWeatherOverlay?.(active,field.geojson)}paint()}catch(e){if(!signal?.aborted&&e?.name!=='AbortError'){overlayMeta=null;mapApi?.clearWeatherOverlay?.();mapApi?.clearWindField?.();source.textContent=`圖層暫時不可用 · 地圖 ${mapState.source||'—'}`}}},delay)};
  const refresh=({lat,lon,zoom=view.zoom})=>{view={lat,lon,zoom};clearTimeout(timer);timer=setTimeout(async()=>{weatherAbort?.abort();weatherAbort=new AbortController();try{data=await fetchPointWeather(lat,lon,{signal:weatherAbort.signal});if(!signal?.aborted)paint()}catch(e){if(!signal?.aborted&&e?.name!=='AbortError'){readout.textContent='即時資料暫時不可用';source.textContent=''}}},180);loadField(250)};
  mapApi=await mountMap(host.querySelector('[data-map]'),{center:[DEFAULT_CENTER.lon,DEFAULT_CENTER.lat],zoom:4.5,basemap:'weather',onMove:refresh,onStatus:s=>{mapState=s||mapState;paint()}});
  refresh(view);loadField(0);
  host.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>{active=b.dataset.layer;overlayMeta=null;host.querySelectorAll('[data-layer]').forEach(x=>x.classList.toggle('on',x===b));paint();loadField(0)});
  host.querySelectorAll('[data-base]').forEach(b=>b.onclick=()=>{mapApi?.setBasemap(b.dataset.base);host.querySelectorAll('[data-base]').forEach(x=>x.classList.toggle('on',x===b))});
  return()=>{clearTimeout(timer);clearTimeout(overlayTimer);weatherAbort?.abort();overlayAbort?.abort();mapApi?.destroy?.()};
}
