const FALLBACK={place:'天氣預覽',temperature:24,feelsLike:25,code:3,high:27,low:21,rain:20,wind:12,gust:20,humidity:72,uv:4,sunrise:'06:18',sunset:'18:32',updatedAt:null,hourly:[{time:'現在',temp:24,rain:20,code:3},{time:'1小時',temp:25,rain:20,code:3},{time:'2小時',temp:25,rain:30,code:61},{time:'3小時',temp:24,rain:40,code:61}],forecast:[{label:'今天',high:27,low:21,code:3},{label:'明天',high:28,low:22,code:2},{label:'後天',high:27,low:22,code:61}]};
const SAVED_KEY='webdesk:v2:card:weather:locations:v1';
export function weatherIcon(code){if(code===0)return'☀️';if([1,2].includes(code))return'🌤️';if(code===3)return'☁️';if([45,48].includes(code))return'🌫️';if(code>=51&&code<=67)return'🌧️';if(code>=71&&code<=77)return'🌨️';if(code>=80&&code<=82)return'🌦️';if(code>=95)return'⛈️';return'☁️'}
export function weatherLabel(code){if(code===0)return'晴朗';if([1,2].includes(code))return'晴間多雲';if(code===3)return'多雲';if([45,48].includes(code))return'有霧';if(code>=51&&code<=67)return'有雨';if(code>=71&&code<=77)return'降雪';if(code>=80&&code<=82)return'驟雨';if(code>=95)return'雷暴';return'天氣'}
export function weatherInsight(data){const next=(data.hourly||[]).slice(1,5),wet=next.find(x=>x.rain>=50);if(wet)return `${wet.time} 降雨 ${wet.rain}%`;if(data.gust>=45)return `陣風最高 ${data.gust} km/h`;if(data.uv>=7)return `UV ${data.uv}，注意防曬`;const delta=(next.at(-1)?.temp??data.temperature)-data.temperature;if(delta>=3)return `數小時內升溫約 ${delta}°`;if(delta<=-3)return `數小時內降溫約 ${Math.abs(delta)}°`;return''}
function locate(signal){return new Promise(resolve=>{if(!navigator.geolocation)return resolve(null);let done=false;const finish=v=>{if(done)return;done=true;resolve(v)};const timer=setTimeout(()=>finish(null),2500);signal?.addEventListener('abort',()=>{clearTimeout(timer);finish(null)},{once:true});navigator.geolocation.getCurrentPosition(p=>{clearTimeout(timer);finish({lat:p.coords.latitude,lon:p.coords.longitude})},()=>{clearTimeout(timer);finish(null)},{enableHighAccuracy:false,timeout:2200,maximumAge:900000})})}
function clock(value){if(!value)return'--:--';return String(value).slice(-5)}
export async function searchCities(query,{signal}={}){const q=String(query||'').trim();if(q.length<2)return[];const u=new URL('https://geocoding-api.open-meteo.com/v1/search');u.search=new URLSearchParams({name:q,count:'8',language:'zh',format:'json'});const r=await fetch(u,{signal});if(!r.ok)throw new Error(`geocoding ${r.status}`);const d=await r.json();return(d.results||[]).map(x=>({id:`${x.latitude},${x.longitude}`,name:x.name,region:[x.admin1,x.country].filter(Boolean).join(' · '),lat:x.latitude,lon:x.longitude,timezone:x.timezone}))}
export function savedLocations(){try{const v=JSON.parse(localStorage.getItem(SAVED_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return[]}}
export function saveLocation(location){const list=savedLocations().filter(x=>x.id!==location.id);list.unshift(location);try{localStorage.setItem(SAVED_KEY,JSON.stringify(list.slice(0,8)))}catch{}return list.slice(0,8)}
export function removeLocation(id){const list=savedLocations().filter(x=>x.id!==id);try{localStorage.setItem(SAVED_KEY,JSON.stringify(list))}catch{}return list}
async function forecast(position,place,signal){const params=new URLSearchParams({latitude:String(position.lat),longitude:String(position.lon),current:'temperature_2m,apparent_temperature,relative_humidity_2m,weather_code,wind_speed_10m,wind_gusts_10m',hourly:'temperature_2m,precipitation_probability,weather_code',daily:'weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,uv_index_max,sunrise,sunset',timezone:'auto',forecast_days:'7'});const response=await fetch(`https://api.open-meteo.com/v1/forecast?${params}`,{signal});if(!response.ok)throw new Error(`weather ${response.status}`);const d=await response.json(),currentTime=d.current?.time;let start=Math.max(0,(d.hourly?.time||[]).findIndex(t=>t>=currentTime));if(start<0)start=0;const hourly=(d.hourly?.time||[]).slice(start,start+12).map((t,i)=>({time:i===0?'現在':clock(t),temp:Math.round(d.hourly.temperature_2m[start+i]),rain:Math.round(d.hourly.precipitation_probability[start+i]??0),code:d.hourly.weather_code[start+i]}));return{place,temperature:Math.round(d.current?.temperature_2m??24),feelsLike:Math.round(d.current?.apparent_temperature??24),humidity:Math.round(d.current?.relative_humidity_2m??0),code:d.current?.weather_code??3,high:Math.round(d.daily?.temperature_2m_max?.[0]??27),low:Math.round(d.daily?.temperature_2m_min?.[0]??21),rain:Math.round(d.daily?.precipitation_probability_max?.[0]??0),wind:Math.round(d.current?.wind_speed_10m??0),gust:Math.round(d.current?.wind_gusts_10m??0),uv:Math.round((d.daily?.uv_index_max?.[0]??0)*10)/10,sunrise:clock(d.daily?.sunrise?.[0]),sunset:clock(d.daily?.sunset?.[0]),updatedAt:currentTime||new Date().toISOString(),hourly,forecast:(d.daily?.time||[]).slice(0,7).map((_,i)=>({label:i===0?'今天':i===1?'明天':new Date(d.daily.time[i]).toLocaleDateString('zh-HK',{weekday:'short'}),high:Math.round(d.daily.temperature_2m_max[i]),low:Math.round(d.daily.temperature_2m_min[i]),code:d.daily.weather_code[i]})),isFallback:false,source:'Open-Meteo'}}
export async function loadWeather({signal,allowLocation=true,location=null}={}){const position=location?{lat:location.lat,lon:location.lon}:allowLocation?await locate(signal):null;if(!position)return{...FALLBACK,updatedAt:new Date().toISOString(),isFallback:true,needsLocation:true,source:null};try{return await forecast(position,location?.name||'目前位置',signal)}catch(error){if(signal?.aborted)throw error;return{...FALLBACK,updatedAt:new Date().toISOString(),isFallback:true,source:null}}}
